/*
 * dns_record_type.h
 *
 * Type of DNS Record
 */

#ifndef _dns_record_type_H_
#define _dns_record_type_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct dns_record_type_t dns_record_type_t;


// Enum  for dns_record_type

typedef enum { interserver_management_api_dns_record_type__NULL = 0, interserver_management_api_dns_record_type__A, interserver_management_api_dns_record_type__A6, interserver_management_api_dns_record_type__AAAA, interserver_management_api_dns_record_type__AFSDB, interserver_management_api_dns_record_type__ALIAS, interserver_management_api_dns_record_type__CAA, interserver_management_api_dns_record_type__CDNSKEY, interserver_management_api_dns_record_type__CDS, interserver_management_api_dns_record_type__CERT, interserver_management_api_dns_record_type__CNAME, interserver_management_api_dns_record_type__DHCID, interserver_management_api_dns_record_type__DLV, interserver_management_api_dns_record_type__DNSKEY, interserver_management_api_dns_record_type__DNAME, interserver_management_api_dns_record_type__DS, interserver_management_api_dns_record_type__EUI48, interserver_management_api_dns_record_type__EUI64, interserver_management_api_dns_record_type__HINFO, interserver_management_api_dns_record_type__IPSECKEY, interserver_management_api_dns_record_type__KEY, interserver_management_api_dns_record_type__KX, interserver_management_api_dns_record_type__LOC, interserver_management_api_dns_record_type__MAILA, interserver_management_api_dns_record_type__MAILB, interserver_management_api_dns_record_type__MINFO, interserver_management_api_dns_record_type__MR, interserver_management_api_dns_record_type__MX, interserver_management_api_dns_record_type__NAPTR, interserver_management_api_dns_record_type__NS, interserver_management_api_dns_record_type__NSEC, interserver_management_api_dns_record_type__NSEC3, interserver_management_api_dns_record_type__NSEC3PARAM, interserver_management_api_dns_record_type__OPENPGPKEY, interserver_management_api_dns_record_type__OPT, interserver_management_api_dns_record_type__PTR, interserver_management_api_dns_record_type__RKEY, interserver_management_api_dns_record_type__RP, interserver_management_api_dns_record_type__RRSIG, interserver_management_api_dns_record_type__SIG, interserver_management_api_dns_record_type__SOA, interserver_management_api_dns_record_type__SPF, interserver_management_api_dns_record_type__SRV, interserver_management_api_dns_record_type__SSHFP, interserver_management_api_dns_record_type__TLSA, interserver_management_api_dns_record_type__TKEY, interserver_management_api_dns_record_type__TSIG, interserver_management_api_dns_record_type__TXT, interserver_management_api_dns_record_type__WKS, interserver_management_api_dns_record_type__URI⏎ } interserver_management_api_dns_record_type__e;

char* dns_record_type_dns_record_type_ToString(interserver_management_api_dns_record_type__e dns_record_type);

interserver_management_api_dns_record_type__e dns_record_type_dns_record_type_FromString(char* dns_record_type);

cJSON *dns_record_type_convertToJSON(interserver_management_api_dns_record_type__e dns_record_type);

interserver_management_api_dns_record_type__e dns_record_type_parseFromJSON(cJSON *dns_record_typeJSON);

#endif /* _dns_record_type_H_ */

