#
# InterServer Management API
# # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
# Version: 0.9.0
# Contact: support@interserver.net
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

version: 1.0.{build}
image:
  - Visual Studio 2019 # PWSH 7.x
  #- Visual Studio 2017 # PS 5.x, PWSH 6.x
  #- Ubuntu # PWSH 6.x
  # ref: https://www.appveyor.com/docs/windows-images-software/
install:
  - pwsh: $PSVersionTable.PSVersion
  - pwsh: Install-Module Pester -Force -Scope CurrentUser
build: off
test_script:
  - pwsh: |
      .\Build.ps1
      Import-Module -Name '.\src\PSOpenAPITools'
      $Result = Invoke-Pester -PassThru
      if ($Result.FailedCount -gt 0) {
          $host.SetShouldExit($Result.FailedCount)
          exit $Result.FailedCount
      }
deploy_script:
  - pwsh: |
      if ($env:APPVEYOR_REPO_TAG -eq $true -and $null -ne $env:NuGetApiKey) {
          .\Build.ps1
          try {
              Publish-Module -NuGetApiKey $env:NuGetApiKey -Path .\src\PSOpenAPITools\ -Confirm:$False -Verbose
              Write-Host "Successfully published the PowerShell module."
          } catch {
              $host.SetShouldExit($LastExitCode)
              Write-Host "Error when running Publish-Module:"
              Write-Host $_
              exit
          }
      }
