/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AccountInfoOauthConfigProviders

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * OAuth integration configuration including callback URL and available providers.
 *
 * @param callback 
 * @param providers 
 */


data class AccountInfoOauthConfig (

    @Json(name = "callback")
    val callback: kotlin.String,

    @Json(name = "providers")
    val providers: AccountInfoOauthConfigProviders

) {


}

