# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BillingPrepayRequest")

model_instance <- BillingPrepayRequest$new()

test_that("module", {
  # tests for the property `module` (character)
  # Module the prepay should be applied to (for example &#x60;default&#x60;).

  # uncomment below to test the property
  #expect_equal(model.instance$`module`, "EXPECTED_RESULT")
})

test_that("amount", {
  # tests for the property `amount` (numeric)
  # Amount to add to prepay balance. Minimum is $10.

  # uncomment below to test the property
  #expect_equal(model.instance$`amount`, "EXPECTED_RESULT")
})

test_that("automatic_use", {
  # tests for the property `automatic_use` (character)
  # Whether the prepay balance should be used automatically.

  # uncomment below to test the property
  #expect_equal(model.instance$`automatic_use`, "EXPECTED_RESULT")
})
