# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ServerOrderBandwidthLi")

model_instance <- ServerOrderBandwidthLi$new()

test_that("15", {
  # tests for the property `15` (ServerOrderBandwidth)

  # uncomment below to test the property
  #expect_equal(model.instance$`15`, "EXPECTED_RESULT")
})
