//
// LicensesOrderServiceTypes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/** Types of license services */
public struct LicensesOrderServiceTypes: Codable {


    public var licensesOrderServiceTypes11482: LicensesOrderServiceTypes11482?
    public init(licensesOrderServiceTypes11482: LicensesOrderServiceTypes11482? = nil) { 
        self.licensesOrderServiceTypes11482 = licensesOrderServiceTypes11482
    }
    public enum CodingKeys: String, CodingKey { 
        case licensesOrderServiceTypes11482 = "LicensesOrderServiceTypes11482"
    }

}
