export * from './account.service';
import { AccountService } from './account.service';
export * from './backups.service';
import { BackupsService } from './backups.service';
export * from './billing.service';
import { BillingService } from './billing.service';
export * from './dNS.service';
import { DNSService } from './dNS.service';
export * from './domains.service';
import { DomainsService } from './domains.service';
export * from './floatingIPs.service';
import { FloatingIPsService } from './floatingIPs.service';
export * from './licenses.service';
import { LicensesService } from './licenses.service';
export * from './mail.service';
import { MailService } from './mail.service';
export * from './public.service';
import { PublicService } from './public.service';
export * from './quickServers.service';
import { QuickServersService } from './quickServers.service';
export * from './sSLCertificates.service';
import { SSLCertificatesService } from './sSLCertificates.service';
export * from './scrubIps.service';
import { ScrubIpsService } from './scrubIps.service';
export * from './servers.service';
import { ServersService } from './servers.service';
export * from './tickets.service';
import { TicketsService } from './tickets.service';
export * from './vPS.service';
import { VPSService } from './vPS.service';
export * from './webhosting.service';
import { WebhostingService } from './webhosting.service';
export const APIS = [AccountService, BackupsService, BillingService, DNSService, DomainsService, FloatingIPsService, LicensesService, MailService, PublicService, QuickServersService, SSLCertificatesService, ScrubIpsService, ServersService, TicketsService, VPSService, WebhostingService];
