## AccountApi

### Change Account Username
## Change Account Username
POST https://my.interserver.net/apiv2/account/username
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Unlink OAuth Account
## Unlink OAuth Account
DELETE https://my.interserver.net/apiv2/account/oauth/{{name}}
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Disable Two-Factor Authentication
## Disable Two-Factor Authentication
DELETE https://my.interserver.net/apiv2/account/2fa
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Remove IP Access Restriction
## Remove IP Access Restriction
PATCH https://my.interserver.net/apiv2/account/iplimits
Content-Type: application/json
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

{
 "start": "<string>",
 "end": "<string>"
}


### Retrieve Account Details
## Retrieve Account Details
GET https://my.interserver.net/apiv2/account
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Get Two-Factor Setup Data
## Get Two-Factor Setup Data
GET https://my.interserver.net/apiv2/account/2fa
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Get Home Data
## Get Home Data
GET https://my.interserver.net/apiv2/home
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Search Autocomplete
## Search Autocomplete
GET https://my.interserver.net/apiv2/search
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Log Out
## Log Out
GET https://my.interserver.net/apiv2/logout
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Logout of OAuth
## Logout of OAuth
GET https://my.interserver.net/apiv2/account/oauth/{{name}}/logout
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Generate New API Key
## Generate New API Key
POST https://my.interserver.net/apiv2/account/apikey
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Update Account Feature Flags
## Update Account Feature Flags
POST https://my.interserver.net/apiv2/account/features
Content-Type: multipart/form-data
Content-Type: application/json
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Update Account Information
## Update Account Information
POST https://my.interserver.net/apiv2/account
Content-Type: multipart/form-data
Content-Type: application/json
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Add IP Access Restriction
## Add IP Access Restriction
POST https://my.interserver.net/apiv2/account/iplimits
Content-Type: multipart/form-data
Content-Type: application/json
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Change Account Password
## Change Account Password
POST https://my.interserver.net/apiv2/account/password
Content-Type: multipart/form-data
Content-Type: application/json
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Update SSH Keys
## Update SSH Keys
POST https://my.interserver.net/apiv2/account/sshkey
Content-Type: multipart/form-data
Content-Type: application/json
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Enable Two-Factor Authentication
## Enable Two-Factor Authentication
POST https://my.interserver.net/apiv2/account/2fa
Content-Type: multipart/form-data
Content-Type: application/json
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}
