## LicensesApi

### Place License Order
## Place License Order
POST https://my.interserver.net/apiv2/licenses/order
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Get License
## Get License
GET https://my.interserver.net/apiv2/licenses/{{id}}
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Get License Invoices
## Get License Invoices
GET https://my.interserver.net/apiv2/licenses/{{id}}/invoices
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### List Licenses
## List Licenses
GET https://my.interserver.net/apiv2/licenses
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Get License Order Information for Category
## Get License Order Information for Category
GET https://my.interserver.net/apiv2/licenses/order/{{catTag}}
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Resend License Welcome Email
## Resend License Welcome Email
GET https://my.interserver.net/apiv2/licenses/{{id}}/welcome_email
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Get License Order Information
## Get License Order Information
GET https://my.interserver.net/apiv2/licenses/order
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Cancel License
## Cancel License
DELETE https://my.interserver.net/apiv2/licenses/{{id}}
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Change License IP
## Change License IP
POST https://my.interserver.net/apiv2/licenses/{{id}}/change_ip
Content-Type: application/json
Content-Type: multipart/form-data
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

{
 "ip": "<string>"
}


### Validate License Order
## Validate License Order
PUT https://my.interserver.net/apiv2/licenses/order
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}

### Update License
## Update License
POST https://my.interserver.net/apiv2/licenses/{{id}}
Accept: application/json
Cookie: sessionid={{cookieKey}}
X-API-KEY: {{apiKey}}
sessionid: {{apiKey}}
