/* tslint:disable */
/* eslint-disable */
/**
 * InterServer Management API
 * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuickserverOrderTemplates } from './QuickserverOrderTemplates';
import {
    QuickserverOrderTemplatesFromJSON,
    QuickserverOrderTemplatesFromJSONTyped,
    QuickserverOrderTemplatesToJSON,
    QuickserverOrderTemplatesToJSONTyped,
} from './QuickserverOrderTemplates';
import type { QuickserverOrderDistroSel } from './QuickserverOrderDistroSel';
import {
    QuickserverOrderDistroSelFromJSON,
    QuickserverOrderDistroSelFromJSONTyped,
    QuickserverOrderDistroSelToJSON,
    QuickserverOrderDistroSelToJSONTyped,
} from './QuickserverOrderDistroSel';
import type { QuickserverOrderServerDetails } from './QuickserverOrderServerDetails';
import {
    QuickserverOrderServerDetailsFromJSON,
    QuickserverOrderServerDetailsFromJSONTyped,
    QuickserverOrderServerDetailsToJSON,
    QuickserverOrderServerDetailsToJSONTyped,
} from './QuickserverOrderServerDetails';
import type { QuickserverOrderVersion } from './QuickserverOrderVersion';
import {
    QuickserverOrderVersionFromJSON,
    QuickserverOrderVersionFromJSONTyped,
    QuickserverOrderVersionToJSON,
    QuickserverOrderVersionToJSONTyped,
} from './QuickserverOrderVersion';

/**
 * Available QuickServer options and OS templates for ordering a new QuickServer.
 * @export
 * @interface QuickserverOrder
 */
export interface QuickserverOrder {
    /**
     * Quickserver ID.
     * @type {string}
     * @memberof QuickserverOrder
     */
    qs_id?: string;
    /**
     * 
     * @type {QuickserverOrderServerDetails}
     * @memberof QuickserverOrder
     */
    server_details?: QuickserverOrderServerDetails;
    /**
     * 
     * @type {QuickserverOrderTemplates}
     * @memberof QuickserverOrder
     */
    templates?: QuickserverOrderTemplates;
    /**
     * 
     * @type {QuickserverOrderVersion}
     * @memberof QuickserverOrder
     */
    version?: QuickserverOrderVersion;
    /**
     * 
     * @type {QuickserverOrderDistroSel}
     * @memberof QuickserverOrder
     */
    distro_sel?: QuickserverOrderDistroSel;
}

/**
 * Check if a given object implements the QuickserverOrder interface.
 */
export function instanceOfQuickserverOrder(value: object): value is QuickserverOrder {
    return true;
}

export function QuickserverOrderFromJSON(json: any): QuickserverOrder {
    return QuickserverOrderFromJSONTyped(json, false);
}

export function QuickserverOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuickserverOrder {
    if (json == null) {
        return json;
    }
    return {
        
        'qs_id': json['qs_id'] == null ? undefined : json['qs_id'],
        'server_details': json['server_details'] == null ? undefined : QuickserverOrderServerDetailsFromJSON(json['server_details']),
        'templates': json['templates'] == null ? undefined : QuickserverOrderTemplatesFromJSON(json['templates']),
        'version': json['version'] == null ? undefined : QuickserverOrderVersionFromJSON(json['version']),
        'distro_sel': json['distro_sel'] == null ? undefined : QuickserverOrderDistroSelFromJSON(json['distro_sel']),
    };
}

export function QuickserverOrderToJSON(json: any): QuickserverOrder {
    return QuickserverOrderToJSONTyped(json, false);
}

export function QuickserverOrderToJSONTyped(value?: QuickserverOrder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'qs_id': value['qs_id'],
        'server_details': QuickserverOrderServerDetailsToJSON(value['server_details']),
        'templates': QuickserverOrderTemplatesToJSON(value['templates']),
        'version': QuickserverOrderVersionToJSON(value['version']),
        'distro_sel': QuickserverOrderDistroSelToJSON(value['distro_sel']),
    };
}

