/**
 * InterServer Management API
 * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAIBillingApi_H
#define OAI_OAIBillingApi_H

#include "OAIHelpers.h"
#include "OAIHttpRequest.h"
#include "OAIServerConfiguration.h"
#include "OAIOauth.h"

#include "OAIAffiliateBannerRow.h"
#include "OAIAffiliateTrafficRow.h"
#include "OAIBillingAddCcRequest.h"
#include "OAIBillingInvoiceDetail.h"
#include "OAIBillingInvoiceList.h"
#include "OAIBillingPaymentMethodRequest.h"
#include "OAIBillingPrepayRequest.h"
#include "OAIBillingVerifyCcRequest.h"
#include "OAIGetAccountInfo_401_response.h"
#include "OAIInitiatePayment_200_response.h"
#include "OAIInvoice.h"
#include "OAIMonthlyCounts.h"
#include "OAIObject.h"
#include "OAIStatusMonthlyBreakdown.h"
#include "OAISuccessTextResponse.h"
#include "OAITextResponse.h"
#include <QString>

#include <QObject>
#include <QByteArray>
#include <QStringList>
#include <QList>
#include <QNetworkAccessManager>

namespace OpenAPI {

class OAIBillingApi : public QObject {
    Q_OBJECT

public:
    OAIBillingApi(const int timeOut = 0);
    ~OAIBillingApi();

    void initializeServerConfigs();
    int setDefaultServerValue(int serverIndex,const QString &operation, const QString &variable,const QString &val);
    void setServerIndex(const QString &operation, int serverIndex);
    void setServerIndex(int serverIndex);
    void setApiKey(const QString &apiKeyName, const QString &apiKey);
    void setBearerToken(const QString &token);
    void setUsername(const QString &username);
    void setPassword(const QString &password);
    void setTimeOut(const int timeOut);
    void setWorkingDirectory(const QString &path);
    void setNetworkAccessManager(QNetworkAccessManager* manager);
    int addServerConfiguration(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables = QMap<QString, OAIServerVariable>());
    void setNewServerForAllOperations(const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables =  QMap<QString, OAIServerVariable>());
    void setNewServer(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables =  QMap<QString, OAIServerVariable>());
    void addHeaders(const QString &key, const QString &value);
    void enableRequestCompression();
    void enableResponseCompression();
    void abortRequests();
    QString getParamStylePrefix(const QString &style);
    QString getParamStyleSuffix(const QString &style);
    QString getParamStyleDelimiter(const QString &style, const QString &name, bool isExplode);

    /**
    * @param[in]  name QString [optional]
    * @param[in]  address QString [optional]
    * @param[in]  city QString [optional]
    * @param[in]  state QString [optional]
    * @param[in]  country QString [optional]
    * @param[in]  zip QString [optional]
    * @param[in]  cc QString [optional]
    * @param[in]  cc_exp QString [optional]
    * @param[in]  cc_ccv2 QString [optional]
    */
    virtual void addAccountCreditCard(const ::OpenAPI::OptionalParam<QString> &name = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<QString> &address = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<QString> &city = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<QString> &state = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<QString> &country = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<QString> &zip = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<QString> &cc = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<QString> &cc_exp = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<QString> &cc_ccv2 = ::OpenAPI::OptionalParam<QString>());

    /**
    * @param[in]  oai_billing_add_cc_request OAIBillingAddCcRequest [required]
    */
    virtual void addBillingCreditCard(const OAIBillingAddCcRequest &oai_billing_add_cc_request);

    /**
    * @param[in]  oai_billing_prepay_request OAIBillingPrepayRequest [required]
    */
    virtual void addBillingPrepay(const OAIBillingPrepayRequest &oai_billing_prepay_request);

    /**
    * @param[in]  id QString [required]
    */
    virtual void deleteAccountCreditCard(const QString &id);

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void deleteBillingCreditCard(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void deleteBillingInvoice(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void deleteBillingPrepay(const qint32 &id);


    virtual void getAffiliateBanners();


    virtual void getAffiliateRichReport();

    /**
    * @param[in]  days qint32 [optional]
    */
    virtual void getAffiliateSalesGraph(const ::OpenAPI::OptionalParam<qint32> &days = ::OpenAPI::OptionalParam<qint32>());


    virtual void getAffiliateSalesReport();

    /**
    * @param[in]  days qint32 [optional]
    */
    virtual void getAffiliateTrafficGraph(const ::OpenAPI::OptionalParam<qint32> &days = ::OpenAPI::OptionalParam<qint32>());


    virtual void getAffiliateWebTraffic();


    virtual void getBillingCart();

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void getBillingCreditCardVerify(const qint32 &id);

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void getBillingInvoice(const qint32 &id);


    virtual void getBillingInvoices();


    virtual void getBillingPrePays();

    /**
    * @param[in]  search_string QString [optional]
    * @param[in]  skip qint32 [optional]
    * @param[in]  limit qint32 [optional]
    */
    virtual void getInvoices(const ::OpenAPI::OptionalParam<QString> &search_string = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<qint32> &skip = ::OpenAPI::OptionalParam<qint32>(), const ::OpenAPI::OptionalParam<qint32> &limit = ::OpenAPI::OptionalParam<qint32>());

    /**
    * @param[in]  method QString [required]
    * @param[in]  invoices QString [required]
    */
    virtual void initiatePayment(const QString &method, const QString &invoices);

    /**
    * @param[in]  id qint32 [required]
    * @param[in]  oai_billing_verify_cc_request OAIBillingVerifyCcRequest [required]
    */
    virtual void postBillingCreditCardVerify(const qint32 &id, const OAIBillingVerifyCcRequest &oai_billing_verify_cc_request);

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void updateAccountCreditCard(const qint32 &id);

    /**
    * @param[in]  affiliate_dock_title QString [optional]
    * @param[in]  affiliate_dock_description QString [optional]
    * @param[in]  referrer_coupon QString [optional]
    */
    virtual void updateAffiliateDockSetup(const ::OpenAPI::OptionalParam<QString> &affiliate_dock_title = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<QString> &affiliate_dock_description = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<QString> &referrer_coupon = ::OpenAPI::OptionalParam<QString>());

    /**
    * @param[in]  affiliate_dock_title QString [optional]
    * @param[in]  affiliate_dock_description QString [optional]
    * @param[in]  referrer_coupon QString [optional]
    */
    virtual void updateAffiliateLandingPage(const ::OpenAPI::OptionalParam<QString> &affiliate_dock_title = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<QString> &affiliate_dock_description = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<QString> &referrer_coupon = ::OpenAPI::OptionalParam<QString>());

    /**
    * @param[in]  affiliate_paypal QString [optional]
    * @param[in]  affiliate_payment_method QString [optional]
    */
    virtual void updateAffiliatePaymentSetup(const ::OpenAPI::OptionalParam<QString> &affiliate_paypal = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<QString> &affiliate_payment_method = ::OpenAPI::OptionalParam<QString>());

    /**
    * @param[in]  id qint32 [required]
    */
    virtual void updateBillingCreditCard(const qint32 &id);

    /**
    * @param[in]  oai_billing_payment_method_request OAIBillingPaymentMethodRequest [required]
    */
    virtual void updateBillingPaymentMethod(const OAIBillingPaymentMethodRequest &oai_billing_payment_method_request);


private:
    enum class OauthMethod : int {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        ImplicitFlow = 1,
        AuthorizationFlow = 2,
        ClientCredentialsFlow = 3,
        ResourceOwnerPasswordFlow = 4
    };
    QMap<QString,int> _serverIndices;
    QMap<QString,QList<OAIServerConfiguration>> _serverConfigs;
    QMap<QString, QString> _apiKeys;
    QString _bearerToken;
    QString _username;
    QString _password;
    int _timeOut;
    QString _workingDirectory;
    QNetworkAccessManager* _manager;
    QMap<QString, QString> _defaultHeaders;
    bool _isResponseCompressionEnabled;
    bool _isRequestCompressionEnabled;
    OAIHttpRequestInput _latestInput;
    OAIHttpRequestWorker *_latestWorker;
    QStringList _latestScope;
    OauthCode _authFlow;
    OauthImplicit _implicitFlow;
    OauthCredentials _credentialFlow;
    OauthPassword _passwordFlow;
    OauthMethod _OauthMethod = OauthMethod::INVALID_VALUE_OPENAPI_GENERATED;

    void addAccountCreditCardCallback(OAIHttpRequestWorker *worker);
    void addBillingCreditCardCallback(OAIHttpRequestWorker *worker);
    void addBillingPrepayCallback(OAIHttpRequestWorker *worker);
    void deleteAccountCreditCardCallback(OAIHttpRequestWorker *worker);
    void deleteBillingCreditCardCallback(OAIHttpRequestWorker *worker);
    void deleteBillingInvoiceCallback(OAIHttpRequestWorker *worker);
    void deleteBillingPrepayCallback(OAIHttpRequestWorker *worker);
    void getAffiliateBannersCallback(OAIHttpRequestWorker *worker);
    void getAffiliateRichReportCallback(OAIHttpRequestWorker *worker);
    void getAffiliateSalesGraphCallback(OAIHttpRequestWorker *worker);
    void getAffiliateSalesReportCallback(OAIHttpRequestWorker *worker);
    void getAffiliateTrafficGraphCallback(OAIHttpRequestWorker *worker);
    void getAffiliateWebTrafficCallback(OAIHttpRequestWorker *worker);
    void getBillingCartCallback(OAIHttpRequestWorker *worker);
    void getBillingCreditCardVerifyCallback(OAIHttpRequestWorker *worker);
    void getBillingInvoiceCallback(OAIHttpRequestWorker *worker);
    void getBillingInvoicesCallback(OAIHttpRequestWorker *worker);
    void getBillingPrePaysCallback(OAIHttpRequestWorker *worker);
    void getInvoicesCallback(OAIHttpRequestWorker *worker);
    void initiatePaymentCallback(OAIHttpRequestWorker *worker);
    void postBillingCreditCardVerifyCallback(OAIHttpRequestWorker *worker);
    void updateAccountCreditCardCallback(OAIHttpRequestWorker *worker);
    void updateAffiliateDockSetupCallback(OAIHttpRequestWorker *worker);
    void updateAffiliateLandingPageCallback(OAIHttpRequestWorker *worker);
    void updateAffiliatePaymentSetupCallback(OAIHttpRequestWorker *worker);
    void updateBillingCreditCardCallback(OAIHttpRequestWorker *worker);
    void updateBillingPaymentMethodCallback(OAIHttpRequestWorker *worker);

Q_SIGNALS:

    void addAccountCreditCardSignal(OAISuccessTextResponse summary);
    void addBillingCreditCardSignal(OAISuccessTextResponse summary);
    void addBillingPrepaySignal(OAISuccessTextResponse summary);
    void deleteAccountCreditCardSignal(QString summary);
    void deleteBillingCreditCardSignal(OAISuccessTextResponse summary);
    void deleteBillingInvoiceSignal(OAISuccessTextResponse summary);
    void deleteBillingPrepaySignal(OAISuccessTextResponse summary);
    void getAffiliateBannersSignal(QList<OAIAffiliateBannerRow> summary);
    void getAffiliateRichReportSignal(OAITextResponse summary);
    void getAffiliateSalesGraphSignal(OAIStatusMonthlyBreakdown summary);
    void getAffiliateSalesReportSignal(OAITextResponse summary);
    void getAffiliateTrafficGraphSignal(OAIMonthlyCounts<QString, qint32> summary);
    void getAffiliateWebTrafficSignal(QList<OAIAffiliateTrafficRow> summary);
    void getBillingCartSignal(OAIObject summary);
    void getBillingCreditCardVerifySignal(OAISuccessTextResponse summary);
    void getBillingInvoiceSignal(OAIBillingInvoiceDetail<QString, QString> summary);
    void getBillingInvoicesSignal(OAIBillingInvoiceList summary);
    void getBillingPrePaysSignal(OAIObject summary);
    void getInvoicesSignal(QList<OAIInvoice> summary);
    void initiatePaymentSignal(OAIInitiatePayment_200_response summary);
    void postBillingCreditCardVerifySignal(OAISuccessTextResponse summary);
    void updateAccountCreditCardSignal(QString summary);
    void updateAffiliateDockSetupSignal(OAITextResponse summary);
    void updateAffiliateLandingPageSignal(OAITextResponse summary);
    void updateAffiliatePaymentSetupSignal(OAITextResponse summary);
    void updateBillingCreditCardSignal(OAISuccessTextResponse summary);
    void updateBillingPaymentMethodSignal(OAISuccessTextResponse summary);


    void addAccountCreditCardSignalFull(OAIHttpRequestWorker *worker, OAISuccessTextResponse summary);
    void addBillingCreditCardSignalFull(OAIHttpRequestWorker *worker, OAISuccessTextResponse summary);
    void addBillingPrepaySignalFull(OAIHttpRequestWorker *worker, OAISuccessTextResponse summary);
    void deleteAccountCreditCardSignalFull(OAIHttpRequestWorker *worker, QString summary);
    void deleteBillingCreditCardSignalFull(OAIHttpRequestWorker *worker, OAISuccessTextResponse summary);
    void deleteBillingInvoiceSignalFull(OAIHttpRequestWorker *worker, OAISuccessTextResponse summary);
    void deleteBillingPrepaySignalFull(OAIHttpRequestWorker *worker, OAISuccessTextResponse summary);
    void getAffiliateBannersSignalFull(OAIHttpRequestWorker *worker, QList<OAIAffiliateBannerRow> summary);
    void getAffiliateRichReportSignalFull(OAIHttpRequestWorker *worker, OAITextResponse summary);
    void getAffiliateSalesGraphSignalFull(OAIHttpRequestWorker *worker, OAIStatusMonthlyBreakdown summary);
    void getAffiliateSalesReportSignalFull(OAIHttpRequestWorker *worker, OAITextResponse summary);
    void getAffiliateTrafficGraphSignalFull(OAIHttpRequestWorker *worker, OAIMonthlyCounts<QString, qint32> summary);
    void getAffiliateWebTrafficSignalFull(OAIHttpRequestWorker *worker, QList<OAIAffiliateTrafficRow> summary);
    void getBillingCartSignalFull(OAIHttpRequestWorker *worker, OAIObject summary);
    void getBillingCreditCardVerifySignalFull(OAIHttpRequestWorker *worker, OAISuccessTextResponse summary);
    void getBillingInvoiceSignalFull(OAIHttpRequestWorker *worker, OAIBillingInvoiceDetail<QString, QString> summary);
    void getBillingInvoicesSignalFull(OAIHttpRequestWorker *worker, OAIBillingInvoiceList summary);
    void getBillingPrePaysSignalFull(OAIHttpRequestWorker *worker, OAIObject summary);
    void getInvoicesSignalFull(OAIHttpRequestWorker *worker, QList<OAIInvoice> summary);
    void initiatePaymentSignalFull(OAIHttpRequestWorker *worker, OAIInitiatePayment_200_response summary);
    void postBillingCreditCardVerifySignalFull(OAIHttpRequestWorker *worker, OAISuccessTextResponse summary);
    void updateAccountCreditCardSignalFull(OAIHttpRequestWorker *worker, QString summary);
    void updateAffiliateDockSetupSignalFull(OAIHttpRequestWorker *worker, OAITextResponse summary);
    void updateAffiliateLandingPageSignalFull(OAIHttpRequestWorker *worker, OAITextResponse summary);
    void updateAffiliatePaymentSetupSignalFull(OAIHttpRequestWorker *worker, OAITextResponse summary);
    void updateBillingCreditCardSignalFull(OAIHttpRequestWorker *worker, OAISuccessTextResponse summary);
    void updateBillingPaymentMethodSignalFull(OAIHttpRequestWorker *worker, OAISuccessTextResponse summary);

    void addAccountCreditCardSignalError(OAISuccessTextResponse summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void addBillingCreditCardSignalError(OAISuccessTextResponse summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void addBillingPrepaySignalError(OAISuccessTextResponse summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void deleteAccountCreditCardSignalError(QString summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void deleteBillingCreditCardSignalError(OAISuccessTextResponse summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void deleteBillingInvoiceSignalError(OAISuccessTextResponse summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void deleteBillingPrepaySignalError(OAISuccessTextResponse summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getAffiliateBannersSignalError(QList<OAIAffiliateBannerRow> summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getAffiliateRichReportSignalError(OAITextResponse summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getAffiliateSalesGraphSignalError(OAIStatusMonthlyBreakdown summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getAffiliateSalesReportSignalError(OAITextResponse summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getAffiliateTrafficGraphSignalError(OAIMonthlyCounts<QString, qint32> summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getAffiliateWebTrafficSignalError(QList<OAIAffiliateTrafficRow> summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getBillingCartSignalError(OAIObject summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getBillingCreditCardVerifySignalError(OAISuccessTextResponse summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getBillingInvoiceSignalError(OAIBillingInvoiceDetail<QString, QString> summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getBillingInvoicesSignalError(OAIBillingInvoiceList summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getBillingPrePaysSignalError(OAIObject summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getInvoicesSignalError(QList<OAIInvoice> summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void initiatePaymentSignalError(OAIInitiatePayment_200_response summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void postBillingCreditCardVerifySignalError(OAISuccessTextResponse summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void updateAccountCreditCardSignalError(QString summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void updateAffiliateDockSetupSignalError(OAITextResponse summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void updateAffiliateLandingPageSignalError(OAITextResponse summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void updateAffiliatePaymentSetupSignalError(OAITextResponse summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void updateBillingCreditCardSignalError(OAISuccessTextResponse summary, QNetworkReply::NetworkError error_type, const QString &error_str);
    void updateBillingPaymentMethodSignalError(OAISuccessTextResponse summary, QNetworkReply::NetworkError error_type, const QString &error_str);

    void addAccountCreditCardSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void addBillingCreditCardSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void addBillingPrepaySignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void deleteAccountCreditCardSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void deleteBillingCreditCardSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void deleteBillingInvoiceSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void deleteBillingPrepaySignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getAffiliateBannersSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getAffiliateRichReportSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getAffiliateSalesGraphSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getAffiliateSalesReportSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getAffiliateTrafficGraphSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getAffiliateWebTrafficSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getBillingCartSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getBillingCreditCardVerifySignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getBillingInvoiceSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getBillingInvoicesSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getBillingPrePaysSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void getInvoicesSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void initiatePaymentSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void postBillingCreditCardVerifySignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void updateAccountCreditCardSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void updateAffiliateDockSetupSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void updateAffiliateLandingPageSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void updateAffiliatePaymentSetupSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void updateBillingCreditCardSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);
    void updateBillingPaymentMethodSignalErrorFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, const QString &error_str);

    void abortRequestsSignal();
    void allPendingRequestsCompleted();

public Q_SLOTS:
    void tokenAvailable();
};

} // namespace OpenAPI
#endif
