/**
 * InterServer Management API
 * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIVps.h
 *
 * 
 */

#ifndef OAIVps_H
#define OAIVps_H

#include <QJsonObject>

#include "OAIVpsBillingDetails.h"
#include "OAIVpsCPData.h"
#include "OAIVpsClientLink.h"
#include "OAIVpsDAData.h"
#include "OAIVpsExtraInfoTables.h"
#include "OAIVpsPlesk12Data.h"
#include "OAIVpsServiceAddons.h"
#include "OAIVpsServiceExtra.h"
#include "OAIVpsServiceInfo.h"
#include "OAIVpsServiceMaster.h"
#include <QJsonValue>
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIVpsServiceInfo;
class OAIVpsClientLink;
class OAIVpsBillingDetails;
class OAIVpsServiceMaster;
class OAIVpsServiceExtra;
class OAIVpsExtraInfoTables;
class OAIVpsCPData;
class OAIVpsDAData;
class OAIVpsPlesk12Data;
class OAIVpsServiceAddons;

class OAIVps : public OAIObject {
public:
    OAIVps();
    OAIVps(const QString &json);
    ~OAIVps() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(const QString &jsonString) override;

    OAIVpsServiceInfo getServiceInfo() const;
    void setServiceInfo(const OAIVpsServiceInfo &service_info);
    bool is_service_info_Set() const;
    bool is_service_info_Valid() const;

    QList<OAIVpsClientLink> getClientLinks() const;
    void setClientLinks(const QList<OAIVpsClientLink> &client_links);
    bool is_client_links_Set() const;
    bool is_client_links_Valid() const;

    OAIVpsBillingDetails getBillingDetails() const;
    void setBillingDetails(const OAIVpsBillingDetails &billing_details);
    bool is_billing_details_Set() const;
    bool is_billing_details_Valid() const;

    QString getCustCurrency() const;
    void setCustCurrency(const QString &cust_currency);
    bool is_cust_currency_Set() const;
    bool is_cust_currency_Valid() const;

    QString getCustCurrencySymbol() const;
    void setCustCurrencySymbol(const QString &cust_currency_symbol);
    bool is_cust_currency_symbol_Set() const;
    bool is_cust_currency_symbol_Valid() const;

    OAIVpsServiceMaster getServiceMaster() const;
    void setServiceMaster(const OAIVpsServiceMaster &service_master);
    bool is_service_master_Set() const;
    bool is_service_master_Valid() const;

    QString getPackage() const;
    void setPackage(const QString &package);
    bool is_package_Set() const;
    bool is_package_Valid() const;

    OAIVpsServiceExtra getServiceExtra() const;
    void setServiceExtra(const OAIVpsServiceExtra &service_extra);
    bool is_service_extra_Set() const;
    bool is_service_extra_Valid() const;

    OAIVpsExtraInfoTables getExtraInfoTables() const;
    void setExtraInfoTables(const OAIVpsExtraInfoTables &extra_info_tables);
    bool is_extra_info_tables_Set() const;
    bool is_extra_info_tables_Valid() const;

    QString getModule() const;
    void setModule(const QString &module);
    bool is_module_Set() const;
    bool is_module_Valid() const;

    QString getToken() const;
    void setToken(const QString &token);
    bool is_token_Set() const;
    bool is_token_Valid() const;

    qint32 getDaLink() const;
    void setDaLink(const qint32 &da_link);
    bool is_da_link_Set() const;
    bool is_da_link_Valid() const;

    qint32 getSrLink() const;
    void setSrLink(const qint32 &sr_link);
    bool is_sr_link_Set() const;
    bool is_sr_link_Valid() const;

    OAIVpsCPData getCpData() const;
    void setCpData(const OAIVpsCPData &cp_data);
    bool is_cp_data_Set() const;
    bool is_cp_data_Valid() const;

    OAIVpsDAData getDaData() const;
    void setDaData(const OAIVpsDAData &da_data);
    bool is_da_data_Set() const;
    bool is_da_data_Valid() const;

    OAIVpsPlesk12Data getPlesk12Data() const;
    void setPlesk12Data(const OAIVpsPlesk12Data &plesk12_data);
    bool is_plesk12_data_Set() const;
    bool is_plesk12_data_Valid() const;

    OAIVpsServiceAddons getServiceAddons() const;
    void setServiceAddons(const OAIVpsServiceAddons &service_addons);
    bool is_service_addons_Set() const;
    bool is_service_addons_Valid() const;

    QString getOsTemplate() const;
    void setOsTemplate(const QString &os_template);
    bool is_os_template_Set() const;
    bool is_os_template_Valid() const;

    QJsonValue getCpuGraphData() const;
    void setCpuGraphData(const QJsonValue &cpu_graph_data);
    bool is_cpu_graph_data_Set() const;
    bool is_cpu_graph_data_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIVpsServiceInfo m_service_info;
    bool m_service_info_isSet;
    bool m_service_info_isValid;

    QList<OAIVpsClientLink> m_client_links;
    bool m_client_links_isSet;
    bool m_client_links_isValid;

    OAIVpsBillingDetails m_billing_details;
    bool m_billing_details_isSet;
    bool m_billing_details_isValid;

    QString m_cust_currency;
    bool m_cust_currency_isSet;
    bool m_cust_currency_isValid;

    QString m_cust_currency_symbol;
    bool m_cust_currency_symbol_isSet;
    bool m_cust_currency_symbol_isValid;

    OAIVpsServiceMaster m_service_master;
    bool m_service_master_isSet;
    bool m_service_master_isValid;

    QString m_package;
    bool m_package_isSet;
    bool m_package_isValid;

    OAIVpsServiceExtra m_service_extra;
    bool m_service_extra_isSet;
    bool m_service_extra_isValid;

    OAIVpsExtraInfoTables m_extra_info_tables;
    bool m_extra_info_tables_isSet;
    bool m_extra_info_tables_isValid;

    QString m_module;
    bool m_module_isSet;
    bool m_module_isValid;

    QString m_token;
    bool m_token_isSet;
    bool m_token_isValid;

    qint32 m_da_link;
    bool m_da_link_isSet;
    bool m_da_link_isValid;

    qint32 m_sr_link;
    bool m_sr_link_isSet;
    bool m_sr_link_isValid;

    OAIVpsCPData m_cp_data;
    bool m_cp_data_isSet;
    bool m_cp_data_isValid;

    OAIVpsDAData m_da_data;
    bool m_da_data_isSet;
    bool m_da_data_isValid;

    OAIVpsPlesk12Data m_plesk12_data;
    bool m_plesk12_data_isSet;
    bool m_plesk12_data_isValid;

    OAIVpsServiceAddons m_service_addons;
    bool m_service_addons_isSet;
    bool m_service_addons_isValid;

    QString m_os_template;
    bool m_os_template_isSet;
    bool m_os_template_isValid;

    QJsonValue m_cpu_graph_data;
    bool m_cpu_graph_data_isSet;
    bool m_cpu_graph_data_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIVps)

#endif // OAIVps_H
