#
# InterServer Management API
# # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
# Version: 0.9.0
# Contact: support@interserver.net
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

VPS Traffic Information

.PARAMETER Name
No description available.
.PARAMETER Target
No description available.
.PARAMETER Interval
No description available.
.PARAMETER History
No description available.
.PARAMETER Last
No description available.
.PARAMETER Times
No description available.
.PARAMETER Totals
No description available.
.PARAMETER Usage
No description available.
.PARAMETER VarData
No description available.
.OUTPUTS

VpsTrafficResponse<PSCustomObject>
#>

function Initialize-VpsTrafficResponse {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Target},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${Interval},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${History},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.DateTime]
        ${Last},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.DateTime[]]
        ${Times},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Totals},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Usage},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${VarData}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => VpsTrafficResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Name) {
            throw "invalid value for 'Name', 'Name' cannot be null."
        }

        if ($null -eq $Target) {
            throw "invalid value for 'Target', 'Target' cannot be null."
        }

        if ($null -eq $Interval) {
            throw "invalid value for 'Interval', 'Interval' cannot be null."
        }

        if ($null -eq $History) {
            throw "invalid value for 'History', 'History' cannot be null."
        }

        if ($null -eq $Last) {
            throw "invalid value for 'Last', 'Last' cannot be null."
        }

        if ($null -eq $Times) {
            throw "invalid value for 'Times', 'Times' cannot be null."
        }

        if ($null -eq $Totals) {
            throw "invalid value for 'Totals', 'Totals' cannot be null."
        }

        if ($null -eq $Usage) {
            throw "invalid value for 'Usage', 'Usage' cannot be null."
        }

        if ($null -eq $VarData) {
            throw "invalid value for 'VarData', 'VarData' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "name" = ${Name}
            "target" = ${Target}
            "interval" = ${Interval}
            "history" = ${History}
            "last" = ${Last}
            "times" = ${Times}
            "totals" = ${Totals}
            "usage" = ${Usage}
            "data" = ${VarData}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VpsTrafficResponse<PSCustomObject>

.DESCRIPTION

Convert from JSON to VpsTrafficResponse<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VpsTrafficResponse<PSCustomObject>
#>
function ConvertFrom-JsonToVpsTrafficResponse {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => VpsTrafficResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in VpsTrafficResponse
        $AllProperties = ("name", "target", "interval", "history", "last", "times", "totals", "usage", "data")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'name' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) {
            throw "Error! JSON cannot be serialized due to the required property 'name' missing."
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "target"))) {
            throw "Error! JSON cannot be serialized due to the required property 'target' missing."
        } else {
            $Target = $JsonParameters.PSobject.Properties["target"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "interval"))) {
            throw "Error! JSON cannot be serialized due to the required property 'interval' missing."
        } else {
            $Interval = $JsonParameters.PSobject.Properties["interval"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "history"))) {
            throw "Error! JSON cannot be serialized due to the required property 'history' missing."
        } else {
            $History = $JsonParameters.PSobject.Properties["history"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "last"))) {
            throw "Error! JSON cannot be serialized due to the required property 'last' missing."
        } else {
            $Last = $JsonParameters.PSobject.Properties["last"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "times"))) {
            throw "Error! JSON cannot be serialized due to the required property 'times' missing."
        } else {
            $Times = $JsonParameters.PSobject.Properties["times"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "totals"))) {
            throw "Error! JSON cannot be serialized due to the required property 'totals' missing."
        } else {
            $Totals = $JsonParameters.PSobject.Properties["totals"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "usage"))) {
            throw "Error! JSON cannot be serialized due to the required property 'usage' missing."
        } else {
            $Usage = $JsonParameters.PSobject.Properties["usage"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "data"))) {
            throw "Error! JSON cannot be serialized due to the required property 'data' missing."
        } else {
            $VarData = $JsonParameters.PSobject.Properties["data"].value
        }

        $PSO = [PSCustomObject]@{
            "name" = ${Name}
            "target" = ${Target}
            "interval" = ${Interval}
            "history" = ${History}
            "last" = ${Last}
            "times" = ${Times}
            "totals" = ${Totals}
            "usage" = ${Usage}
            "data" = ${VarData}
        }

        return $PSO
    }

}

