/* 
 * InterServer Management API
 *
 * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
 *
 * OpenAPI spec version: 0.9.0
 * Contact: support@interserver.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Interserver.MyAdmin.Client.Client.SwaggerDateConverter;
namespace Interserver.MyAdmin.Client.Model
{
    /// <summary>
    /// Currently selected configuration option IDs for a server order form.
    /// </summary>
    [DataContract]
        public partial class FormValues :  IEquatable<FormValues>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FormValues" /> class.
        /// </summary>
        /// <param name="memory">Selected memory option ID..</param>
        /// <param name="bandwidth">Selected bandwidth option ID..</param>
        /// <param name="ips">Selected IP block option ID..</param>
        /// <param name="os">Selected operating system option ID..</param>
        /// <param name="cp">Selected control panel option ID..</param>
        /// <param name="raid">Selected RAID option ID..</param>
        /// <param name="hd">Selected hard drive option ID..</param>
        /// <param name="region">Selected datacenter region ID..</param>
        public FormValues(int? memory = default(int?), int? bandwidth = default(int?), int? ips = default(int?), int? os = default(int?), int? cp = default(int?), int? raid = default(int?), int? hd = default(int?), int? region = default(int?))
        {
            this.memory = memory;
            this.bandwidth = bandwidth;
            this.ips = ips;
            this.os = os;
            this.cp = cp;
            this.raid = raid;
            this.hd = hd;
            this.region = region;
        }
        
        /// <summary>
        /// Selected memory option ID.
        /// </summary>
        /// <value>Selected memory option ID.</value>
        [DataMember(Name="memory", EmitDefaultValue=false)]
        public int? memory { get; set; }

        /// <summary>
        /// Selected bandwidth option ID.
        /// </summary>
        /// <value>Selected bandwidth option ID.</value>
        [DataMember(Name="bandwidth", EmitDefaultValue=false)]
        public int? bandwidth { get; set; }

        /// <summary>
        /// Selected IP block option ID.
        /// </summary>
        /// <value>Selected IP block option ID.</value>
        [DataMember(Name="ips", EmitDefaultValue=false)]
        public int? ips { get; set; }

        /// <summary>
        /// Selected operating system option ID.
        /// </summary>
        /// <value>Selected operating system option ID.</value>
        [DataMember(Name="os", EmitDefaultValue=false)]
        public int? os { get; set; }

        /// <summary>
        /// Selected control panel option ID.
        /// </summary>
        /// <value>Selected control panel option ID.</value>
        [DataMember(Name="cp", EmitDefaultValue=false)]
        public int? cp { get; set; }

        /// <summary>
        /// Selected RAID option ID.
        /// </summary>
        /// <value>Selected RAID option ID.</value>
        [DataMember(Name="raid", EmitDefaultValue=false)]
        public int? raid { get; set; }

        /// <summary>
        /// Selected hard drive option ID.
        /// </summary>
        /// <value>Selected hard drive option ID.</value>
        [DataMember(Name="hd", EmitDefaultValue=false)]
        public int? hd { get; set; }

        /// <summary>
        /// Selected datacenter region ID.
        /// </summary>
        /// <value>Selected datacenter region ID.</value>
        [DataMember(Name="region", EmitDefaultValue=false)]
        public int? region { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FormValues {\n");
            sb.Append("  memory: ").Append(memory).Append("\n");
            sb.Append("  bandwidth: ").Append(bandwidth).Append("\n");
            sb.Append("  ips: ").Append(ips).Append("\n");
            sb.Append("  os: ").Append(os).Append("\n");
            sb.Append("  cp: ").Append(cp).Append("\n");
            sb.Append("  raid: ").Append(raid).Append("\n");
            sb.Append("  hd: ").Append(hd).Append("\n");
            sb.Append("  region: ").Append(region).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FormValues);
        }

        /// <summary>
        /// Returns true if FormValues instances are equal
        /// </summary>
        /// <param name="input">Instance of FormValues to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FormValues input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.memory == input.memory ||
                    (this.memory != null &&
                    this.memory.Equals(input.memory))
                ) && 
                (
                    this.bandwidth == input.bandwidth ||
                    (this.bandwidth != null &&
                    this.bandwidth.Equals(input.bandwidth))
                ) && 
                (
                    this.ips == input.ips ||
                    (this.ips != null &&
                    this.ips.Equals(input.ips))
                ) && 
                (
                    this.os == input.os ||
                    (this.os != null &&
                    this.os.Equals(input.os))
                ) && 
                (
                    this.cp == input.cp ||
                    (this.cp != null &&
                    this.cp.Equals(input.cp))
                ) && 
                (
                    this.raid == input.raid ||
                    (this.raid != null &&
                    this.raid.Equals(input.raid))
                ) && 
                (
                    this.hd == input.hd ||
                    (this.hd != null &&
                    this.hd.Equals(input.hd))
                ) && 
                (
                    this.region == input.region ||
                    (this.region != null &&
                    this.region.Equals(input.region))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.memory != null)
                    hashCode = hashCode * 59 + this.memory.GetHashCode();
                if (this.bandwidth != null)
                    hashCode = hashCode * 59 + this.bandwidth.GetHashCode();
                if (this.ips != null)
                    hashCode = hashCode * 59 + this.ips.GetHashCode();
                if (this.os != null)
                    hashCode = hashCode * 59 + this.os.GetHashCode();
                if (this.cp != null)
                    hashCode = hashCode * 59 + this.cp.GetHashCode();
                if (this.raid != null)
                    hashCode = hashCode * 59 + this.raid.GetHashCode();
                if (this.hd != null)
                    hashCode = hashCode * 59 + this.hd.GetHashCode();
                if (this.region != null)
                    hashCode = hashCode * 59 + this.region.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
