/* 
 * InterServer Management API
 *
 * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
 *
 * OpenAPI spec version: 0.9.0
 * Contact: support@interserver.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Interserver.MyAdmin.Client.Client.SwaggerDateConverter;
namespace Interserver.MyAdmin.Client.Model
{
    /// <summary>
    /// Information about the host node (hypervisor) running this VPS, including hardware specs and resource utilization.
    /// </summary>
    [DataContract]
        public partial class VpsServiceMaster :  IEquatable<VpsServiceMaster>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VpsServiceMaster" /> class.
        /// </summary>
        /// <param name="vpsId">VPS ID.</param>
        /// <param name="vpsName">VPS name.</param>
        /// <param name="vpsIp">IP address of the VPS.</param>
        /// <param name="vpsType">VPS type.</param>
        /// <param name="vpsHdsize">Hard drive size.</param>
        /// <param name="vpsHdfree">Free hard drive space.</param>
        /// <param name="vpsBits">Bits.</param>
        /// <param name="vpsLoad">CPU load.</param>
        /// <param name="vpsRam">RAM.</param>
        /// <param name="vpsCpuModel">CPU model.</param>
        /// <param name="vpsCpuMhz">CPU frequency in MHz.</param>
        /// <param name="vpsLocation">Location of the VPS.</param>
        /// <param name="vpsLastUpdate">Last update date.</param>
        /// <param name="vpsRaidBuilding">RAID building status.</param>
        /// <param name="vpsKernel">Kernel version.</param>
        /// <param name="vpsAvailable">Available.</param>
        /// <param name="vpsCores">Number of CPU cores.</param>
        /// <param name="vpsIowait">I/O wait.</param>
        /// <param name="vpsRaidStatus">RAID status.</param>
        /// <param name="vpsMounts">Mounts.</param>
        /// <param name="vpsServerMax">Maximum number of servers.</param>
        /// <param name="vpsServerMaxSlices">Maximum number of server slices.</param>
        /// <param name="vpsDriveType">Drive type.</param>
        /// <param name="vpsOrder">Order number.</param>
        public VpsServiceMaster(string vpsId = default(string), string vpsName = default(string), string vpsIp = default(string), string vpsType = default(string), string vpsHdsize = default(string), string vpsHdfree = default(string), string vpsBits = default(string), string vpsLoad = default(string), string vpsRam = default(string), string vpsCpuModel = default(string), string vpsCpuMhz = default(string), string vpsLocation = default(string), string vpsLastUpdate = default(string), string vpsRaidBuilding = default(string), string vpsKernel = default(string), string vpsAvailable = default(string), string vpsCores = default(string), string vpsIowait = default(string), string vpsRaidStatus = default(string), string vpsMounts = default(string), string vpsServerMax = default(string), string vpsServerMaxSlices = default(string), string vpsDriveType = default(string), string vpsOrder = default(string))
        {
            this.vps_id = vpsId;
            this.vps_name = vpsName;
            this.vps_ip = vpsIp;
            this.vps_type = vpsType;
            this.vps_hdsize = vpsHdsize;
            this.vps_hdfree = vpsHdfree;
            this.vps_bits = vpsBits;
            this.vps_load = vpsLoad;
            this.vps_ram = vpsRam;
            this.vps_cpu_model = vpsCpuModel;
            this.vps_cpu_mhz = vpsCpuMhz;
            this.vps_location = vpsLocation;
            this.vps_last_update = vpsLastUpdate;
            this.vps_raid_building = vpsRaidBuilding;
            this.vps_kernel = vpsKernel;
            this.vps_available = vpsAvailable;
            this.vps_cores = vpsCores;
            this.vps_iowait = vpsIowait;
            this.vps_raid_status = vpsRaidStatus;
            this.vps_mounts = vpsMounts;
            this.vps_server_max = vpsServerMax;
            this.vps_server_max_slices = vpsServerMaxSlices;
            this.vps_drive_type = vpsDriveType;
            this.vps_order = vpsOrder;
        }
        
        /// <summary>
        /// VPS ID
        /// </summary>
        /// <value>VPS ID</value>
        [DataMember(Name="vps_id", EmitDefaultValue=false)]
        public string vps_id { get; set; }

        /// <summary>
        /// VPS name
        /// </summary>
        /// <value>VPS name</value>
        [DataMember(Name="vps_name", EmitDefaultValue=false)]
        public string vps_name { get; set; }

        /// <summary>
        /// IP address of the VPS
        /// </summary>
        /// <value>IP address of the VPS</value>
        [DataMember(Name="vps_ip", EmitDefaultValue=false)]
        public string vps_ip { get; set; }

        /// <summary>
        /// VPS type
        /// </summary>
        /// <value>VPS type</value>
        [DataMember(Name="vps_type", EmitDefaultValue=false)]
        public string vps_type { get; set; }

        /// <summary>
        /// Hard drive size
        /// </summary>
        /// <value>Hard drive size</value>
        [DataMember(Name="vps_hdsize", EmitDefaultValue=false)]
        public string vps_hdsize { get; set; }

        /// <summary>
        /// Free hard drive space
        /// </summary>
        /// <value>Free hard drive space</value>
        [DataMember(Name="vps_hdfree", EmitDefaultValue=false)]
        public string vps_hdfree { get; set; }

        /// <summary>
        /// Bits
        /// </summary>
        /// <value>Bits</value>
        [DataMember(Name="vps_bits", EmitDefaultValue=false)]
        public string vps_bits { get; set; }

        /// <summary>
        /// CPU load
        /// </summary>
        /// <value>CPU load</value>
        [DataMember(Name="vps_load", EmitDefaultValue=false)]
        public string vps_load { get; set; }

        /// <summary>
        /// RAM
        /// </summary>
        /// <value>RAM</value>
        [DataMember(Name="vps_ram", EmitDefaultValue=false)]
        public string vps_ram { get; set; }

        /// <summary>
        /// CPU model
        /// </summary>
        /// <value>CPU model</value>
        [DataMember(Name="vps_cpu_model", EmitDefaultValue=false)]
        public string vps_cpu_model { get; set; }

        /// <summary>
        /// CPU frequency in MHz
        /// </summary>
        /// <value>CPU frequency in MHz</value>
        [DataMember(Name="vps_cpu_mhz", EmitDefaultValue=false)]
        public string vps_cpu_mhz { get; set; }

        /// <summary>
        /// Location of the VPS
        /// </summary>
        /// <value>Location of the VPS</value>
        [DataMember(Name="vps_location", EmitDefaultValue=false)]
        public string vps_location { get; set; }

        /// <summary>
        /// Last update date
        /// </summary>
        /// <value>Last update date</value>
        [DataMember(Name="vps_last_update", EmitDefaultValue=false)]
        public string vps_last_update { get; set; }

        /// <summary>
        /// RAID building status
        /// </summary>
        /// <value>RAID building status</value>
        [DataMember(Name="vps_raid_building", EmitDefaultValue=false)]
        public string vps_raid_building { get; set; }

        /// <summary>
        /// Kernel version
        /// </summary>
        /// <value>Kernel version</value>
        [DataMember(Name="vps_kernel", EmitDefaultValue=false)]
        public string vps_kernel { get; set; }

        /// <summary>
        /// Available
        /// </summary>
        /// <value>Available</value>
        [DataMember(Name="vps_available", EmitDefaultValue=false)]
        public string vps_available { get; set; }

        /// <summary>
        /// Number of CPU cores
        /// </summary>
        /// <value>Number of CPU cores</value>
        [DataMember(Name="vps_cores", EmitDefaultValue=false)]
        public string vps_cores { get; set; }

        /// <summary>
        /// I/O wait
        /// </summary>
        /// <value>I/O wait</value>
        [DataMember(Name="vps_iowait", EmitDefaultValue=false)]
        public string vps_iowait { get; set; }

        /// <summary>
        /// RAID status
        /// </summary>
        /// <value>RAID status</value>
        [DataMember(Name="vps_raid_status", EmitDefaultValue=false)]
        public string vps_raid_status { get; set; }

        /// <summary>
        /// Mounts
        /// </summary>
        /// <value>Mounts</value>
        [DataMember(Name="vps_mounts", EmitDefaultValue=false)]
        public string vps_mounts { get; set; }

        /// <summary>
        /// Maximum number of servers
        /// </summary>
        /// <value>Maximum number of servers</value>
        [DataMember(Name="vps_server_max", EmitDefaultValue=false)]
        public string vps_server_max { get; set; }

        /// <summary>
        /// Maximum number of server slices
        /// </summary>
        /// <value>Maximum number of server slices</value>
        [DataMember(Name="vps_server_max_slices", EmitDefaultValue=false)]
        public string vps_server_max_slices { get; set; }

        /// <summary>
        /// Drive type
        /// </summary>
        /// <value>Drive type</value>
        [DataMember(Name="vps_drive_type", EmitDefaultValue=false)]
        public string vps_drive_type { get; set; }

        /// <summary>
        /// Order number
        /// </summary>
        /// <value>Order number</value>
        [DataMember(Name="vps_order", EmitDefaultValue=false)]
        public string vps_order { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VpsServiceMaster {\n");
            sb.Append("  vps_id: ").Append(vps_id).Append("\n");
            sb.Append("  vps_name: ").Append(vps_name).Append("\n");
            sb.Append("  vps_ip: ").Append(vps_ip).Append("\n");
            sb.Append("  vps_type: ").Append(vps_type).Append("\n");
            sb.Append("  vps_hdsize: ").Append(vps_hdsize).Append("\n");
            sb.Append("  vps_hdfree: ").Append(vps_hdfree).Append("\n");
            sb.Append("  vps_bits: ").Append(vps_bits).Append("\n");
            sb.Append("  vps_load: ").Append(vps_load).Append("\n");
            sb.Append("  vps_ram: ").Append(vps_ram).Append("\n");
            sb.Append("  vps_cpu_model: ").Append(vps_cpu_model).Append("\n");
            sb.Append("  vps_cpu_mhz: ").Append(vps_cpu_mhz).Append("\n");
            sb.Append("  vps_location: ").Append(vps_location).Append("\n");
            sb.Append("  vps_last_update: ").Append(vps_last_update).Append("\n");
            sb.Append("  vps_raid_building: ").Append(vps_raid_building).Append("\n");
            sb.Append("  vps_kernel: ").Append(vps_kernel).Append("\n");
            sb.Append("  vps_available: ").Append(vps_available).Append("\n");
            sb.Append("  vps_cores: ").Append(vps_cores).Append("\n");
            sb.Append("  vps_iowait: ").Append(vps_iowait).Append("\n");
            sb.Append("  vps_raid_status: ").Append(vps_raid_status).Append("\n");
            sb.Append("  vps_mounts: ").Append(vps_mounts).Append("\n");
            sb.Append("  vps_server_max: ").Append(vps_server_max).Append("\n");
            sb.Append("  vps_server_max_slices: ").Append(vps_server_max_slices).Append("\n");
            sb.Append("  vps_drive_type: ").Append(vps_drive_type).Append("\n");
            sb.Append("  vps_order: ").Append(vps_order).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VpsServiceMaster);
        }

        /// <summary>
        /// Returns true if VpsServiceMaster instances are equal
        /// </summary>
        /// <param name="input">Instance of VpsServiceMaster to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VpsServiceMaster input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.vps_id == input.vps_id ||
                    (this.vps_id != null &&
                    this.vps_id.Equals(input.vps_id))
                ) && 
                (
                    this.vps_name == input.vps_name ||
                    (this.vps_name != null &&
                    this.vps_name.Equals(input.vps_name))
                ) && 
                (
                    this.vps_ip == input.vps_ip ||
                    (this.vps_ip != null &&
                    this.vps_ip.Equals(input.vps_ip))
                ) && 
                (
                    this.vps_type == input.vps_type ||
                    (this.vps_type != null &&
                    this.vps_type.Equals(input.vps_type))
                ) && 
                (
                    this.vps_hdsize == input.vps_hdsize ||
                    (this.vps_hdsize != null &&
                    this.vps_hdsize.Equals(input.vps_hdsize))
                ) && 
                (
                    this.vps_hdfree == input.vps_hdfree ||
                    (this.vps_hdfree != null &&
                    this.vps_hdfree.Equals(input.vps_hdfree))
                ) && 
                (
                    this.vps_bits == input.vps_bits ||
                    (this.vps_bits != null &&
                    this.vps_bits.Equals(input.vps_bits))
                ) && 
                (
                    this.vps_load == input.vps_load ||
                    (this.vps_load != null &&
                    this.vps_load.Equals(input.vps_load))
                ) && 
                (
                    this.vps_ram == input.vps_ram ||
                    (this.vps_ram != null &&
                    this.vps_ram.Equals(input.vps_ram))
                ) && 
                (
                    this.vps_cpu_model == input.vps_cpu_model ||
                    (this.vps_cpu_model != null &&
                    this.vps_cpu_model.Equals(input.vps_cpu_model))
                ) && 
                (
                    this.vps_cpu_mhz == input.vps_cpu_mhz ||
                    (this.vps_cpu_mhz != null &&
                    this.vps_cpu_mhz.Equals(input.vps_cpu_mhz))
                ) && 
                (
                    this.vps_location == input.vps_location ||
                    (this.vps_location != null &&
                    this.vps_location.Equals(input.vps_location))
                ) && 
                (
                    this.vps_last_update == input.vps_last_update ||
                    (this.vps_last_update != null &&
                    this.vps_last_update.Equals(input.vps_last_update))
                ) && 
                (
                    this.vps_raid_building == input.vps_raid_building ||
                    (this.vps_raid_building != null &&
                    this.vps_raid_building.Equals(input.vps_raid_building))
                ) && 
                (
                    this.vps_kernel == input.vps_kernel ||
                    (this.vps_kernel != null &&
                    this.vps_kernel.Equals(input.vps_kernel))
                ) && 
                (
                    this.vps_available == input.vps_available ||
                    (this.vps_available != null &&
                    this.vps_available.Equals(input.vps_available))
                ) && 
                (
                    this.vps_cores == input.vps_cores ||
                    (this.vps_cores != null &&
                    this.vps_cores.Equals(input.vps_cores))
                ) && 
                (
                    this.vps_iowait == input.vps_iowait ||
                    (this.vps_iowait != null &&
                    this.vps_iowait.Equals(input.vps_iowait))
                ) && 
                (
                    this.vps_raid_status == input.vps_raid_status ||
                    (this.vps_raid_status != null &&
                    this.vps_raid_status.Equals(input.vps_raid_status))
                ) && 
                (
                    this.vps_mounts == input.vps_mounts ||
                    (this.vps_mounts != null &&
                    this.vps_mounts.Equals(input.vps_mounts))
                ) && 
                (
                    this.vps_server_max == input.vps_server_max ||
                    (this.vps_server_max != null &&
                    this.vps_server_max.Equals(input.vps_server_max))
                ) && 
                (
                    this.vps_server_max_slices == input.vps_server_max_slices ||
                    (this.vps_server_max_slices != null &&
                    this.vps_server_max_slices.Equals(input.vps_server_max_slices))
                ) && 
                (
                    this.vps_drive_type == input.vps_drive_type ||
                    (this.vps_drive_type != null &&
                    this.vps_drive_type.Equals(input.vps_drive_type))
                ) && 
                (
                    this.vps_order == input.vps_order ||
                    (this.vps_order != null &&
                    this.vps_order.Equals(input.vps_order))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.vps_id != null)
                    hashCode = hashCode * 59 + this.vps_id.GetHashCode();
                if (this.vps_name != null)
                    hashCode = hashCode * 59 + this.vps_name.GetHashCode();
                if (this.vps_ip != null)
                    hashCode = hashCode * 59 + this.vps_ip.GetHashCode();
                if (this.vps_type != null)
                    hashCode = hashCode * 59 + this.vps_type.GetHashCode();
                if (this.vps_hdsize != null)
                    hashCode = hashCode * 59 + this.vps_hdsize.GetHashCode();
                if (this.vps_hdfree != null)
                    hashCode = hashCode * 59 + this.vps_hdfree.GetHashCode();
                if (this.vps_bits != null)
                    hashCode = hashCode * 59 + this.vps_bits.GetHashCode();
                if (this.vps_load != null)
                    hashCode = hashCode * 59 + this.vps_load.GetHashCode();
                if (this.vps_ram != null)
                    hashCode = hashCode * 59 + this.vps_ram.GetHashCode();
                if (this.vps_cpu_model != null)
                    hashCode = hashCode * 59 + this.vps_cpu_model.GetHashCode();
                if (this.vps_cpu_mhz != null)
                    hashCode = hashCode * 59 + this.vps_cpu_mhz.GetHashCode();
                if (this.vps_location != null)
                    hashCode = hashCode * 59 + this.vps_location.GetHashCode();
                if (this.vps_last_update != null)
                    hashCode = hashCode * 59 + this.vps_last_update.GetHashCode();
                if (this.vps_raid_building != null)
                    hashCode = hashCode * 59 + this.vps_raid_building.GetHashCode();
                if (this.vps_kernel != null)
                    hashCode = hashCode * 59 + this.vps_kernel.GetHashCode();
                if (this.vps_available != null)
                    hashCode = hashCode * 59 + this.vps_available.GetHashCode();
                if (this.vps_cores != null)
                    hashCode = hashCode * 59 + this.vps_cores.GetHashCode();
                if (this.vps_iowait != null)
                    hashCode = hashCode * 59 + this.vps_iowait.GetHashCode();
                if (this.vps_raid_status != null)
                    hashCode = hashCode * 59 + this.vps_raid_status.GetHashCode();
                if (this.vps_mounts != null)
                    hashCode = hashCode * 59 + this.vps_mounts.GetHashCode();
                if (this.vps_server_max != null)
                    hashCode = hashCode * 59 + this.vps_server_max.GetHashCode();
                if (this.vps_server_max_slices != null)
                    hashCode = hashCode * 59 + this.vps_server_max_slices.GetHashCode();
                if (this.vps_drive_type != null)
                    hashCode = hashCode * 59 + this.vps_drive_type.GetHashCode();
                if (this.vps_order != null)
                    hashCode = hashCode * 59 + this.vps_order.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
