# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from myadmin-client-python-flask.models.base_model_ import Model
from myadmin-client-python-flask import util


class IdMigrationBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, cust_portal: str=None, reg_email: str=None, password: str=None, ctrl_panel: str=None, ftp_username: str=None, ftp_password: str=None, site_busy_mig: str=None, spl_req_mig: str=None, domain_reg: str=None, data_mig: str=None, domain_reg_portal: str=None, domain_reg_email: str=None, domain_reg_password: str=None):  # noqa: E501
        """IdMigrationBody - a model defined in Swagger

        :param cust_portal: The cust_portal of this IdMigrationBody.  # noqa: E501
        :type cust_portal: str
        :param reg_email: The reg_email of this IdMigrationBody.  # noqa: E501
        :type reg_email: str
        :param password: The password of this IdMigrationBody.  # noqa: E501
        :type password: str
        :param ctrl_panel: The ctrl_panel of this IdMigrationBody.  # noqa: E501
        :type ctrl_panel: str
        :param ftp_username: The ftp_username of this IdMigrationBody.  # noqa: E501
        :type ftp_username: str
        :param ftp_password: The ftp_password of this IdMigrationBody.  # noqa: E501
        :type ftp_password: str
        :param site_busy_mig: The site_busy_mig of this IdMigrationBody.  # noqa: E501
        :type site_busy_mig: str
        :param spl_req_mig: The spl_req_mig of this IdMigrationBody.  # noqa: E501
        :type spl_req_mig: str
        :param domain_reg: The domain_reg of this IdMigrationBody.  # noqa: E501
        :type domain_reg: str
        :param data_mig: The data_mig of this IdMigrationBody.  # noqa: E501
        :type data_mig: str
        :param domain_reg_portal: The domain_reg_portal of this IdMigrationBody.  # noqa: E501
        :type domain_reg_portal: str
        :param domain_reg_email: The domain_reg_email of this IdMigrationBody.  # noqa: E501
        :type domain_reg_email: str
        :param domain_reg_password: The domain_reg_password of this IdMigrationBody.  # noqa: E501
        :type domain_reg_password: str
        """
        self.swagger_types = {
            'cust_portal': str,
            'reg_email': str,
            'password': str,
            'ctrl_panel': str,
            'ftp_username': str,
            'ftp_password': str,
            'site_busy_mig': str,
            'spl_req_mig': str,
            'domain_reg': str,
            'data_mig': str,
            'domain_reg_portal': str,
            'domain_reg_email': str,
            'domain_reg_password': str
        }

        self.attribute_map = {
            'cust_portal': 'custPortal',
            'reg_email': 'regEmail',
            'password': 'password',
            'ctrl_panel': 'ctrlPanel',
            'ftp_username': 'ftpUsername',
            'ftp_password': 'ftpPassword',
            'site_busy_mig': 'siteBusyMig',
            'spl_req_mig': 'splReqMig',
            'domain_reg': 'domainReg',
            'data_mig': 'dataMig',
            'domain_reg_portal': 'domainRegPortal',
            'domain_reg_email': 'domainRegEmail',
            'domain_reg_password': 'domainRegPassword'
        }
        self._cust_portal = cust_portal
        self._reg_email = reg_email
        self._password = password
        self._ctrl_panel = ctrl_panel
        self._ftp_username = ftp_username
        self._ftp_password = ftp_password
        self._site_busy_mig = site_busy_mig
        self._spl_req_mig = spl_req_mig
        self._domain_reg = domain_reg
        self._data_mig = data_mig
        self._domain_reg_portal = domain_reg_portal
        self._domain_reg_email = domain_reg_email
        self._domain_reg_password = domain_reg_password

    @classmethod
    def from_dict(cls, dikt) -> 'IdMigrationBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The id_migration_body of this IdMigrationBody.  # noqa: E501
        :rtype: IdMigrationBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cust_portal(self) -> str:
        """Gets the cust_portal of this IdMigrationBody.

        URL of the customer's current hosting portal.  # noqa: E501

        :return: The cust_portal of this IdMigrationBody.
        :rtype: str
        """
        return self._cust_portal

    @cust_portal.setter
    def cust_portal(self, cust_portal: str):
        """Sets the cust_portal of this IdMigrationBody.

        URL of the customer's current hosting portal.  # noqa: E501

        :param cust_portal: The cust_portal of this IdMigrationBody.
        :type cust_portal: str
        """

        self._cust_portal = cust_portal

    @property
    def reg_email(self) -> str:
        """Gets the reg_email of this IdMigrationBody.

        Registered email address at the current host.  # noqa: E501

        :return: The reg_email of this IdMigrationBody.
        :rtype: str
        """
        return self._reg_email

    @reg_email.setter
    def reg_email(self, reg_email: str):
        """Sets the reg_email of this IdMigrationBody.

        Registered email address at the current host.  # noqa: E501

        :param reg_email: The reg_email of this IdMigrationBody.
        :type reg_email: str
        """

        self._reg_email = reg_email

    @property
    def password(self) -> str:
        """Gets the password of this IdMigrationBody.

        Password for the current hosting account.  # noqa: E501

        :return: The password of this IdMigrationBody.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this IdMigrationBody.

        Password for the current hosting account.  # noqa: E501

        :param password: The password of this IdMigrationBody.
        :type password: str
        """

        self._password = password

    @property
    def ctrl_panel(self) -> str:
        """Gets the ctrl_panel of this IdMigrationBody.

        URL of the current control panel.  # noqa: E501

        :return: The ctrl_panel of this IdMigrationBody.
        :rtype: str
        """
        return self._ctrl_panel

    @ctrl_panel.setter
    def ctrl_panel(self, ctrl_panel: str):
        """Sets the ctrl_panel of this IdMigrationBody.

        URL of the current control panel.  # noqa: E501

        :param ctrl_panel: The ctrl_panel of this IdMigrationBody.
        :type ctrl_panel: str
        """

        self._ctrl_panel = ctrl_panel

    @property
    def ftp_username(self) -> str:
        """Gets the ftp_username of this IdMigrationBody.

        FTP username at the current host.  # noqa: E501

        :return: The ftp_username of this IdMigrationBody.
        :rtype: str
        """
        return self._ftp_username

    @ftp_username.setter
    def ftp_username(self, ftp_username: str):
        """Sets the ftp_username of this IdMigrationBody.

        FTP username at the current host.  # noqa: E501

        :param ftp_username: The ftp_username of this IdMigrationBody.
        :type ftp_username: str
        """

        self._ftp_username = ftp_username

    @property
    def ftp_password(self) -> str:
        """Gets the ftp_password of this IdMigrationBody.

        FTP password at the current host.  # noqa: E501

        :return: The ftp_password of this IdMigrationBody.
        :rtype: str
        """
        return self._ftp_password

    @ftp_password.setter
    def ftp_password(self, ftp_password: str):
        """Sets the ftp_password of this IdMigrationBody.

        FTP password at the current host.  # noqa: E501

        :param ftp_password: The ftp_password of this IdMigrationBody.
        :type ftp_password: str
        """

        self._ftp_password = ftp_password

    @property
    def site_busy_mig(self) -> str:
        """Gets the site_busy_mig of this IdMigrationBody.

        Information about site traffic during migration.  # noqa: E501

        :return: The site_busy_mig of this IdMigrationBody.
        :rtype: str
        """
        return self._site_busy_mig

    @site_busy_mig.setter
    def site_busy_mig(self, site_busy_mig: str):
        """Sets the site_busy_mig of this IdMigrationBody.

        Information about site traffic during migration.  # noqa: E501

        :param site_busy_mig: The site_busy_mig of this IdMigrationBody.
        :type site_busy_mig: str
        """

        self._site_busy_mig = site_busy_mig

    @property
    def spl_req_mig(self) -> str:
        """Gets the spl_req_mig of this IdMigrationBody.

        Special requirements for the migration.  # noqa: E501

        :return: The spl_req_mig of this IdMigrationBody.
        :rtype: str
        """
        return self._spl_req_mig

    @spl_req_mig.setter
    def spl_req_mig(self, spl_req_mig: str):
        """Sets the spl_req_mig of this IdMigrationBody.

        Special requirements for the migration.  # noqa: E501

        :param spl_req_mig: The spl_req_mig of this IdMigrationBody.
        :type spl_req_mig: str
        """

        self._spl_req_mig = spl_req_mig

    @property
    def domain_reg(self) -> str:
        """Gets the domain_reg of this IdMigrationBody.

        Whether domain registration assistance is needed.  # noqa: E501

        :return: The domain_reg of this IdMigrationBody.
        :rtype: str
        """
        return self._domain_reg

    @domain_reg.setter
    def domain_reg(self, domain_reg: str):
        """Sets the domain_reg of this IdMigrationBody.

        Whether domain registration assistance is needed.  # noqa: E501

        :param domain_reg: The domain_reg of this IdMigrationBody.
        :type domain_reg: str
        """

        self._domain_reg = domain_reg

    @property
    def data_mig(self) -> str:
        """Gets the data_mig of this IdMigrationBody.

        Data migration timing preference.  # noqa: E501

        :return: The data_mig of this IdMigrationBody.
        :rtype: str
        """
        return self._data_mig

    @data_mig.setter
    def data_mig(self, data_mig: str):
        """Sets the data_mig of this IdMigrationBody.

        Data migration timing preference.  # noqa: E501

        :param data_mig: The data_mig of this IdMigrationBody.
        :type data_mig: str
        """

        self._data_mig = data_mig

    @property
    def domain_reg_portal(self) -> str:
        """Gets the domain_reg_portal of this IdMigrationBody.

        Domain registrar portal URL.  # noqa: E501

        :return: The domain_reg_portal of this IdMigrationBody.
        :rtype: str
        """
        return self._domain_reg_portal

    @domain_reg_portal.setter
    def domain_reg_portal(self, domain_reg_portal: str):
        """Sets the domain_reg_portal of this IdMigrationBody.

        Domain registrar portal URL.  # noqa: E501

        :param domain_reg_portal: The domain_reg_portal of this IdMigrationBody.
        :type domain_reg_portal: str
        """

        self._domain_reg_portal = domain_reg_portal

    @property
    def domain_reg_email(self) -> str:
        """Gets the domain_reg_email of this IdMigrationBody.

        Email for the domain registrar account.  # noqa: E501

        :return: The domain_reg_email of this IdMigrationBody.
        :rtype: str
        """
        return self._domain_reg_email

    @domain_reg_email.setter
    def domain_reg_email(self, domain_reg_email: str):
        """Sets the domain_reg_email of this IdMigrationBody.

        Email for the domain registrar account.  # noqa: E501

        :param domain_reg_email: The domain_reg_email of this IdMigrationBody.
        :type domain_reg_email: str
        """

        self._domain_reg_email = domain_reg_email

    @property
    def domain_reg_password(self) -> str:
        """Gets the domain_reg_password of this IdMigrationBody.

        Password for the domain registrar account.  # noqa: E501

        :return: The domain_reg_password of this IdMigrationBody.
        :rtype: str
        """
        return self._domain_reg_password

    @domain_reg_password.setter
    def domain_reg_password(self, domain_reg_password: str):
        """Sets the domain_reg_password of this IdMigrationBody.

        Password for the domain registrar account.  # noqa: E501

        :param domain_reg_password: The domain_reg_password of this IdMigrationBody.
        :type domain_reg_password: str
        """

        self._domain_reg_password = domain_reg_password
