# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from myadmin-client-python-flask.models.base_model_ import Model
from myadmin-client-python-flask.models.server_billing_details import ServerBillingDetails  # noqa: F401,E501
from myadmin-client-python-flask.models.server_client_link import ServerClientLink  # noqa: F401,E501
from myadmin-client-python-flask.models.server_extra_info_tables import ServerExtraInfoTables  # noqa: F401,E501
from myadmin-client-python-flask.models.server_locations import ServerLocations  # noqa: F401,E501
from myadmin-client-python-flask.models.server_network_info import ServerNetworkInfo  # noqa: F401,E501
from myadmin-client-python-flask.models.server_service_info import ServerServiceInfo  # noqa: F401,E501
from myadmin-client-python-flask import util


class Server(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ipmi_auth: bool=None, client_links: List[ServerClientLink]=None, billing_details: ServerBillingDetails=None, cust_currency: str=None, cust_currency_symbol: str=None, package: str=None, service_extra: List[str]=None, locations: ServerLocations=None, network_info: ServerNetworkInfo=None, extra_info_tables: ServerExtraInfoTables=None, service_info: ServerServiceInfo=None):  # noqa: E501
        """Server - a model defined in Swagger

        :param ipmi_auth: The ipmi_auth of this Server.  # noqa: E501
        :type ipmi_auth: bool
        :param client_links: The client_links of this Server.  # noqa: E501
        :type client_links: List[ServerClientLink]
        :param billing_details: The billing_details of this Server.  # noqa: E501
        :type billing_details: ServerBillingDetails
        :param cust_currency: The cust_currency of this Server.  # noqa: E501
        :type cust_currency: str
        :param cust_currency_symbol: The cust_currency_symbol of this Server.  # noqa: E501
        :type cust_currency_symbol: str
        :param package: The package of this Server.  # noqa: E501
        :type package: str
        :param service_extra: The service_extra of this Server.  # noqa: E501
        :type service_extra: List[str]
        :param locations: The locations of this Server.  # noqa: E501
        :type locations: ServerLocations
        :param network_info: The network_info of this Server.  # noqa: E501
        :type network_info: ServerNetworkInfo
        :param extra_info_tables: The extra_info_tables of this Server.  # noqa: E501
        :type extra_info_tables: ServerExtraInfoTables
        :param service_info: The service_info of this Server.  # noqa: E501
        :type service_info: ServerServiceInfo
        """
        self.swagger_types = {
            'ipmi_auth': bool,
            'client_links': List[ServerClientLink],
            'billing_details': ServerBillingDetails,
            'cust_currency': str,
            'cust_currency_symbol': str,
            'package': str,
            'service_extra': List[str],
            'locations': ServerLocations,
            'network_info': ServerNetworkInfo,
            'extra_info_tables': ServerExtraInfoTables,
            'service_info': ServerServiceInfo
        }

        self.attribute_map = {
            'ipmi_auth': 'ipmiAuth',
            'client_links': 'client_links',
            'billing_details': 'billingDetails',
            'cust_currency': 'custCurrency',
            'cust_currency_symbol': 'custCurrencySymbol',
            'package': 'package',
            'service_extra': 'serviceExtra',
            'locations': 'locations',
            'network_info': 'networkInfo',
            'extra_info_tables': 'extraInfoTables',
            'service_info': 'serviceInfo'
        }
        self._ipmi_auth = ipmi_auth
        self._client_links = client_links
        self._billing_details = billing_details
        self._cust_currency = cust_currency
        self._cust_currency_symbol = cust_currency_symbol
        self._package = package
        self._service_extra = service_extra
        self._locations = locations
        self._network_info = network_info
        self._extra_info_tables = extra_info_tables
        self._service_info = service_info

    @classmethod
    def from_dict(cls, dikt) -> 'Server':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Server of this Server.  # noqa: E501
        :rtype: Server
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ipmi_auth(self) -> bool:
        """Gets the ipmi_auth of this Server.


        :return: The ipmi_auth of this Server.
        :rtype: bool
        """
        return self._ipmi_auth

    @ipmi_auth.setter
    def ipmi_auth(self, ipmi_auth: bool):
        """Sets the ipmi_auth of this Server.


        :param ipmi_auth: The ipmi_auth of this Server.
        :type ipmi_auth: bool
        """
        if ipmi_auth is None:
            raise ValueError("Invalid value for `ipmi_auth`, must not be `None`")  # noqa: E501

        self._ipmi_auth = ipmi_auth

    @property
    def client_links(self) -> List[ServerClientLink]:
        """Gets the client_links of this Server.


        :return: The client_links of this Server.
        :rtype: List[ServerClientLink]
        """
        return self._client_links

    @client_links.setter
    def client_links(self, client_links: List[ServerClientLink]):
        """Sets the client_links of this Server.


        :param client_links: The client_links of this Server.
        :type client_links: List[ServerClientLink]
        """
        if client_links is None:
            raise ValueError("Invalid value for `client_links`, must not be `None`")  # noqa: E501

        self._client_links = client_links

    @property
    def billing_details(self) -> ServerBillingDetails:
        """Gets the billing_details of this Server.


        :return: The billing_details of this Server.
        :rtype: ServerBillingDetails
        """
        return self._billing_details

    @billing_details.setter
    def billing_details(self, billing_details: ServerBillingDetails):
        """Sets the billing_details of this Server.


        :param billing_details: The billing_details of this Server.
        :type billing_details: ServerBillingDetails
        """
        if billing_details is None:
            raise ValueError("Invalid value for `billing_details`, must not be `None`")  # noqa: E501

        self._billing_details = billing_details

    @property
    def cust_currency(self) -> str:
        """Gets the cust_currency of this Server.


        :return: The cust_currency of this Server.
        :rtype: str
        """
        return self._cust_currency

    @cust_currency.setter
    def cust_currency(self, cust_currency: str):
        """Sets the cust_currency of this Server.


        :param cust_currency: The cust_currency of this Server.
        :type cust_currency: str
        """
        if cust_currency is None:
            raise ValueError("Invalid value for `cust_currency`, must not be `None`")  # noqa: E501

        self._cust_currency = cust_currency

    @property
    def cust_currency_symbol(self) -> str:
        """Gets the cust_currency_symbol of this Server.


        :return: The cust_currency_symbol of this Server.
        :rtype: str
        """
        return self._cust_currency_symbol

    @cust_currency_symbol.setter
    def cust_currency_symbol(self, cust_currency_symbol: str):
        """Sets the cust_currency_symbol of this Server.


        :param cust_currency_symbol: The cust_currency_symbol of this Server.
        :type cust_currency_symbol: str
        """
        if cust_currency_symbol is None:
            raise ValueError("Invalid value for `cust_currency_symbol`, must not be `None`")  # noqa: E501

        self._cust_currency_symbol = cust_currency_symbol

    @property
    def package(self) -> str:
        """Gets the package of this Server.


        :return: The package of this Server.
        :rtype: str
        """
        return self._package

    @package.setter
    def package(self, package: str):
        """Sets the package of this Server.


        :param package: The package of this Server.
        :type package: str
        """
        if package is None:
            raise ValueError("Invalid value for `package`, must not be `None`")  # noqa: E501

        self._package = package

    @property
    def service_extra(self) -> List[str]:
        """Gets the service_extra of this Server.


        :return: The service_extra of this Server.
        :rtype: List[str]
        """
        return self._service_extra

    @service_extra.setter
    def service_extra(self, service_extra: List[str]):
        """Sets the service_extra of this Server.


        :param service_extra: The service_extra of this Server.
        :type service_extra: List[str]
        """
        if service_extra is None:
            raise ValueError("Invalid value for `service_extra`, must not be `None`")  # noqa: E501

        self._service_extra = service_extra

    @property
    def locations(self) -> ServerLocations:
        """Gets the locations of this Server.


        :return: The locations of this Server.
        :rtype: ServerLocations
        """
        return self._locations

    @locations.setter
    def locations(self, locations: ServerLocations):
        """Sets the locations of this Server.


        :param locations: The locations of this Server.
        :type locations: ServerLocations
        """
        if locations is None:
            raise ValueError("Invalid value for `locations`, must not be `None`")  # noqa: E501

        self._locations = locations

    @property
    def network_info(self) -> ServerNetworkInfo:
        """Gets the network_info of this Server.


        :return: The network_info of this Server.
        :rtype: ServerNetworkInfo
        """
        return self._network_info

    @network_info.setter
    def network_info(self, network_info: ServerNetworkInfo):
        """Sets the network_info of this Server.


        :param network_info: The network_info of this Server.
        :type network_info: ServerNetworkInfo
        """
        if network_info is None:
            raise ValueError("Invalid value for `network_info`, must not be `None`")  # noqa: E501

        self._network_info = network_info

    @property
    def extra_info_tables(self) -> ServerExtraInfoTables:
        """Gets the extra_info_tables of this Server.


        :return: The extra_info_tables of this Server.
        :rtype: ServerExtraInfoTables
        """
        return self._extra_info_tables

    @extra_info_tables.setter
    def extra_info_tables(self, extra_info_tables: ServerExtraInfoTables):
        """Sets the extra_info_tables of this Server.


        :param extra_info_tables: The extra_info_tables of this Server.
        :type extra_info_tables: ServerExtraInfoTables
        """
        if extra_info_tables is None:
            raise ValueError("Invalid value for `extra_info_tables`, must not be `None`")  # noqa: E501

        self._extra_info_tables = extra_info_tables

    @property
    def service_info(self) -> ServerServiceInfo:
        """Gets the service_info of this Server.


        :return: The service_info of this Server.
        :rtype: ServerServiceInfo
        """
        return self._service_info

    @service_info.setter
    def service_info(self, service_info: ServerServiceInfo):
        """Sets the service_info of this Server.


        :param service_info: The service_info of this Server.
        :type service_info: ServerServiceInfo
        """
        if service_info is None:
            raise ValueError("Invalid value for `service_info`, must not be `None`")  # noqa: E501

        self._service_info = service_info
