extends Resource
class_name LicensesOrderPackageCosts

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# LicensesOrderPackageCosts Model
# Costs of license packages


# Cost of package with ID 11468
# Required: False
# Example: 3.75
# isArray: false
@export var LicensesOrderPackageCosts11468: float:
	set(value):
		__LicensesOrderPackageCosts11468__was__set = true
		LicensesOrderPackageCosts11468 = value
var __LicensesOrderPackageCosts11468__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__LicensesOrderPackageCosts11468__was__set:
		bzz_dictionary["LicensesOrderPackageCosts11468"] = self.LicensesOrderPackageCosts11468
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("LicensesOrderPackageCosts11468"):
		me.LicensesOrderPackageCosts11468 = from_dict["LicensesOrderPackageCosts11468"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

