extends Resource
class_name VpsServiceInfo

# THIS FILE WAS AUTOMATICALLY GENERATED by the OpenAPI Generator project.
# For more information on how to customize templates, see:
# https://openapi-generator.tech
# https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/gdscript
# The OpenAPI Generator Community, © Public Domain, 2022

# VpsServiceInfo Model


# VPS ID
# Required: False
# Example: 85872
# isArray: false
@export var vpsUnderscoreid: String = "":
	set(value):
		__vpsUnderscoreid__was__set = true
		vpsUnderscoreid = value
var __vpsUnderscoreid__was__set := false

# Customer ID
# Required: False
# Example: 223513
# isArray: false
@export var vpsUnderscorecustid: String = "":
	set(value):
		__vpsUnderscorecustid__was__set = true
		vpsUnderscorecustid = value
var __vpsUnderscorecustid__was__set := false

# Server ID
# Required: False
# Example: 2439
# isArray: false
@export var vpsUnderscoreserver: String = "":
	set(value):
		__vpsUnderscoreserver__was__set = true
		vpsUnderscoreserver = value
var __vpsUnderscoreserver__was__set := false

# IP address of the VPS
# Required: False
# Example: 1.2.3.4
# isArray: false
@export var vpsUnderscoreip: String = "":
	set(value):
		__vpsUnderscoreip__was__set = true
		vpsUnderscoreip = value
var __vpsUnderscoreip__was__set := false

# IPv6 address of the VPS
# Required: False
# isArray: false
@export var vpsUnderscoreipv6: AnyType:
	set(value):
		__vpsUnderscoreipv6__was__set = true
		vpsUnderscoreipv6 = value
var __vpsUnderscoreipv6__was__set := false

# VPS Virtuozzo ID
# Required: False
# Example: vps85872
# isArray: false
@export var vpsUnderscorevzid: String = "":
	set(value):
		__vpsUnderscorevzid__was__set = true
		vpsUnderscorevzid = value
var __vpsUnderscorevzid__was__set := false

# Currency used for billing
# Required: False
# Example: USD
# isArray: false
@export var vpsUnderscorecurrency: String = "":
	set(value):
		__vpsUnderscorecurrency__was__set = true
		vpsUnderscorecurrency = value
var __vpsUnderscorecurrency__was__set := false

# VPS type
# Required: False
# Example: 33
# isArray: false
@export var vpsUnderscoretype: String = "":
	set(value):
		__vpsUnderscoretype__was__set = true
		vpsUnderscoretype = value
var __vpsUnderscoretype__was__set := false

# Date of VPS order
# Required: False
# Example: 2022-12-26T20:14:59.000Z
# isArray: false
@export var vpsUnderscoreorderUnderscoredate: String = "":
	set(value):
		__vpsUnderscoreorderUnderscoredate__was__set = true
		vpsUnderscoreorderUnderscoredate = value
var __vpsUnderscoreorderUnderscoredate__was__set := false

# VPS status
# Required: False
# Example: active
# isArray: false
@export var vpsUnderscorestatus: String = "":
	set(value):
		__vpsUnderscorestatus__was__set = true
		vpsUnderscorestatus = value
var __vpsUnderscorestatus__was__set := false

# VPS invoice number
# Required: False
# Example: 20130799
# isArray: false
@export var vpsUnderscoreinvoice: String = "":
	set(value):
		__vpsUnderscoreinvoice__was__set = true
		vpsUnderscoreinvoice = value
var __vpsUnderscoreinvoice__was__set := false

# VPS coupon code
# Required: False
# Example: 3646
# isArray: false
@export var vpsUnderscorecoupon: String = "":
	set(value):
		__vpsUnderscorecoupon__was__set = true
		vpsUnderscorecoupon = value
var __vpsUnderscorecoupon__was__set := false

# Additional information about the VPS
# Required: False
# Example: {\"spice\":5903,\"snapshots\":[{\"name\":\"third\",\"used\":36490445,\"date\":1692095220},{\"name\":\"second\",\"used\":40894464,\"date\":1692181620},{\"name\":\"first\",\"used\":54735668,\"date\":1692268020}]}
# isArray: false
@export var vpsUnderscoreextra: String = "":
	set(value):
		__vpsUnderscoreextra__was__set = true
		vpsUnderscoreextra = value
var __vpsUnderscoreextra__was__set := false

# VPS hostname
# Required: False
# Example: vps85872
# isArray: false
@export var vpsUnderscorehostname: String = "":
	set(value):
		__vpsUnderscorehostname__was__set = true
		vpsUnderscorehostname = value
var __vpsUnderscorehostname__was__set := false

# Status of the VPS server
# Required: False
# Example: running
# isArray: false
@export var vpsUnderscoreserverUnderscorestatus: String = "":
	set(value):
		__vpsUnderscoreserverUnderscorestatus__was__set = true
		vpsUnderscoreserverUnderscorestatus = value
var __vpsUnderscoreserverUnderscorestatus__was__set := false

# Comment associated with the VPS
# Required: False
# Example: my-web-2
# isArray: false
@export var vpsUnderscorecomment: String = "":
	set(value):
		__vpsUnderscorecomment__was__set = true
		vpsUnderscorecomment = value
var __vpsUnderscorecomment__was__set := false

# Number of VPS slices
# Required: False
# Example: 16
# isArray: false
@export var vpsUnderscoreslices: String = "":
	set(value):
		__vpsUnderscoreslices__was__set = true
		vpsUnderscoreslices = value
var __vpsUnderscoreslices__was__set := false

# VNC address
# Required: False
# Example: 8.7.6.5
# isArray: false
@export var vpsUnderscorevnc: String = "":
	set(value):
		__vpsUnderscorevnc__was__set = true
		vpsUnderscorevnc = value
var __vpsUnderscorevnc__was__set := false

# VNC port
# Required: False
# Example: 5902
# isArray: false
@export var vpsUnderscorevncUnderscoreport: String = "":
	set(value):
		__vpsUnderscorevncUnderscoreport__was__set = true
		vpsUnderscorevncUnderscoreport = value
var __vpsUnderscorevncUnderscoreport__was__set := false

# Root password of the VPS
# Required: False
# Example: mypassword
# isArray: false
@export var vpsUnderscorerootpass: String = "":
	set(value):
		__vpsUnderscorerootpass__was__set = true
		vpsUnderscorerootpass = value
var __vpsUnderscorerootpass__was__set := false

# MAC address of the VPS
# Required: False
# Example: 00:16:3e:27:59:b2
# isArray: false
@export var vpsUnderscoremac: String = "":
	set(value):
		__vpsUnderscoremac__was__set = true
		vpsUnderscoremac = value
var __vpsUnderscoremac__was__set := false

# Operating system of the VPS
# Required: False
# Example: ubuntu24
# isArray: false
@export var vpsUnderscoreos: String = "":
	set(value):
		__vpsUnderscoreos__was__set = true
		vpsUnderscoreos = value
var __vpsUnderscoreos__was__set := false

# Version of the operating system
# Required: False
# Example: ubuntu
# isArray: false
@export var vpsUnderscoreversion: String = "":
	set(value):
		__vpsUnderscoreversion__was__set = true
		vpsUnderscoreversion = value
var __vpsUnderscoreversion__was__set := false

# Location of the VPS
# Required: False
# Example: 1
# isArray: false
@export var vpsUnderscorelocation: String = "":
	set(value):
		__vpsUnderscorelocation__was__set = true
		vpsUnderscorelocation = value
var __vpsUnderscorelocation__was__set := false

# Virtualization platform
# Required: False
# Example: kvm
# isArray: false
@export var vpsUnderscoreplatform: String = "":
	set(value):
		__vpsUnderscoreplatform__was__set = true
		vpsUnderscoreplatform = value
var __vpsUnderscoreplatform__was__set := false

# Amount of disk space used
# Required: False
# Example: 0
# isArray: false
@export var vpsUnderscorediskused: String = "":
	set(value):
		__vpsUnderscorediskused__was__set = true
		vpsUnderscorediskused = value
var __vpsUnderscorediskused__was__set := false

# Maximum disk space available
# Required: False
# Example: 0
# isArray: false
@export var vpsUnderscorediskmax: String = "":
	set(value):
		__vpsUnderscorediskmax__was__set = true
		vpsUnderscorediskmax = value
var __vpsUnderscorediskmax__was__set := false


func bzz_collect_missing_properties() -> Array:
	var bzz_missing_properties := Array()
	return bzz_missing_properties


func bzz_normalize() -> Dictionary:
	var bzz_dictionary := Dictionary()
	if self.__vpsUnderscoreid__was__set:
		bzz_dictionary["vpsUnderscoreid"] = self.vpsUnderscoreid
	if self.__vpsUnderscorecustid__was__set:
		bzz_dictionary["vpsUnderscorecustid"] = self.vpsUnderscorecustid
	if self.__vpsUnderscoreserver__was__set:
		bzz_dictionary["vpsUnderscoreserver"] = self.vpsUnderscoreserver
	if self.__vpsUnderscoreip__was__set:
		bzz_dictionary["vpsUnderscoreip"] = self.vpsUnderscoreip
	if self.__vpsUnderscoreipv6__was__set:
		bzz_dictionary["vpsUnderscoreipv6"] = self.vpsUnderscoreipv6
	if self.__vpsUnderscorevzid__was__set:
		bzz_dictionary["vpsUnderscorevzid"] = self.vpsUnderscorevzid
	if self.__vpsUnderscorecurrency__was__set:
		bzz_dictionary["vpsUnderscorecurrency"] = self.vpsUnderscorecurrency
	if self.__vpsUnderscoretype__was__set:
		bzz_dictionary["vpsUnderscoretype"] = self.vpsUnderscoretype
	if self.__vpsUnderscoreorderUnderscoredate__was__set:
		bzz_dictionary["vpsUnderscoreorderUnderscoredate"] = self.vpsUnderscoreorderUnderscoredate
	if self.__vpsUnderscorestatus__was__set:
		bzz_dictionary["vpsUnderscorestatus"] = self.vpsUnderscorestatus
	if self.__vpsUnderscoreinvoice__was__set:
		bzz_dictionary["vpsUnderscoreinvoice"] = self.vpsUnderscoreinvoice
	if self.__vpsUnderscorecoupon__was__set:
		bzz_dictionary["vpsUnderscorecoupon"] = self.vpsUnderscorecoupon
	if self.__vpsUnderscoreextra__was__set:
		bzz_dictionary["vpsUnderscoreextra"] = self.vpsUnderscoreextra
	if self.__vpsUnderscorehostname__was__set:
		bzz_dictionary["vpsUnderscorehostname"] = self.vpsUnderscorehostname
	if self.__vpsUnderscoreserverUnderscorestatus__was__set:
		bzz_dictionary["vpsUnderscoreserverUnderscorestatus"] = self.vpsUnderscoreserverUnderscorestatus
	if self.__vpsUnderscorecomment__was__set:
		bzz_dictionary["vpsUnderscorecomment"] = self.vpsUnderscorecomment
	if self.__vpsUnderscoreslices__was__set:
		bzz_dictionary["vpsUnderscoreslices"] = self.vpsUnderscoreslices
	if self.__vpsUnderscorevnc__was__set:
		bzz_dictionary["vpsUnderscorevnc"] = self.vpsUnderscorevnc
	if self.__vpsUnderscorevncUnderscoreport__was__set:
		bzz_dictionary["vpsUnderscorevncUnderscoreport"] = self.vpsUnderscorevncUnderscoreport
	if self.__vpsUnderscorerootpass__was__set:
		bzz_dictionary["vpsUnderscorerootpass"] = self.vpsUnderscorerootpass
	if self.__vpsUnderscoremac__was__set:
		bzz_dictionary["vpsUnderscoremac"] = self.vpsUnderscoremac
	if self.__vpsUnderscoreos__was__set:
		bzz_dictionary["vpsUnderscoreos"] = self.vpsUnderscoreos
	if self.__vpsUnderscoreversion__was__set:
		bzz_dictionary["vpsUnderscoreversion"] = self.vpsUnderscoreversion
	if self.__vpsUnderscorelocation__was__set:
		bzz_dictionary["vpsUnderscorelocation"] = self.vpsUnderscorelocation
	if self.__vpsUnderscoreplatform__was__set:
		bzz_dictionary["vpsUnderscoreplatform"] = self.vpsUnderscoreplatform
	if self.__vpsUnderscorediskused__was__set:
		bzz_dictionary["vpsUnderscorediskused"] = self.vpsUnderscorediskused
	if self.__vpsUnderscorediskmax__was__set:
		bzz_dictionary["vpsUnderscorediskmax"] = self.vpsUnderscorediskmax
	return bzz_dictionary


# Won't work for JSON+LD
static func bzz_denormalize_single(from_dict: Dictionary):
	var me := new()
	if from_dict.has("vpsUnderscoreid"):
		me.vpsUnderscoreid = from_dict["vpsUnderscoreid"]
	if from_dict.has("vpsUnderscorecustid"):
		me.vpsUnderscorecustid = from_dict["vpsUnderscorecustid"]
	if from_dict.has("vpsUnderscoreserver"):
		me.vpsUnderscoreserver = from_dict["vpsUnderscoreserver"]
	if from_dict.has("vpsUnderscoreip"):
		me.vpsUnderscoreip = from_dict["vpsUnderscoreip"]
	if from_dict.has("vpsUnderscoreipv6"):
		me.vpsUnderscoreipv6 = from_dict["vpsUnderscoreipv6"]
	if from_dict.has("vpsUnderscorevzid"):
		me.vpsUnderscorevzid = from_dict["vpsUnderscorevzid"]
	if from_dict.has("vpsUnderscorecurrency"):
		me.vpsUnderscorecurrency = from_dict["vpsUnderscorecurrency"]
	if from_dict.has("vpsUnderscoretype"):
		me.vpsUnderscoretype = from_dict["vpsUnderscoretype"]
	if from_dict.has("vpsUnderscoreorderUnderscoredate"):
		me.vpsUnderscoreorderUnderscoredate = from_dict["vpsUnderscoreorderUnderscoredate"]
	if from_dict.has("vpsUnderscorestatus"):
		me.vpsUnderscorestatus = from_dict["vpsUnderscorestatus"]
	if from_dict.has("vpsUnderscoreinvoice"):
		me.vpsUnderscoreinvoice = from_dict["vpsUnderscoreinvoice"]
	if from_dict.has("vpsUnderscorecoupon"):
		me.vpsUnderscorecoupon = from_dict["vpsUnderscorecoupon"]
	if from_dict.has("vpsUnderscoreextra"):
		me.vpsUnderscoreextra = from_dict["vpsUnderscoreextra"]
	if from_dict.has("vpsUnderscorehostname"):
		me.vpsUnderscorehostname = from_dict["vpsUnderscorehostname"]
	if from_dict.has("vpsUnderscoreserverUnderscorestatus"):
		me.vpsUnderscoreserverUnderscorestatus = from_dict["vpsUnderscoreserverUnderscorestatus"]
	if from_dict.has("vpsUnderscorecomment"):
		me.vpsUnderscorecomment = from_dict["vpsUnderscorecomment"]
	if from_dict.has("vpsUnderscoreslices"):
		me.vpsUnderscoreslices = from_dict["vpsUnderscoreslices"]
	if from_dict.has("vpsUnderscorevnc"):
		me.vpsUnderscorevnc = from_dict["vpsUnderscorevnc"]
	if from_dict.has("vpsUnderscorevncUnderscoreport"):
		me.vpsUnderscorevncUnderscoreport = from_dict["vpsUnderscorevncUnderscoreport"]
	if from_dict.has("vpsUnderscorerootpass"):
		me.vpsUnderscorerootpass = from_dict["vpsUnderscorerootpass"]
	if from_dict.has("vpsUnderscoremac"):
		me.vpsUnderscoremac = from_dict["vpsUnderscoremac"]
	if from_dict.has("vpsUnderscoreos"):
		me.vpsUnderscoreos = from_dict["vpsUnderscoreos"]
	if from_dict.has("vpsUnderscoreversion"):
		me.vpsUnderscoreversion = from_dict["vpsUnderscoreversion"]
	if from_dict.has("vpsUnderscorelocation"):
		me.vpsUnderscorelocation = from_dict["vpsUnderscorelocation"]
	if from_dict.has("vpsUnderscoreplatform"):
		me.vpsUnderscoreplatform = from_dict["vpsUnderscoreplatform"]
	if from_dict.has("vpsUnderscorediskused"):
		me.vpsUnderscorediskused = from_dict["vpsUnderscorediskused"]
	if from_dict.has("vpsUnderscorediskmax"):
		me.vpsUnderscorediskmax = from_dict["vpsUnderscorediskmax"]
	return me


# Won't work for JSON+LD
static func bzz_denormalize_multiple(from_array: Array):
	var mes := Array()
	for element in from_array:
		if element is Array:
			mes.append(bzz_denormalize_multiple(element))
		elif element is Dictionary:
			# TODO: perhaps check first if it looks like a match or an intermediate container
			mes.append(bzz_denormalize_single(element))
		else:
			mes.append(element)
	return mes

