/**
 * InterServer Management API
 * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
 *
 * OpenAPI spec version: 0.9.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import java.text.SimpleDateFormat

import io.swagger.client.model.ChargeInvoiceRows
import io.swagger.client.model.IpObject
import io.swagger.client.model.ServiceOrderPostResponse
import io.swagger.client.model.SuccessTextResponse
import io.swagger.client.model.inline_response_200_3
import io.swagger.client.model.inline_response_401
import io.swagger.client.{ApiInvoker, ApiException}

import com.sun.jersey.multipart.FormDataMultiPart
import com.sun.jersey.multipart.file.FileDataBodyPart

import javax.ws.rs.core.MediaType

import java.io.File
import java.util.Date
import java.util.TimeZone

import scala.collection.mutable.HashMap

import com.wordnik.swagger.client._
import scala.concurrent.Future
import collection.mutable

import java.net.URI

import com.wordnik.swagger.client.ClientResponseReaders.Json4sFormatsReader._
import com.wordnik.swagger.client.RequestWriters.Json4sFormatsWriter._

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent._
import scala.concurrent.duration._
import scala.util.{Failure, Success, Try}

import org.json4s._

class FloatingIPsApi(
  val defBasePath: String = "https://my.interserver.net/apiv2",
  defApiInvoker: ApiInvoker = ApiInvoker
) {
  private lazy val dateTimeFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  private val dateFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  implicit val formats = new org.json4s.DefaultFormats {
    override def dateFormatter = dateTimeFormatter
  }
  implicit val stringReader: ClientResponseReader[String] = ClientResponseReaders.StringReader
  implicit val unitReader: ClientResponseReader[Unit] = ClientResponseReaders.UnitReader
  implicit val jvalueReader: ClientResponseReader[JValue] = ClientResponseReaders.JValueReader
  implicit val jsonReader: ClientResponseReader[Nothing] = JsonFormatsReader
  implicit val stringWriter: RequestWriter[String] = RequestWriters.StringWriter
  implicit val jsonWriter: RequestWriter[Nothing] = JsonFormatsWriter

  var basePath: String = defBasePath
  var apiInvoker: ApiInvoker = defApiInvoker

  def addHeader(key: String, value: String): mutable.HashMap[String, String] = {
    apiInvoker.defaultHeaders += key -> value
  }

  val config: SwaggerConfig = SwaggerConfig.forUrl(new URI(defBasePath))
  val client = new RestClient(config)
  val helper = new FloatingIPsApiAsyncHelper(client, config)

  /**
   * Place Floating IP Order
   * Places an order for a new Floating IP service. Use &#x60;PUT /floating_ips/order&#x60; to validate the order first.
   *
   * @return ServiceOrderPostResponse
   */
  def addFloatingIp(): Option[ServiceOrderPostResponse] = {
    val await = Try(Await.result(addFloatingIpAsync(), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * Place Floating IP Order asynchronously
   * Places an order for a new Floating IP service. Use &#x60;PUT /floating_ips/order&#x60; to validate the order first.
   *
   * @return Future(ServiceOrderPostResponse)
   */
  def addFloatingIpAsync(): Future[ServiceOrderPostResponse] = {
      helper.addFloatingIp()
  }

  /**
   * Cancel Floating IP
   * Cancels a Floating IP service. After cancellation the IP assignment is released and the service transitions to a canceled status. No further billing charges will be incurred.
   *
   * @param id The Floating IP service ID. Use the ID from &#x60;GET /floating_ips&#x60;. 
   * @return inline_response_200_3
   */
  def floatingIpsCancel(id: Integer): Option[inline_response_200_3] = {
    val await = Try(Await.result(floatingIpsCancelAsync(id), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * Cancel Floating IP asynchronously
   * Cancels a Floating IP service. After cancellation the IP assignment is released and the service transitions to a canceled status. No further billing charges will be incurred.
   *
   * @param id The Floating IP service ID. Use the ID from &#x60;GET /floating_ips&#x60;. 
   * @return Future(inline_response_200_3)
   */
  def floatingIpsCancelAsync(id: Integer): Future[inline_response_200_3] = {
      helper.floatingIpsCancel(id)
  }

  /**
   * View Floating IP
   * Returns detailed information about a specific Floating IP service including its current target IP assignment.
   *
   * @param id The Floating IP service ID. Use the ID from &#x60;GET /floating_ips&#x60;. 
   * @return Any
   */
  def getFloatingIpInfo(id: Integer): Option[Any] = {
    val await = Try(Await.result(getFloatingIpInfoAsync(id), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * View Floating IP asynchronously
   * Returns detailed information about a specific Floating IP service including its current target IP assignment.
   *
   * @param id The Floating IP service ID. Use the ID from &#x60;GET /floating_ips&#x60;. 
   * @return Future(Any)
   */
  def getFloatingIpInfoAsync(id: Integer): Future[Any] = {
      helper.getFloatingIpInfo(id)
  }

  /**
   * Get Floating IP Invoices
   * Returns the billing invoices associated with this Floating IP service.
   *
   * @param id The Floating IP service ID. Use the ID from &#x60;GET /floating_ips&#x60;. 
   * @return ChargeInvoiceRows
   */
  def getFloatingIpInvoices(id: Integer): Option[ChargeInvoiceRows] = {
    val await = Try(Await.result(getFloatingIpInvoicesAsync(id), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * Get Floating IP Invoices asynchronously
   * Returns the billing invoices associated with this Floating IP service.
   *
   * @param id The Floating IP service ID. Use the ID from &#x60;GET /floating_ips&#x60;. 
   * @return Future(ChargeInvoiceRows)
   */
  def getFloatingIpInvoicesAsync(id: Integer): Future[ChargeInvoiceRows] = {
      helper.getFloatingIpInvoices(id)
  }

  /**
   * List Floating IPs
   * Returns all Floating IP services on the account with their current status and assignment details.
   *
   * @return List[Any]
   */
  def getFloatingIpsList(): Option[List[Any]] = {
    val await = Try(Await.result(getFloatingIpsListAsync(), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * List Floating IPs asynchronously
   * Returns all Floating IP services on the account with their current status and assignment details.
   *
   * @return Future(List[Any])
   */
  def getFloatingIpsListAsync(): Future[List[Any]] = {
      helper.getFloatingIpsList()
  }

  /**
   * Resend Floating IPs Welcome Email
   * Resends the welcome email for the Floating IP service. The email contains setup instructions and connection details.
   *
   * @param id The Floating IP service ID. Use the ID from &#x60;GET /floating_ips&#x60;. 
   * @return SuccessTextResponse
   */
  def getFloatingIpsWelcomeEmail(id: Integer): Option[SuccessTextResponse] = {
    val await = Try(Await.result(getFloatingIpsWelcomeEmailAsync(id), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * Resend Floating IPs Welcome Email asynchronously
   * Resends the welcome email for the Floating IP service. The email contains setup instructions and connection details.
   *
   * @param id The Floating IP service ID. Use the ID from &#x60;GET /floating_ips&#x60;. 
   * @return Future(SuccessTextResponse)
   */
  def getFloatingIpsWelcomeEmailAsync(id: Integer): Future[SuccessTextResponse] = {
      helper.getFloatingIpsWelcomeEmail(id)
  }

  /**
   * Get Floating IP Ordering Information
   * Retrieves available options and pricing for ordering a new Floating IP.
   *
   * @return Any
   */
  def getNewFloatingIp(): Option[Any] = {
    val await = Try(Await.result(getNewFloatingIpAsync(), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * Get Floating IP Ordering Information asynchronously
   * Retrieves available options and pricing for ordering a new Floating IP.
   *
   * @return Future(Any)
   */
  def getNewFloatingIpAsync(): Future[Any] = {
      helper.getNewFloatingIp()
  }

  /**
   * Change Floating IP Target
   * Changes the target IP address that the Floating IP points to. The Floating IP service must be active. Use &#x60;GET /floating_ips/{id}&#x60; to view the current target before making changes.
   *
   * @param ip  
   * @param body  
   * @param id The Floating IP service ID. Use the ID from &#x60;GET /floating_ips&#x60;. 
   * @return SuccessTextResponse
   */
  def postFloatingIpsChangeIp(ip: String, body: IpObject, id: Integer): Option[SuccessTextResponse] = {
    val await = Try(Await.result(postFloatingIpsChangeIpAsync(ip, body, id), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * Change Floating IP Target asynchronously
   * Changes the target IP address that the Floating IP points to. The Floating IP service must be active. Use &#x60;GET /floating_ips/{id}&#x60; to view the current target before making changes.
   *
   * @param ip  
   * @param body  
   * @param id The Floating IP service ID. Use the ID from &#x60;GET /floating_ips&#x60;. 
   * @return Future(SuccessTextResponse)
   */
  def postFloatingIpsChangeIpAsync(ip: String, body: IpObject, id: Integer): Future[SuccessTextResponse] = {
      helper.postFloatingIpsChangeIp(ip, body, id)
  }

  /**
   * Validate Floating IP Order
   * Validates a Floating IP order before placing it. Use this to check for errors before committing to a purchase.
   *
   * @return void
   */
  def putFloatingIps() = {
    val await = Try(Await.result(putFloatingIpsAsync(), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * Validate Floating IP Order asynchronously
   * Validates a Floating IP order before placing it. Use this to check for errors before committing to a purchase.
   *
   * @return Future(void)
   */
  def putFloatingIpsAsync() = {
      helper.putFloatingIps()
  }

  /**
   * Update Floating IP
   * Updates settings on a Floating IP service, such as its label or configuration metadata.
   *
   * @param id The Floating IP service ID. Use the ID from &#x60;GET /floating_ips&#x60;. 
   * @return SuccessTextResponse
   */
  def updateFloatingIpInfo(id: String): Option[SuccessTextResponse] = {
    val await = Try(Await.result(updateFloatingIpInfoAsync(id), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * Update Floating IP asynchronously
   * Updates settings on a Floating IP service, such as its label or configuration metadata.
   *
   * @param id The Floating IP service ID. Use the ID from &#x60;GET /floating_ips&#x60;. 
   * @return Future(SuccessTextResponse)
   */
  def updateFloatingIpInfoAsync(id: String): Future[SuccessTextResponse] = {
      helper.updateFloatingIpInfo(id)
  }

}

class FloatingIPsApiAsyncHelper(client: TransportClient, config: SwaggerConfig) extends ApiClient(client, config) {

  def addFloatingIp()(implicit reader: ClientResponseReader[ServiceOrderPostResponse]): Future[ServiceOrderPostResponse] = {
    // create path and map variables
    val path = (addFmt("/floating_ips/order"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("POST", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def floatingIpsCancel(id: Integer)(implicit reader: ClientResponseReader[inline_response_200_3]): Future[inline_response_200_3] = {
    // create path and map variables
    val path = (addFmt("/floating_ips/{id}")
      replaceAll("\\{" + "id" + "\\}", id.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("DELETE", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def getFloatingIpInfo(id: Integer)(implicit reader: ClientResponseReader[Any]): Future[Any] = {
    // create path and map variables
    val path = (addFmt("/floating_ips/{id}")
      replaceAll("\\{" + "id" + "\\}", id.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def getFloatingIpInvoices(id: Integer)(implicit reader: ClientResponseReader[ChargeInvoiceRows]): Future[ChargeInvoiceRows] = {
    // create path and map variables
    val path = (addFmt("/floating_ips/{id}/invoices")
      replaceAll("\\{" + "id" + "\\}", id.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def getFloatingIpsList()(implicit reader: ClientResponseReader[List[Any]]): Future[List[Any]] = {
    // create path and map variables
    val path = (addFmt("/floating_ips"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def getFloatingIpsWelcomeEmail(id: Integer)(implicit reader: ClientResponseReader[SuccessTextResponse]): Future[SuccessTextResponse] = {
    // create path and map variables
    val path = (addFmt("/floating_ips/{id}/welcome_email")
      replaceAll("\\{" + "id" + "\\}", id.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def getNewFloatingIp()(implicit reader: ClientResponseReader[Any]): Future[Any] = {
    // create path and map variables
    val path = (addFmt("/floating_ips/order"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def postFloatingIpsChangeIp(ip: String,
    body: IpObject,
    id: Integer)(implicit reader: ClientResponseReader[SuccessTextResponse], writer: RequestWriter[IpObject]): Future[SuccessTextResponse] = {
    // create path and map variables
    val path = (addFmt("/floating_ips/{id}/change_ip")
      replaceAll("\\{" + "id" + "\\}", id.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (ip == null) throw new Exception("Missing required parameter 'ip' when calling FloatingIPsApi->postFloatingIpsChangeIp")

    if (body == null) throw new Exception("Missing required parameter 'body' when calling FloatingIPsApi->postFloatingIpsChangeIp")

    val resFuture = client.submit("POST", path, queryParams.toMap, headerParams.toMap, writer.write(body))
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def putFloatingIps()(implicit reader: ClientResponseReader[Unit]): Future[Unit] = {
    // create path and map variables
    val path = (addFmt("/floating_ips/order"))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]


    val resFuture = client.submit("PUT", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }

  def updateFloatingIpInfo(id: String)(implicit reader: ClientResponseReader[SuccessTextResponse]): Future[SuccessTextResponse] = {
    // create path and map variables
    val path = (addFmt("/floating_ips/{id}")
      replaceAll("\\{" + "id" + "\\}", id.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (id == null) throw new Exception("Missing required parameter 'id' when calling FloatingIPsApi->updateFloatingIpInfo")


    val resFuture = client.submit("POST", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }


}
