const utils = require('../utils/utils');

module.exports = {
        fields: (key) => (
            {
                label: `Type of DNS Record - [${key.replaceAll('__', '.')}]`,
                choices: [
                    'A',
                    'A6',
                    'AAAA',
                    'AFSDB',
                    'ALIAS',
                    'CAA',
                    'CDNSKEY',
                    'CDS',
                    'CERT',
                    'CNAME',
                    'DHCID',
                    'DLV',
                    'DNSKEY',
                    'DNAME',
                    'DS',
                    'EUI48',
                    'EUI64',
                    'HINFO',
                    'IPSECKEY',
                    'KEY',
                    'KX',
                    'LOC',
                    'MAILA',
                    'MAILB',
                    'MINFO',
                    'MR',
                    'MX',
                    'NAPTR',
                    'NS',
                    'NSEC',
                    'NSEC3',
                    'NSEC3PARAM',
                    'OPENPGPKEY',
                    'OPT',
                    'PTR',
                    'RKEY',
                    'RP',
                    'RRSIG',
                    'SIG',
                    'SOA',
                    'SPF',
                    'SRV',
                    'SSHFP',
                    'TLSA',
                    'TKEY',
                    'TSIG',
                    'TXT',
                    'WKS',
                    'URI⏎',
                ],
            }
        )
    }
