const utils = require('../utils/utils');
const ServerLease = require('../models/ServerLease');

module.exports = {
    fields: (prefix = '', isInput = true, isArrayChild = false) => {
        const {keyPrefix, labelPrefix} = utils.buildKeyAndLabel(prefix, isInput, isArrayChild)
        return [
            {
                key: `${keyPrefix}id`,
                label: `Unique identifier for the asset. - [${labelPrefix}id]`,
                required: true,
                type: 'integer',
            },
            {
                key: `${keyPrefix}order_id`,
                label: `Order identifier for the asset. - [${labelPrefix}order_id]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}hostname`,
                label: `Hostname associated with the asset. - [${labelPrefix}hostname]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}status`,
                label: `Status of the asset. - [${labelPrefix}status]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}primary_ipv4`,
                label: `Primary IPv4 address of the asset. - [${labelPrefix}primary_ipv4]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}primary_ipv6`,
                label: `Primary IPv6 address of the asset. - [${labelPrefix}primary_ipv6]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}datacenter`,
                label: `Datacenter identifier for the asset. - [${labelPrefix}datacenter]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}type_id`,
                label: `Type identifier for the asset. - [${labelPrefix}type_id]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}asset_tag`,
                label: `Asset tag associated with the asset. - [${labelPrefix}asset_tag]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}rack`,
                label: `Rack identifier for the asset. - [${labelPrefix}rack]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}row`,
                label: `Row identifier for the asset. - [${labelPrefix}row]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}col`,
                label: `Column identifier for the asset. - [${labelPrefix}col]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}unit_start`,
                label: `Starting unit identifier for the asset. - [${labelPrefix}unit_start]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}unit_end`,
                label: `Ending unit identifier for the asset. - [${labelPrefix}unit_end]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}unit_sub`,
                label: `Subunit identifier for the asset. - [${labelPrefix}unit_sub]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}ipmi_mac`,
                label: `IPMI MAC address associated with the asset. - [${labelPrefix}ipmi_mac]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}ipmi_ip`,
                label: `IPMI IP address associated with the asset. - [${labelPrefix}ipmi_ip]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}ipmi_working`,
                label: `IPMI working status associated with the asset. - [${labelPrefix}ipmi_working]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}company`,
                label: `Company associated with the asset. - [${labelPrefix}company]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}comments`,
                label: `Comments associated with the asset. - [${labelPrefix}comments]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}make`,
                label: `Make of the asset. - [${labelPrefix}make]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}model`,
                label: `Model of the asset. - [${labelPrefix}model]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}description`,
                label: `Description of the asset. - [${labelPrefix}description]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}customer_id`,
                label: `Customer identifier for the asset. - [${labelPrefix}customer_id]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}external_id`,
                label: `External identifier for the asset. - [${labelPrefix}external_id]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}billing_status`,
                label: `Billing status of the asset. - [${labelPrefix}billing_status]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}overdue`,
                label: `Overdue status of the asset. - [${labelPrefix}overdue]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}asset_id`,
                label: `Asset identifier for the asset. - [${labelPrefix}asset_id]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}asset_name`,
                label: `Name of the asset. - [${labelPrefix}asset_name]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}rack_id`,
                label: `Rack identifier for the asset. - [${labelPrefix}rack_id]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}rack_name`,
                label: `Rack name associated with the asset. - [${labelPrefix}rack_name]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}rack_location`,
                label: `Location of the rack associated with the asset. - [${labelPrefix}rack_location]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}rack_size`,
                label: `Size of the rack associated with the asset. - [${labelPrefix}rack_size]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}rack_x`,
                label: `X-coordinate of the asset within the rack. - [${labelPrefix}rack_x]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}rack_y`,
                label: `Y-coordinate of the asset within the rack. - [${labelPrefix}rack_y]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}switchports`,
                label: `List of switchports associated with the asset. - [${labelPrefix}switchports]`,
                required: true,
                list: true,
                type: 'integer',
            },
            {
                key: `${keyPrefix}vlans`,
                label: `List of VLANs associated with the asset. - [${labelPrefix}vlans]`,
                required: true,
                list: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}vlans6`,
                label: `List of IPv6 VLANs associated with the asset. - [${labelPrefix}vlans6]`,
                required: true,
                list: true,
                type: 'string',
            },
            ...ServerLease.fields(`${keyPrefix}lease`, isInput),
            {
                key: `${keyPrefix}mac`,
                label: `MAC address associated with the asset. - [${labelPrefix}mac]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}ipmi_admin_username`,
                label: `IPMI admin username associated with the asset. - [${labelPrefix}ipmi_admin_username]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}ipmi_admin_password`,
                label: `IPMI admin password associated with the asset. - [${labelPrefix}ipmi_admin_password]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}ipmi_client_username`,
                label: `IPMI client username associated with the asset. - [${labelPrefix}ipmi_client_username]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}ipmi_client_password`,
                label: `IPMI client password associated with the asset. - [${labelPrefix}ipmi_client_password]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}ipmi_updated`,
                label: `IPMI update status associated with the asset. - [${labelPrefix}ipmi_updated]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}create_timestamp`,
                label: `Timestamp of asset creation. - [${labelPrefix}create_timestamp]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}update_timestamp`,
                label: `Timestamp of asset update. - [${labelPrefix}update_timestamp]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}comment`,
                label: `Comment associated with the asset. - [${labelPrefix}comment]`,
                type: 'string',
            },
        ]
    },
    mapping: (bundle, prefix = '') => {
        const {keyPrefix} = utils.buildKeyAndLabel(prefix)
        return {
            'id': bundle.inputData?.[`${keyPrefix}id`],
            'order_id': bundle.inputData?.[`${keyPrefix}order_id`],
            'hostname': bundle.inputData?.[`${keyPrefix}hostname`],
            'status': bundle.inputData?.[`${keyPrefix}status`],
            'primary_ipv4': bundle.inputData?.[`${keyPrefix}primary_ipv4`],
            'primary_ipv6': bundle.inputData?.[`${keyPrefix}primary_ipv6`],
            'datacenter': bundle.inputData?.[`${keyPrefix}datacenter`],
            'type_id': bundle.inputData?.[`${keyPrefix}type_id`],
            'asset_tag': bundle.inputData?.[`${keyPrefix}asset_tag`],
            'rack': bundle.inputData?.[`${keyPrefix}rack`],
            'row': bundle.inputData?.[`${keyPrefix}row`],
            'col': bundle.inputData?.[`${keyPrefix}col`],
            'unit_start': bundle.inputData?.[`${keyPrefix}unit_start`],
            'unit_end': bundle.inputData?.[`${keyPrefix}unit_end`],
            'unit_sub': bundle.inputData?.[`${keyPrefix}unit_sub`],
            'ipmi_mac': bundle.inputData?.[`${keyPrefix}ipmi_mac`],
            'ipmi_ip': bundle.inputData?.[`${keyPrefix}ipmi_ip`],
            'ipmi_working': bundle.inputData?.[`${keyPrefix}ipmi_working`],
            'company': bundle.inputData?.[`${keyPrefix}company`],
            'comments': bundle.inputData?.[`${keyPrefix}comments`],
            'make': bundle.inputData?.[`${keyPrefix}make`],
            'model': bundle.inputData?.[`${keyPrefix}model`],
            'description': bundle.inputData?.[`${keyPrefix}description`],
            'customer_id': bundle.inputData?.[`${keyPrefix}customer_id`],
            'external_id': bundle.inputData?.[`${keyPrefix}external_id`],
            'billing_status': bundle.inputData?.[`${keyPrefix}billing_status`],
            'overdue': bundle.inputData?.[`${keyPrefix}overdue`],
            'asset_id': bundle.inputData?.[`${keyPrefix}asset_id`],
            'asset_name': bundle.inputData?.[`${keyPrefix}asset_name`],
            'rack_id': bundle.inputData?.[`${keyPrefix}rack_id`],
            'rack_name': bundle.inputData?.[`${keyPrefix}rack_name`],
            'rack_location': bundle.inputData?.[`${keyPrefix}rack_location`],
            'rack_size': bundle.inputData?.[`${keyPrefix}rack_size`],
            'rack_x': bundle.inputData?.[`${keyPrefix}rack_x`],
            'rack_y': bundle.inputData?.[`${keyPrefix}rack_y`],
            'switchports': bundle.inputData?.[`${keyPrefix}switchports`],
            'vlans': bundle.inputData?.[`${keyPrefix}vlans`],
            'vlans6': bundle.inputData?.[`${keyPrefix}vlans6`],
            'lease': utils.removeIfEmpty(ServerLease.mapping(bundle, `${keyPrefix}lease`)),
            'mac': bundle.inputData?.[`${keyPrefix}mac`],
            'ipmi_admin_username': bundle.inputData?.[`${keyPrefix}ipmi_admin_username`],
            'ipmi_admin_password': bundle.inputData?.[`${keyPrefix}ipmi_admin_password`],
            'ipmi_client_username': bundle.inputData?.[`${keyPrefix}ipmi_client_username`],
            'ipmi_client_password': bundle.inputData?.[`${keyPrefix}ipmi_client_password`],
            'ipmi_updated': bundle.inputData?.[`${keyPrefix}ipmi_updated`],
            'create_timestamp': bundle.inputData?.[`${keyPrefix}create_timestamp`],
            'update_timestamp': bundle.inputData?.[`${keyPrefix}update_timestamp`],
            'comment': bundle.inputData?.[`${keyPrefix}comment`],
        }
    },
}
