/*
 * InterServer Management API
 * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * ServerClientLink
 */
@JsonPropertyOrder({
  ServerClientLink.JSON_PROPERTY_LABEL,
  ServerClientLink.JSON_PROPERTY_LINK,
  ServerClientLink.JSON_PROPERTY_ICON,
  ServerClientLink.JSON_PROPERTY_ICON_TEXT,
  ServerClientLink.JSON_PROPERTY_HELP_TEXT
})
@JsonTypeName("ServerClientLink")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2026-03-25T16:38:58.640178313-04:00[America/New_York]", comments = "Generator version: 7.21.0")
@Introspected
public class ServerClientLink {
    public static final String JSON_PROPERTY_LABEL = "label";
    private String label;

    public static final String JSON_PROPERTY_LINK = "link";
    private String link;

    public static final String JSON_PROPERTY_ICON = "icon";
    private String icon;

    public static final String JSON_PROPERTY_ICON_TEXT = "icon_text";
    private String iconText;

    public static final String JSON_PROPERTY_HELP_TEXT = "help_text";
    private String helpText;

    public ServerClientLink(String label, String link) {
        this.label = label;
        this.link = link;
    }

    public ServerClientLink label(String label) {
        this.label = label;
        return this;
    }

    /**
     * Get label
     * @return label
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_LABEL)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getLabel() {
        return label;
    }

    @JsonProperty(JSON_PROPERTY_LABEL)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setLabel(String label) {
        this.label = label;
    }

    public ServerClientLink link(String link) {
        this.link = link;
        return this;
    }

    /**
     * Get link
     * @return link
     */
    @NotNull
    @JsonProperty(JSON_PROPERTY_LINK)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getLink() {
        return link;
    }

    @JsonProperty(JSON_PROPERTY_LINK)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setLink(String link) {
        this.link = link;
    }

    public ServerClientLink icon(String icon) {
        this.icon = icon;
        return this;
    }

    /**
     * Get icon
     * @return icon
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_ICON)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getIcon() {
        return icon;
    }

    @JsonProperty(JSON_PROPERTY_ICON)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIcon(String icon) {
        this.icon = icon;
    }

    public ServerClientLink iconText(String iconText) {
        this.iconText = iconText;
        return this;
    }

    /**
     * Get iconText
     * @return iconText
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_ICON_TEXT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getIconText() {
        return iconText;
    }

    @JsonProperty(JSON_PROPERTY_ICON_TEXT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIconText(String iconText) {
        this.iconText = iconText;
    }

    public ServerClientLink helpText(String helpText) {
        this.helpText = helpText;
        return this;
    }

    /**
     * Get helpText
     * @return helpText
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_HELP_TEXT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getHelpText() {
        return helpText;
    }

    @JsonProperty(JSON_PROPERTY_HELP_TEXT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setHelpText(String helpText) {
        this.helpText = helpText;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ServerClientLink serverClientLink = (ServerClientLink) o;
        return Objects.equals(this.label, serverClientLink.label) &&
            Objects.equals(this.link, serverClientLink.link) &&
            Objects.equals(this.icon, serverClientLink.icon) &&
            Objects.equals(this.iconText, serverClientLink.iconText) &&
            Objects.equals(this.helpText, serverClientLink.helpText);
    }

    @Override
    public int hashCode() {
        return Objects.hash(label, link, icon, iconText, helpText);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ServerClientLink {\n");
        sb.append("    label: ").append(toIndentedString(label)).append("\n");
        sb.append("    link: ").append(toIndentedString(link)).append("\n");
        sb.append("    icon: ").append(toIndentedString(icon)).append("\n");
        sb.append("    iconText: ").append(toIndentedString(iconText)).append("\n");
        sb.append("    helpText: ").append(toIndentedString(helpText)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        return o == null ? "null" : o.toString().replace("\n", "\n    ");
    }

}

