(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Backups_order.t : Available backup storage packages and pricing for ordering a new backup service.
 *)



    
        type t = {
                              package_costs: Backups_order_package_costs.t
                  
                  
                
                
                ; [@key "packageCosts"]
                                              service_types: Backups_order_service_types.t
                  
                  
                
                
                ; [@key "serviceTypes"]
                        } [@@deriving yojson { strict = false }, show, eq ];;
        
        (** Available backup storage packages and pricing for ordering a new backup service. *)
        let create (package_costs : Backups_order_package_costs.t) (service_types : Backups_order_service_types.t) : t = {
            package_costs = package_costs;
            service_types = service_types;
        }
    

