(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Ticket_details.t : Detailed ticket information
 *)



    
        type t = {
                              ticketid: int32
                  
                   option [@default None]
                
                
                ; [@key "ticketid"]
                                              ticketmaskid: string
                  
                   option [@default None]
                
                
                ; [@key "ticketmaskid"]
                                              department: string
                  
                   option [@default None]
                
                
                ; [@key "department"]
                                              status: string
                  
                   option [@default None]
                
                
                ; [@key "status"]
                                              priority: string
                  
                   option [@default None]
                
                
                ; [@key "priority"]
                                              subject: string
                  
                   option [@default None]
                
                
                ; [@key "subject"]
                                              created_on: string
                  
                   option [@default None]
                
                
                ; [@key "created_on"]
                                              updated_on: string
                  
                   option [@default None]
                
                
                ; [@key "updated_on"]
                        } [@@deriving yojson { strict = false }, show, eq ];;
        
        (** Detailed ticket information *)
        let create () : t = {
            ticketid = None;
            ticketmaskid = None;
            department = None;
            status = None;
            priority = None;
            subject = None;
            created_on = None;
            updated_on = None;
        }
    

