@isTest
private class OASBillingPrepayRequestTest {
    @isTest
    private static void equalsSameInstance() {
        OASBillingPrepayRequest billingPrepayRequest1 = OASBillingPrepayRequest.getExample();
        OASBillingPrepayRequest billingPrepayRequest2 = billingPrepayRequest1;
        OASBillingPrepayRequest billingPrepayRequest3 = new OASBillingPrepayRequest();
        OASBillingPrepayRequest billingPrepayRequest4 = billingPrepayRequest3;

        System.assert(billingPrepayRequest1.equals(billingPrepayRequest2));
        System.assert(billingPrepayRequest2.equals(billingPrepayRequest1));
        System.assert(billingPrepayRequest1.equals(billingPrepayRequest1));
        System.assert(billingPrepayRequest3.equals(billingPrepayRequest4));
        System.assert(billingPrepayRequest4.equals(billingPrepayRequest3));
        System.assert(billingPrepayRequest3.equals(billingPrepayRequest3));
    }

    @isTest
    private static void equalsIdenticalInstance() {
        OASBillingPrepayRequest billingPrepayRequest1 = OASBillingPrepayRequest.getExample();
        OASBillingPrepayRequest billingPrepayRequest2 = OASBillingPrepayRequest.getExample();
        OASBillingPrepayRequest billingPrepayRequest3 = new OASBillingPrepayRequest();
        OASBillingPrepayRequest billingPrepayRequest4 = new OASBillingPrepayRequest();

        System.assert(billingPrepayRequest1.equals(billingPrepayRequest2));
        System.assert(billingPrepayRequest2.equals(billingPrepayRequest1));
        System.assert(billingPrepayRequest3.equals(billingPrepayRequest4));
        System.assert(billingPrepayRequest4.equals(billingPrepayRequest3));
    }

    @isTest
    private static void notEqualsDifferentType() {
        OASBillingPrepayRequest billingPrepayRequest1 = OASBillingPrepayRequest.getExample();
        OASBillingPrepayRequest billingPrepayRequest2 = new OASBillingPrepayRequest();

        System.assertEquals(false, billingPrepayRequest1.equals('foo'));
        System.assertEquals(false, billingPrepayRequest2.equals('foo'));
    }

    @isTest
    private static void notEqualsNull() {
        OASBillingPrepayRequest billingPrepayRequest1 = OASBillingPrepayRequest.getExample();
        OASBillingPrepayRequest billingPrepayRequest2 = new OASBillingPrepayRequest();
        OASBillingPrepayRequest billingPrepayRequest3;

        System.assertEquals(false, billingPrepayRequest1.equals(billingPrepayRequest3));
        System.assertEquals(false, billingPrepayRequest2.equals(billingPrepayRequest3));
    }

    @isTest
    private static void consistentHashCodeValue() {
        OASBillingPrepayRequest billingPrepayRequest1 = OASBillingPrepayRequest.getExample();
        OASBillingPrepayRequest billingPrepayRequest2 = new OASBillingPrepayRequest();

        System.assertEquals(billingPrepayRequest1.hashCode(), billingPrepayRequest1.hashCode());
        System.assertEquals(billingPrepayRequest2.hashCode(), billingPrepayRequest2.hashCode());
    }

    @isTest
    private static void equalInstancesHaveSameHashCode() {
        OASBillingPrepayRequest billingPrepayRequest1 = OASBillingPrepayRequest.getExample();
        OASBillingPrepayRequest billingPrepayRequest2 = OASBillingPrepayRequest.getExample();
        OASBillingPrepayRequest billingPrepayRequest3 = new OASBillingPrepayRequest();
        OASBillingPrepayRequest billingPrepayRequest4 = new OASBillingPrepayRequest();

        System.assert(billingPrepayRequest1.equals(billingPrepayRequest2));
        System.assert(billingPrepayRequest3.equals(billingPrepayRequest4));
        System.assertEquals(billingPrepayRequest1.hashCode(), billingPrepayRequest2.hashCode());
        System.assertEquals(billingPrepayRequest3.hashCode(), billingPrepayRequest4.hashCode());
    }

    @isTest
    private static void maintainRenamedProperties() {
        OASBillingPrepayRequest billingPrepayRequest = new OASBillingPrepayRequest();
        Map<String, String> x-property-mappings = billingPrepayRequest.getx-property-mappings();
        System.assertEquals('automaticUse', x-property-mappings.get('automatic_use'));
    }
}
