@isTest
private class OASDeleteFilter200ResponseTest {
    @isTest
    private static void equalsSameInstance() {
        OASDeleteFilter200Response deleteFilter200Response1 = OASDeleteFilter200Response.getExample();
        OASDeleteFilter200Response deleteFilter200Response2 = deleteFilter200Response1;
        OASDeleteFilter200Response deleteFilter200Response3 = new OASDeleteFilter200Response();
        OASDeleteFilter200Response deleteFilter200Response4 = deleteFilter200Response3;

        System.assert(deleteFilter200Response1.equals(deleteFilter200Response2));
        System.assert(deleteFilter200Response2.equals(deleteFilter200Response1));
        System.assert(deleteFilter200Response1.equals(deleteFilter200Response1));
        System.assert(deleteFilter200Response3.equals(deleteFilter200Response4));
        System.assert(deleteFilter200Response4.equals(deleteFilter200Response3));
        System.assert(deleteFilter200Response3.equals(deleteFilter200Response3));
    }

    @isTest
    private static void equalsIdenticalInstance() {
        OASDeleteFilter200Response deleteFilter200Response1 = OASDeleteFilter200Response.getExample();
        OASDeleteFilter200Response deleteFilter200Response2 = OASDeleteFilter200Response.getExample();
        OASDeleteFilter200Response deleteFilter200Response3 = new OASDeleteFilter200Response();
        OASDeleteFilter200Response deleteFilter200Response4 = new OASDeleteFilter200Response();

        System.assert(deleteFilter200Response1.equals(deleteFilter200Response2));
        System.assert(deleteFilter200Response2.equals(deleteFilter200Response1));
        System.assert(deleteFilter200Response3.equals(deleteFilter200Response4));
        System.assert(deleteFilter200Response4.equals(deleteFilter200Response3));
    }

    @isTest
    private static void notEqualsDifferentType() {
        OASDeleteFilter200Response deleteFilter200Response1 = OASDeleteFilter200Response.getExample();
        OASDeleteFilter200Response deleteFilter200Response2 = new OASDeleteFilter200Response();

        System.assertEquals(false, deleteFilter200Response1.equals('foo'));
        System.assertEquals(false, deleteFilter200Response2.equals('foo'));
    }

    @isTest
    private static void notEqualsNull() {
        OASDeleteFilter200Response deleteFilter200Response1 = OASDeleteFilter200Response.getExample();
        OASDeleteFilter200Response deleteFilter200Response2 = new OASDeleteFilter200Response();
        OASDeleteFilter200Response deleteFilter200Response3;

        System.assertEquals(false, deleteFilter200Response1.equals(deleteFilter200Response3));
        System.assertEquals(false, deleteFilter200Response2.equals(deleteFilter200Response3));
    }

    @isTest
    private static void consistentHashCodeValue() {
        OASDeleteFilter200Response deleteFilter200Response1 = OASDeleteFilter200Response.getExample();
        OASDeleteFilter200Response deleteFilter200Response2 = new OASDeleteFilter200Response();

        System.assertEquals(deleteFilter200Response1.hashCode(), deleteFilter200Response1.hashCode());
        System.assertEquals(deleteFilter200Response2.hashCode(), deleteFilter200Response2.hashCode());
    }

    @isTest
    private static void equalInstancesHaveSameHashCode() {
        OASDeleteFilter200Response deleteFilter200Response1 = OASDeleteFilter200Response.getExample();
        OASDeleteFilter200Response deleteFilter200Response2 = OASDeleteFilter200Response.getExample();
        OASDeleteFilter200Response deleteFilter200Response3 = new OASDeleteFilter200Response();
        OASDeleteFilter200Response deleteFilter200Response4 = new OASDeleteFilter200Response();

        System.assert(deleteFilter200Response1.equals(deleteFilter200Response2));
        System.assert(deleteFilter200Response3.equals(deleteFilter200Response4));
        System.assertEquals(deleteFilter200Response1.hashCode(), deleteFilter200Response2.hashCode());
        System.assertEquals(deleteFilter200Response3.hashCode(), deleteFilter200Response4.hashCode());
    }
}
