# InterServer Management API
#
# # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
#
# OpenAPI spec version: 0.9.0
# Contact: support@interserver.net
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' InlineResponse20025 Class
#'
#' @field message 
#' @field success 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
InlineResponse20025 <- R6::R6Class(
  'InlineResponse20025',
  public = list(
    `message` = NULL,
    `success` = NULL,
    initialize = function(`message`, `success`){
      if (!missing(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
      if (!missing(`success`)) {
        self$`success` <- `success`
      }
    },
    toJSON = function() {
      InlineResponse20025Object <- list()
      if (!is.null(self$`message`)) {
        InlineResponse20025Object[['message']] <- self$`message`
      }
      if (!is.null(self$`success`)) {
        InlineResponse20025Object[['success']] <- self$`success`
      }

      InlineResponse20025Object
    },
    fromJSON = function(InlineResponse20025Json) {
      InlineResponse20025Object <- jsonlite::fromJSON(InlineResponse20025Json)
      if (!is.null(InlineResponse20025Object$`message`)) {
        self$`message` <- InlineResponse20025Object$`message`
      }
      if (!is.null(InlineResponse20025Object$`success`)) {
        self$`success` <- InlineResponse20025Object$`success`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "message": %s,
           "success": %s
        }',
        self$`message`,
        self$`success`
      )
    },
    fromJSONString = function(InlineResponse20025Json) {
      InlineResponse20025Object <- jsonlite::fromJSON(InlineResponse20025Json)
      self$`message` <- InlineResponse20025Object$`message`
      self$`success` <- InlineResponse20025Object$`success`
    }
  )
)
