// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GetWebsiteBuyIp200Response - GetWebsiteBuyIp200Response struct
type GetWebsiteBuyIp200Response struct {
	Ips map[string]string `json:"ips,omitempty"`
}
