// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// LicensesOrder - Available license packages and pricing for ordering a new software license.
type LicensesOrder struct {
	ServiceCategories LicensesOrderServiceCategories `json:"serviceCategories,omitempty"`
	PackageCosts LicensesOrderPackageCosts `json:"packageCosts,omitempty"`
	ServiceTypes LicensesOrderServiceTypes `json:"serviceTypes,omitempty"`
}
