// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// SslCancel200Response - SslCancel200Response struct
type SslCancel200Response struct {
	Success bool `json:"success"`
	Text string `json:"text"`
}
