//
// ServersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech

import Foundation
import Combine
import OpenAPITransport


open class ServersAPI {
    private let transport: OpenAPITransport
    public var encoder: JSONEncoder = {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .formatted(OpenISO8601DateFormatter())
        return encoder
    }()
    public var decoder: JSONDecoder = {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .formatted(OpenISO8601DateFormatter())
        return decoder
    }()
    public var baseURL = URL(string: "https://my.interserver.net/apiv2")

    public init(_ transport: OpenAPITransport) {
        self.transport = transport
    }

    public enum AddServerError: Error, CustomStringConvertible {
        // Unauthorized
        case code401Error(GetAccountInfo401Response)

        public var description: String {
            switch self {
            case .code401Error(let object):
                return "AddServerError: Unauthorized: \(object)"
            }
        }
    }

    /// Place Server Order
    /// - POST /servers/order
    /// - Places an order for a new dedicated server. Use `PUT /servers/order` to validate the order first.
    /// - API Key:
    /// - type: apiKey sessionid 
    /// - name: sessionIdCookieAuth
    /// - API Key:
    /// - type: apiKey X-API-KEY (HEADER)
    /// - name: apiKeyAuth
    /// - API Key:
    /// - type: apiKey sessionid (HEADER)
    /// - name: sessionIdHeaderAuth
    /// - returns: AnyPublisher<Void, Error> 
    open func addServer() -> AnyPublisher<Void, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                let localVarPath = "/servers/order"
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "POST"
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<Void, Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 401 {
                        do {
                            let error = try self.decoder.decode(GetAccountInfo401Response.self, from: transportError.data)
                            return AddServerError.code401Error(error)
                        } catch {
                            return error
                        }
                    }
                    return transportError
                }
                .tryMap { response in
                    return ()
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }

    public enum BuyItNowServerOrderError: Error, CustomStringConvertible {
        // Unauthorized
        case code401Error(GetAccountInfo401Response)

        public var description: String {
            switch self {
            case .code401Error(let object):
                return "BuyItNowServerOrderError: Unauthorized: \(object)"
            }
        }
    }

    /// Get Buy Now Server Options
    /// - GET /servers/order/buy_now_server
    /// - Returns the configuration options and pricing for buy-it-now dedicated servers, including available bandwidth packages, IP blocks, operating systems, control panels, and RAID configurations. Use the returned option IDs when placing an order via `POST /servers/order/buy_now_server`.
    /// - API Key:
    /// - type: apiKey sessionid 
    /// - name: sessionIdCookieAuth
    /// - API Key:
    /// - type: apiKey X-API-KEY (HEADER)
    /// - name: apiKeyAuth
    /// - API Key:
    /// - type: apiKey sessionid (HEADER)
    /// - name: sessionIdHeaderAuth
    /// - returns: AnyPublisher<BuyItNowServerOrder200Response, Error> 
    open func buyItNowServerOrder() -> AnyPublisher<BuyItNowServerOrder200Response, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                let localVarPath = "/servers/order/buy_now_server"
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "GET"
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<BuyItNowServerOrder200Response, Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 401 {
                        do {
                            let error = try self.decoder.decode(GetAccountInfo401Response.self, from: transportError.data)
                            return BuyItNowServerOrderError.code401Error(error)
                        } catch {
                            return error
                        }
                    }
                    return transportError
                }
                .tryMap { response in
                    try self.decoder.decode(BuyItNowServerOrder200Response.self, from: response.data)
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }

    public enum GetMPServersError: Error, CustomStringConvertible {
        // Unauthorized
        case code401Error(GetAccountInfo401Response)

        public var description: String {
            switch self {
            case .code401Error(let object):
                return "GetMPServersError: Unauthorized: \(object)"
            }
        }
    }

    /// List Marketplace Servers
    /// - GET /buy_now_servers_list
    /// - Returns the list of available Rapid Deploy dedicated servers with current pricing. Each entry includes CPU, memory, disk, bandwidth, IP allocation, and location details. These servers are pre-configured and can be provisioned immediately after purchase.
    /// - API Key:
    /// - type: apiKey sessionid 
    /// - name: sessionIdCookieAuth
    /// - API Key:
    /// - type: apiKey X-API-KEY (HEADER)
    /// - name: apiKeyAuth
    /// - API Key:
    /// - type: apiKey sessionid (HEADER)
    /// - name: sessionIdHeaderAuth
    /// - returns: AnyPublisher<BuyItNowList, Error> 
    open func getMPServers() -> AnyPublisher<BuyItNowList, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                let localVarPath = "/buy_now_servers_list"
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "GET"
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<BuyItNowList, Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 401 {
                        do {
                            let error = try self.decoder.decode(GetAccountInfo401Response.self, from: transportError.data)
                            return GetMPServersError.code401Error(error)
                        } catch {
                            return error
                        }
                    }
                    return transportError
                }
                .tryMap { response in
                    try self.decoder.decode(BuyItNowList.self, from: response.data)
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }

    public enum GetNewServerError: Error, CustomStringConvertible {
        // Unauthorized
        case code401Error(GetAccountInfo401Response)

        public var description: String {
            switch self {
            case .code401Error(let object):
                return "GetNewServerError: Unauthorized: \(object)"
            }
        }
    }

    /// Server Ordering Information
    /// - GET /servers/order
    /// - Retrieves available server configurations and pricing for ordering a new dedicated server.
    /// - API Key:
    /// - type: apiKey sessionid 
    /// - name: sessionIdCookieAuth
    /// - API Key:
    /// - type: apiKey X-API-KEY (HEADER)
    /// - name: apiKeyAuth
    /// - API Key:
    /// - type: apiKey sessionid (HEADER)
    /// - name: sessionIdHeaderAuth
    /// - returns: AnyPublisher<ServerOrder, Error> 
    open func getNewServer() -> AnyPublisher<ServerOrder, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                let localVarPath = "/servers/order"
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "GET"
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<ServerOrder, Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 401 {
                        do {
                            let error = try self.decoder.decode(GetAccountInfo401Response.self, from: transportError.data)
                            return GetNewServerError.code401Error(error)
                        } catch {
                            return error
                        }
                    }
                    return transportError
                }
                .tryMap { response in
                    try self.decoder.decode(ServerOrder.self, from: response.data)
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }

    public enum GetServerInfoError: Error, CustomStringConvertible {
        // Unauthorized
        case code401Error(GetAccountInfo401Response)

        public var description: String {
            switch self {
            case .code401Error(let object):
                return "GetServerInfoError: Unauthorized: \(object)"
            }
        }
    }

    /// Get Server Order
    /// - GET /servers/{id}
    /// - Returns detailed information about a specific server including its hardware configuration, IPs, and status.
    /// - API Key:
    /// - type: apiKey sessionid 
    /// - name: sessionIdCookieAuth
    /// - API Key:
    /// - type: apiKey X-API-KEY (HEADER)
    /// - name: apiKeyAuth
    /// - API Key:
    /// - type: apiKey sessionid (HEADER)
    /// - name: sessionIdHeaderAuth
    /// - parameter id: (path) Server ID number. 
    /// - returns: AnyPublisher<Server, Error> 
    open func getServerInfo(id: Int) -> AnyPublisher<Server, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                var localVarPath = "/servers/{id}"
                localVarPath = localVarPath.replacingOccurrences(of: "{id}", with: "\(id)")
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "GET"
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<Server, Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 401 {
                        do {
                            let error = try self.decoder.decode(GetAccountInfo401Response.self, from: transportError.data)
                            return GetServerInfoError.code401Error(error)
                        } catch {
                            return error
                        }
                    }
                    return transportError
                }
                .tryMap { response in
                    try self.decoder.decode(Server.self, from: response.data)
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }

    public enum GetServerInvoicesError: Error, CustomStringConvertible {
        // Unauthorized
        case code401Error(GetAccountInfo401Response)

        public var description: String {
            switch self {
            case .code401Error(let object):
                return "GetServerInvoicesError: Unauthorized: \(object)"
            }
        }
    }

    /// Get Server Invoices
    /// - GET /servers/{id}/invoices
    /// - Returns the billing invoices associated with this dedicated server.
    /// - API Key:
    /// - type: apiKey sessionid 
    /// - name: sessionIdCookieAuth
    /// - API Key:
    /// - type: apiKey X-API-KEY (HEADER)
    /// - name: apiKeyAuth
    /// - API Key:
    /// - type: apiKey sessionid (HEADER)
    /// - name: sessionIdHeaderAuth
    /// - parameter id: (path) Server ID number 
    /// - returns: AnyPublisher<ChargeInvoiceRows, Error> 
    open func getServerInvoices(id: Int) -> AnyPublisher<ChargeInvoiceRows, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                var localVarPath = "/servers/{id}/invoices"
                localVarPath = localVarPath.replacingOccurrences(of: "{id}", with: "\(id)")
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "GET"
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<ChargeInvoiceRows, Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 401 {
                        do {
                            let error = try self.decoder.decode(GetAccountInfo401Response.self, from: transportError.data)
                            return GetServerInvoicesError.code401Error(error)
                        } catch {
                            return error
                        }
                    }
                    return transportError
                }
                .tryMap { response in
                    try self.decoder.decode(ChargeInvoiceRows.self, from: response.data)
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }

    public enum GetServerListError: Error, CustomStringConvertible {
        // Unauthorized
        case code401Error(GetAccountInfo401Response)

        public var description: String {
            switch self {
            case .code401Error(let object):
                return "GetServerListError: Unauthorized: \(object)"
            }
        }
    }

    /// List Servers
    /// - GET /servers
    /// - Returns all dedicated server services on the account with their current status and configuration.
    /// - API Key:
    /// - type: apiKey sessionid 
    /// - name: sessionIdCookieAuth
    /// - API Key:
    /// - type: apiKey X-API-KEY (HEADER)
    /// - name: apiKeyAuth
    /// - API Key:
    /// - type: apiKey sessionid (HEADER)
    /// - name: sessionIdHeaderAuth
    /// - returns: AnyPublisher<[ServerRow], Error> 
    open func getServerList() -> AnyPublisher<[ServerRow], Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                let localVarPath = "/servers"
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "GET"
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<[ServerRow], Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 401 {
                        do {
                            let error = try self.decoder.decode(GetAccountInfo401Response.self, from: transportError.data)
                            return GetServerListError.code401Error(error)
                        } catch {
                            return error
                        }
                    }
                    return transportError
                }
                .tryMap { response in
                    try self.decoder.decode([ServerRow].self, from: response.data)
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }

    public enum GetServerReverseDnsError: Error, CustomStringConvertible {
        // Unauthorized
        case code401Error(GetAccountInfo401Response)

        public var description: String {
            switch self {
            case .code401Error(let object):
                return "GetServerReverseDnsError: Unauthorized: \(object)"
            }
        }
    }

    /// Reverse DNS Info
    /// - GET /servers/{id}/reverse_dns
    /// - Returns the current reverse DNS (PTR record) entries for the server's IP addresses.
    /// - API Key:
    /// - type: apiKey sessionid 
    /// - name: sessionIdCookieAuth
    /// - API Key:
    /// - type: apiKey X-API-KEY (HEADER)
    /// - name: apiKeyAuth
    /// - API Key:
    /// - type: apiKey sessionid (HEADER)
    /// - name: sessionIdHeaderAuth
    /// - parameter id: (path) Server ID number 
    /// - returns: AnyPublisher<ReverseDnsEntries, Error> 
    open func getServerReverseDns(id: Int) -> AnyPublisher<ReverseDnsEntries, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                var localVarPath = "/servers/{id}/reverse_dns"
                localVarPath = localVarPath.replacingOccurrences(of: "{id}", with: "\(id)")
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "GET"
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<ReverseDnsEntries, Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 401 {
                        do {
                            let error = try self.decoder.decode(GetAccountInfo401Response.self, from: transportError.data)
                            return GetServerReverseDnsError.code401Error(error)
                        } catch {
                            return error
                        }
                    }
                    return transportError
                }
                .tryMap { response in
                    try self.decoder.decode(ReverseDnsEntries.self, from: response.data)
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }

    public enum GetServersWelcomeEmailError: Error, CustomStringConvertible {
        // Unauthorized
        case code401Error(GetAccountInfo401Response)

        public var description: String {
            switch self {
            case .code401Error(let object):
                return "GetServersWelcomeEmailError: Unauthorized: \(object)"
            }
        }
    }

    /// Resend Server Welcome Email
    /// - GET /servers/{id}/welcome_email
    /// - Resends the welcome email for the order.
    /// - API Key:
    /// - type: apiKey sessionid 
    /// - name: sessionIdCookieAuth
    /// - API Key:
    /// - type: apiKey X-API-KEY (HEADER)
    /// - name: apiKeyAuth
    /// - API Key:
    /// - type: apiKey sessionid (HEADER)
    /// - name: sessionIdHeaderAuth
    /// - parameter id: (path) Server ID number 
    /// - returns: AnyPublisher<SuccessTextResponse, Error> 
    open func getServersWelcomeEmail(id: Int) -> AnyPublisher<SuccessTextResponse, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                var localVarPath = "/servers/{id}/welcome_email"
                localVarPath = localVarPath.replacingOccurrences(of: "{id}", with: "\(id)")
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "GET"
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<SuccessTextResponse, Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 401 {
                        do {
                            let error = try self.decoder.decode(GetAccountInfo401Response.self, from: transportError.data)
                            return GetServersWelcomeEmailError.code401Error(error)
                        } catch {
                            return error
                        }
                    }
                    return transportError
                }
                .tryMap { response in
                    try self.decoder.decode(SuccessTextResponse.self, from: response.data)
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }

    public enum PlaceBuyNowServerError: Error, CustomStringConvertible {
        // Order validation failed.
        case code400Error(ServersBuyNowError)
        // Unauthorized
        case code401Error(GetAccountInfo401Response)

        public var description: String {
            switch self {
            case .code400Error(let object):
                return "PlaceBuyNowServerError: Order validation failed.: \(object)"
            case .code401Error(let object):
                return "PlaceBuyNowServerError: Unauthorized: \(object)"
            }
        }
    }

    /// Place Buy Now Server Order
    /// - POST /servers/order/buy_now_server
    /// - Places an order for a buy-it-now dedicated server. Use `GET /servers/order/buy_now_server` to retrieve available server configurations and their IDs before ordering.
    /// - API Key:
    /// - type: apiKey sessionid 
    /// - name: sessionIdCookieAuth
    /// - API Key:
    /// - type: apiKey X-API-KEY (HEADER)
    /// - name: apiKeyAuth
    /// - API Key:
    /// - type: apiKey sessionid (HEADER)
    /// - name: sessionIdHeaderAuth
    /// - parameter placeBuyNowServerRequest: (body)  (optional)
    /// - returns: AnyPublisher<ServersBuyNowResponse, Error> 
    open func placeBuyNowServer(placeBuyNowServerRequest: PlaceBuyNowServerRequest? = nil) -> AnyPublisher<ServersBuyNowResponse, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                let localVarPath = "/servers/order/buy_now_server"
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "POST"
                request.httpBody = try self.encoder.encode(placeBuyNowServerRequest)
                request.setValue("application/json", forHTTPHeaderField: "Content-Type")
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<ServersBuyNowResponse, Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 400 {
                        do {
                            let error = try self.decoder.decode(ServersBuyNowError.self, from: transportError.data)
                            return PlaceBuyNowServerError.code400Error(error)
                        } catch {
                            return error
                        }
                    }
                    if transportError.statusCode == 401 {
                        do {
                            let error = try self.decoder.decode(GetAccountInfo401Response.self, from: transportError.data)
                            return PlaceBuyNowServerError.code401Error(error)
                        } catch {
                            return error
                        }
                    }
                    return transportError
                }
                .tryMap { response in
                    try self.decoder.decode(ServersBuyNowResponse.self, from: response.data)
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }

    public enum PostServerReverseDnsError: Error, CustomStringConvertible {
        // Unauthorized
        case code401Error(GetAccountInfo401Response)

        public var description: String {
            switch self {
            case .code401Error(let object):
                return "PostServerReverseDnsError: Unauthorized: \(object)"
            }
        }
    }

    /// Update Reverse DNS
    /// - POST /servers/{id}/reverse_dns
    /// - Updates the reverse DNS (PTR record) entries for the server's IP addresses.
    /// - API Key:
    /// - type: apiKey sessionid 
    /// - name: sessionIdCookieAuth
    /// - API Key:
    /// - type: apiKey X-API-KEY (HEADER)
    /// - name: apiKeyAuth
    /// - API Key:
    /// - type: apiKey sessionid (HEADER)
    /// - name: sessionIdHeaderAuth
    /// - parameter id: (path) Server ID number 
    /// - parameter reverseDnsEntries: (body)  
    /// - returns: AnyPublisher<TextResponse, Error> 
    open func postServerReverseDns(id: Int, reverseDnsEntries: ReverseDnsEntries) -> AnyPublisher<TextResponse, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                var localVarPath = "/servers/{id}/reverse_dns"
                localVarPath = localVarPath.replacingOccurrences(of: "{id}", with: "\(id)")
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "POST"
                request.httpBody = try self.encoder.encode(reverseDnsEntries)
                request.setValue("application/json", forHTTPHeaderField: "Content-Type")
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<TextResponse, Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 401 {
                        do {
                            let error = try self.decoder.decode(GetAccountInfo401Response.self, from: transportError.data)
                            return PostServerReverseDnsError.code401Error(error)
                        } catch {
                            return error
                        }
                    }
                    return transportError
                }
                .tryMap { response in
                    try self.decoder.decode(TextResponse.self, from: response.data)
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }

    public enum PutServersError: Error, CustomStringConvertible {
        // Unauthorized
        case code401Error(GetAccountInfo401Response)

        public var description: String {
            switch self {
            case .code401Error(let object):
                return "PutServersError: Unauthorized: \(object)"
            }
        }
    }

    /// Validate Server Order
    /// - PUT /servers/order
    /// - Validates a server order before placing it. Use this to check for errors before committing to a purchase.
    /// - API Key:
    /// - type: apiKey sessionid 
    /// - name: sessionIdCookieAuth
    /// - API Key:
    /// - type: apiKey X-API-KEY (HEADER)
    /// - name: apiKeyAuth
    /// - API Key:
    /// - type: apiKey sessionid (HEADER)
    /// - name: sessionIdHeaderAuth
    /// - returns: AnyPublisher<Void, Error> 
    open func putServers() -> AnyPublisher<Void, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                let localVarPath = "/servers/order"
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "PUT"
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<Void, Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 401 {
                        do {
                            let error = try self.decoder.decode(GetAccountInfo401Response.self, from: transportError.data)
                            return PutServersError.code401Error(error)
                        } catch {
                            return error
                        }
                    }
                    return transportError
                }
                .tryMap { response in
                    return ()
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }

    public enum ServerIpmiLiveGetError: Error, CustomStringConvertible {
        // The specified resource was not found
        case code404Error(GetAccountInfo401Response)

        public var description: String {
            switch self {
            case .code404Error(let object):
                return "ServerIpmiLiveGetError: The specified resource was not found: \(object)"
            }
        }
    }

    /// Server IPMI Live Information
    /// - GET /servers/{id}/ipmi_live
    /// - Returns the current IPMI live connection information for the server.
    /// - API Key:
    /// - type: apiKey sessionid 
    /// - name: sessionIdCookieAuth
    /// - API Key:
    /// - type: apiKey X-API-KEY (HEADER)
    /// - name: apiKeyAuth
    /// - API Key:
    /// - type: apiKey sessionid (HEADER)
    /// - name: sessionIdHeaderAuth
    /// - parameter id: (path) Server ID number 
    /// - returns: AnyPublisher<ServerIpmiLiveInfo, Error> 
    open func serverIpmiLiveGet(id: Int) -> AnyPublisher<ServerIpmiLiveInfo, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                var localVarPath = "/servers/{id}/ipmi_live"
                localVarPath = localVarPath.replacingOccurrences(of: "{id}", with: "\(id)")
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "GET"
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<ServerIpmiLiveInfo, Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 404 {
                        do {
                            let error = try self.decoder.decode(GetAccountInfo401Response.self, from: transportError.data)
                            return ServerIpmiLiveGetError.code404Error(error)
                        } catch {
                            return error
                        }
                    }
                    return transportError
                }
                .tryMap { response in
                    try self.decoder.decode(ServerIpmiLiveInfo.self, from: response.data)
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }

    public enum ServerIpmiLivePostError: Error, CustomStringConvertible {
        // The specified resource was not found
        case code404Error(GetAccountInfo401Response)

        public var description: String {
            switch self {
            case .code404Error(let object):
                return "ServerIpmiLivePostError: The specified resource was not found: \(object)"
            }
        }
    }

    /// Server IPMI Live Setup
    /// - POST /servers/{id}/ipmi_live
    /// - Configures IPMI live access by whitelisting your current IP address for connections to the server's IPMI management interface.
    /// - API Key:
    /// - type: apiKey sessionid 
    /// - name: sessionIdCookieAuth
    /// - API Key:
    /// - type: apiKey X-API-KEY (HEADER)
    /// - name: apiKeyAuth
    /// - API Key:
    /// - type: apiKey sessionid (HEADER)
    /// - name: sessionIdHeaderAuth
    /// - parameter id: (path) Server ID number 
    /// - parameter ip: (form) Your IP Address you wish to connect to the IPMI system from. 
    /// - parameter asset: (form) Asset ID (optional)
    /// - returns: AnyPublisher<ServerIpmiLiveInfo, Error> 
    open func serverIpmiLivePost(id: Int, ip: String, asset: Int? = nil) -> AnyPublisher<ServerIpmiLiveInfo, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                var localVarPath = "/servers/{id}/ipmi_live"
                localVarPath = localVarPath.replacingOccurrences(of: "{id}", with: "\(id)")
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "POST"
                let multipartBoundary = String(format: "Boundary+%08X%08X", arc4random(), arc4random())
                var multipartData = Data()
				if let asset = asset {
					let assetHeader = "--\(multipartBoundary)\r\n"
					    .appending("Content-Disposition:form-data; name=\"asset\"\r\n")
					    .appending("\r\n")
					multipartData.append(assetHeader.data(using: .utf8) ?? Data())
					multipartData.append()
					multipartData.append("\r\n".data(using: .utf8) ?? Data())
				}

				let ipHeader = "--\(multipartBoundary)\r\n"
				    .appending("Content-Disposition:form-data; name=\"ip\"\r\n")
				    .appending("\r\n")
				multipartData.append(ipHeader.data(using: .utf8) ?? Data())
				multipartData.append(ip.data(using: .utf8) ?? Data())

                multipartData.append("\r\n--\(multipartBoundary)--\r\n".data(using: .utf8) ?? Data())
                request.httpBody = multipartData
                request.setValue("\(multipartData.count)", forHTTPHeaderField: "Content-Length")
                request.setValue("multipart/form-data; boundary=\(multipartBoundary)", forHTTPHeaderField: "Content-Type")
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<ServerIpmiLiveInfo, Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 404 {
                        do {
                            let error = try self.decoder.decode(GetAccountInfo401Response.self, from: transportError.data)
                            return ServerIpmiLivePostError.code404Error(error)
                        } catch {
                            return error
                        }
                    }
                    return transportError
                }
                .tryMap { response in
                    try self.decoder.decode(ServerIpmiLiveInfo.self, from: response.data)
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }

    public enum ServerIpmiPowerGetError: Error, CustomStringConvertible {
        // Unauthorized
        case code401Error(GetAccountInfo401Response)

        public var description: String {
            switch self {
            case .code401Error(let object):
                return "ServerIpmiPowerGetError: Unauthorized: \(object)"
            }
        }
    }

    /// Get IPMI Power Status
    /// - GET /servers/{id}/ipmi_power
    /// - Returns the chassis power status from ipmi.
    /// - API Key:
    /// - type: apiKey sessionid 
    /// - name: sessionIdCookieAuth
    /// - API Key:
    /// - type: apiKey X-API-KEY (HEADER)
    /// - name: apiKeyAuth
    /// - API Key:
    /// - type: apiKey sessionid (HEADER)
    /// - name: sessionIdHeaderAuth
    /// - parameter id: (path) Server ID number 
    /// - returns: AnyPublisher<TextResponse, Error> 
    open func serverIpmiPowerGet(id: Int) -> AnyPublisher<TextResponse, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                var localVarPath = "/servers/{id}/ipmi_power"
                localVarPath = localVarPath.replacingOccurrences(of: "{id}", with: "\(id)")
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "GET"
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<TextResponse, Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 401 {
                        do {
                            let error = try self.decoder.decode(GetAccountInfo401Response.self, from: transportError.data)
                            return ServerIpmiPowerGetError.code401Error(error)
                        } catch {
                            return error
                        }
                    }
                    return transportError
                }
                .tryMap { response in
                    try self.decoder.decode(TextResponse.self, from: response.data)
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }

    ///
    /// Enum for parameter action
    ///
    public enum ServerIpmiPowerPostAction: String, Codable, CaseIterable {
        case cycle = "cycle"
        case reset = "reset"
        case on = "on"
        case off = "off"
        case soft = "soft"
    }
    public enum ServerIpmiPowerPostError: Error, CustomStringConvertible {
        // The specified resource was not found
        case code400Error(GetAccountInfo401Response)

        public var description: String {
            switch self {
            case .code400Error(let object):
                return "ServerIpmiPowerPostError: The specified resource was not found: \(object)"
            }
        }
    }

    /// Server IPMI Power
    /// - POST /servers/{id}/ipmi_power
    /// - Uses the IPMI interface to set the Power status on the server.
    /// - API Key:
    /// - type: apiKey sessionid 
    /// - name: sessionIdCookieAuth
    /// - API Key:
    /// - type: apiKey X-API-KEY (HEADER)
    /// - name: apiKeyAuth
    /// - API Key:
    /// - type: apiKey sessionid (HEADER)
    /// - name: sessionIdHeaderAuth
    /// - parameter id: (path) Server ID number 
    /// - parameter action: (form) The power action to send to the ipmi controller. 
    /// - parameter asset: (form) The Asset ID (optional)
    /// - returns: AnyPublisher<TextResponse, Error> 
    open func serverIpmiPowerPost(id: Int, action: ServerIpmiPowerPostAction, asset: Int? = nil) -> AnyPublisher<TextResponse, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                var localVarPath = "/servers/{id}/ipmi_power"
                localVarPath = localVarPath.replacingOccurrences(of: "{id}", with: "\(id)")
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "POST"
                let multipartBoundary = String(format: "Boundary+%08X%08X", arc4random(), arc4random())
                var multipartData = Data()
				if let asset = asset {
					let assetHeader = "--\(multipartBoundary)\r\n"
					    .appending("Content-Disposition:form-data; name=\"asset\"\r\n")
					    .appending("\r\n")
					multipartData.append(assetHeader.data(using: .utf8) ?? Data())
					multipartData.append()
					multipartData.append("\r\n".data(using: .utf8) ?? Data())
				}

				let actionHeader = "--\(multipartBoundary)\r\n"
				    .appending("Content-Disposition:form-data; name=\"action\"\r\n")
				    .appending("\r\n")
				multipartData.append(actionHeader.data(using: .utf8) ?? Data())
				multipartData.append(action.rawValue.data(using: .utf8) ?? Data())

                multipartData.append("\r\n--\(multipartBoundary)--\r\n".data(using: .utf8) ?? Data())
                request.httpBody = multipartData
                request.setValue("\(multipartData.count)", forHTTPHeaderField: "Content-Length")
                request.setValue("multipart/form-data; boundary=\(multipartBoundary)", forHTTPHeaderField: "Content-Type")
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<TextResponse, Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 400 {
                        do {
                            let error = try self.decoder.decode(GetAccountInfo401Response.self, from: transportError.data)
                            return ServerIpmiPowerPostError.code400Error(error)
                        } catch {
                            return error
                        }
                    }
                    return transportError
                }
                .tryMap { response in
                    try self.decoder.decode(TextResponse.self, from: response.data)
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }

    public enum ServersCancelError: Error, CustomStringConvertible {
        // Unauthorized
        case code401Error(GetAccountInfo401Response)

        public var description: String {
            switch self {
            case .code401Error(let object):
                return "ServersCancelError: Unauthorized: \(object)"
            }
        }
    }

    /// Cancel Server Service
    /// - DELETE /servers/{id}
    /// - Cancels the dedicated server service. The server will be deprovisioned and billing will stop at the end of the current billing cycle.
    /// - API Key:
    /// - type: apiKey sessionid 
    /// - name: sessionIdCookieAuth
    /// - API Key:
    /// - type: apiKey X-API-KEY (HEADER)
    /// - name: apiKeyAuth
    /// - API Key:
    /// - type: apiKey sessionid (HEADER)
    /// - name: sessionIdHeaderAuth
    /// - parameter id: (path) Server ID number 
    /// - returns: AnyPublisher<ServersCancel200Response, Error> 
    open func serversCancel(id: Int) -> AnyPublisher<ServersCancel200Response, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                var localVarPath = "/servers/{id}"
                localVarPath = localVarPath.replacingOccurrences(of: "{id}", with: "\(id)")
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "DELETE"
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<ServersCancel200Response, Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 401 {
                        do {
                            let error = try self.decoder.decode(GetAccountInfo401Response.self, from: transportError.data)
                            return ServersCancelError.code401Error(error)
                        } catch {
                            return error
                        }
                    }
                    return transportError
                }
                .tryMap { response in
                    try self.decoder.decode(ServersCancel200Response.self, from: response.data)
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }

    public enum UpdateServerInfoError: Error, CustomStringConvertible {
        // Unauthorized
        case code401Error(GetAccountInfo401Response)

        public var description: String {
            switch self {
            case .code401Error(let object):
                return "UpdateServerInfoError: Unauthorized: \(object)"
            }
        }
    }

    /// Update Server Order
    /// - POST /servers/{id}
    /// - Updates settings on a dedicated server order.
    /// - API Key:
    /// - type: apiKey sessionid 
    /// - name: sessionIdCookieAuth
    /// - API Key:
    /// - type: apiKey X-API-KEY (HEADER)
    /// - name: apiKeyAuth
    /// - API Key:
    /// - type: apiKey sessionid (HEADER)
    /// - name: sessionIdHeaderAuth
    /// - parameter id: (path) Server ID number. 
    /// - returns: AnyPublisher<Void, Error> 
    open func updateServerInfo(id: String) -> AnyPublisher<Void, Error> {
        Deferred {
            Result<URLRequest, Error> {
                guard let baseURL = self.transport.baseURL ?? self.baseURL else {
                    throw OpenAPITransportError.badURLError()
                }
                var localVarPath = "/servers/{id}"
                localVarPath = localVarPath.replacingOccurrences(of: "{id}", with: id)
                let localVarURL = baseURL.appendingPathComponent(localVarPath)
                let components = URLComponents(url: localVarURL, resolvingAgainstBaseURL: false)
                guard let requestURL = components?.url else {
                    throw OpenAPITransportError.badURLError()
                }
                var request = URLRequest(url: requestURL)
                request.httpMethod = "POST"
                return request
            }.publisher
        }.flatMap { request -> AnyPublisher<Void, Error> in 
            return self.transport.send(request: request)
                .mapError { transportError -> Error in 
                    if transportError.statusCode == 401 {
                        do {
                            let error = try self.decoder.decode(GetAccountInfo401Response.self, from: transportError.data)
                            return UpdateServerInfoError.code401Error(error)
                        } catch {
                            return error
                        }
                    }
                    return transportError
                }
                .tryMap { response in
                    return ()
                }
                .eraseToAnyPublisher()
        }.eraseToAnyPublisher()
    }
}
