/** InterServer Management API
  * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
  *
  * The version of the OpenAPI document: 0.9.0
  * Contact: support@interserver.net
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
package org.openapitools.client.apis

import cats.effect.Concurrent
import io.circe.Encoder
import org.http4s.Uri
import org.http4s.client.Client as Http4sClient
import org.openapitools.client.models.ChargeInvoiceRows
import org.openapitools.client.models.DeliveredStatus
import org.openapitools.client.models.DenyRuleNew
import org.openapitools.client.models.DenyRuleRecord
import org.openapitools.client.models.GenericResponse
import org.openapitools.client.models.GetAccountInfo401Response
import org.openapitools.client.models.GetStatsTimeParameter
import org.openapitools.client.models.MailAlertRequest
import org.openapitools.client.models.MailAlertUpdateRequest
import org.openapitools.client.models.MailAlertsResponse
import org.openapitools.client.models.MailBlocks
import org.openapitools.client.models.MailCancel200Response
import org.openapitools.client.models.MailDelistRequest
import org.openapitools.client.models.MailDelistResponse
import org.openapitools.client.models.MailDeliverabilityResponse
import org.openapitools.client.models.MailLog
import org.openapitools.client.models.MailOrder
import org.openapitools.client.models.MailRow
import org.openapitools.client.models.MailSchema
import org.openapitools.client.models.MailStatsType
import org.openapitools.client.models.SendMail
import org.openapitools.client.models.SendMailAdv
import scala.collection.immutable.Seq
import org.openapitools.client.models.ServiceOrderPostResponse
import org.openapitools.client.models.SuccessTextResponse
import org.openapitools.client.models.ViewMailLogDirParameter
import org.openapitools.client.models.ViewMailLogGroupbyParameter
import org.openapitools.client.models.ViewMailLogSortParameter
import org.openapitools.client.models.ViewMailLogStartDateParameter
import org.openapitools.client.models.*

trait MailApiEndpoints[F[*]] {

  def addMail()(using auth: _Authorization.ApiKey): F[ServiceOrderPostResponse]
  def addRule(id: Int, denyRuleNew: DenyRuleNew)(using auth: _Authorization.ApiKey): F[GenericResponse]
  def createMailAlert(id: Int, mailAlertRequest: MailAlertRequest)(using auth: _Authorization.ApiKey): F[SuccessTextResponse]
  def deleteMailAlert(id: Int, alertId: Int)(using auth: _Authorization.ApiKey): F[SuccessTextResponse]
  def deleteRule(id: Int, rule: String)(using auth: _Authorization.ApiKey): F[GenericResponse]
  def delistBlock(id: Int, email: Option[String] = None)(using auth: _Authorization.ApiKey): F[GenericResponse]
  def getMailAlerts(id: Int)(using auth: _Authorization.ApiKey): F[MailAlertsResponse]
  def getMailBlocks(id: Int)(using auth: _Authorization.ApiKey): F[MailBlocks]
  def getMailDelist(id: Int)(using auth: _Authorization.ApiKey): F[MailDelistResponse]
  def getMailDeliverability(id: Int)(using auth: _Authorization.ApiKey): F[MailDeliverabilityResponse]
  def getMailInfo(id: Int)(using auth: _Authorization.ApiKey): F[MailSchema]
  def getMailInvoices(id: Int)(using auth: _Authorization.ApiKey): F[ChargeInvoiceRows]
  def getMailList()(using auth: _Authorization.ApiKey): F[Seq[MailRow]]
  def getMailWelcomeEmail(id: Int)(using auth: _Authorization.ApiKey): F[SuccessTextResponse]
  def getNewMail()(using auth: _Authorization.ApiKey): F[MailOrder]
  def getRules(id: Int)(using auth: _Authorization.ApiKey): F[Seq[DenyRuleRecord]]
  def getStats(id: Int, time: Option[GetStatsTimeParameter] = None)(using auth: _Authorization.ApiKey): F[MailStatsType]
  def mailCancel(id: Int)(using auth: _Authorization.ApiKey): F[MailCancel200Response]
  def postMailDelist(id: Int, mailDelistRequest: MailDelistRequest)(using auth: _Authorization.ApiKey): F[SuccessTextResponse]
  def putMail()(using auth: _Authorization.ApiKey): F[Unit]
  def resetMailPassword(id: Int)(using auth: _Authorization.ApiKey): F[SuccessTextResponse]
  def sendAdvMail(id: Int, sendMailAdv: SendMailAdv)(using auth: _Authorization.ApiKey): F[GenericResponse]
  def sendMail(id: Int, sendMail: SendMail)(using auth: _Authorization.ApiKey): F[GenericResponse]
  def updateMailAlert(id: Int, mailAlertUpdateRequest: MailAlertUpdateRequest)(using auth: _Authorization.ApiKey): F[SuccessTextResponse]
  def updateMailInfo(id: String)(using auth: _Authorization.ApiKey): F[SuccessTextResponse]
  def viewMailLog(id: Int, id2: Option[Long] = None, origin: Option[String] = None, mx: Option[String] = None, from: Option[String] = None, to: Option[String] = None, subject: Option[String] = None, mailid: Option[String] = None, messageId: Option[String] = None, replyto: Option[String] = None, headerfrom: Option[String] = None, delivered: Option[DeliveredStatus] = None, skip: Option[Int] = None, limit: Option[Int] = None, startDate: Option[ViewMailLogStartDateParameter] = None, endDate: Option[ViewMailLogStartDateParameter] = None, sort: Option[ViewMailLogSortParameter] = None, dir: Option[ViewMailLogDirParameter] = None, groupby: Option[ViewMailLogGroupbyParameter] = None)(using auth: _Authorization.ApiKey): F[MailLog]

}

class MailApiEndpointsImpl[F[*]: Concurrent](
  override val baseUrl: Uri,
  defaultHeaders: Seq[(String, String)] = Nil,
  httpClient: Http4sClient[F]
) extends BaseClient[F](baseUrl, defaultHeaders, httpClient) with MailApiEndpoints[F] {
  
  import JsonSupports.*
  import io.circe.syntax.EncoderOps
  import cats.implicits.toFlatMapOps

  override def addMail()(using auth: _Authorization.ApiKey): F[ServiceOrderPostResponse] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten

    _executeRequest[Unit, ServiceOrderPostResponse](
      method = "POST",
      path = s"/mail/order",
      body = None,
      formParameters = None,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, ServiceOrderPostResponse]("ServiceOrderPostResponse", r)
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def addRule(id: Int, denyRuleNew: DenyRuleNew)(using auth: _Authorization.ApiKey): F[GenericResponse] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten

    _executeRequest[DenyRuleNew, GenericResponse](
      method = "POST",
      path = s"/mail/${id}/rules",
      body = Some(denyRuleNew),
      formParameters = None,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, GenericResponse]("GenericResponse", r)
        case r if r.status.code == 400 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
        case r if r.status.code == 404 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def createMailAlert(id: Int, mailAlertRequest: MailAlertRequest)(using auth: _Authorization.ApiKey): F[SuccessTextResponse] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten

    _executeRequest[MailAlertRequest, SuccessTextResponse](
      method = "POST",
      path = s"/mail/${id}/alerts",
      body = Some(mailAlertRequest),
      formParameters = None,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, SuccessTextResponse]("SuccessTextResponse", r)
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def deleteMailAlert(id: Int, alertId: Int)(using auth: _Authorization.ApiKey): F[SuccessTextResponse] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten
    val queryParameters = (
      Some(Seq("alert_id" -> alertId))
    ).toSeq.flatten

    _executeRequest[Unit, SuccessTextResponse](
      method = "DELETE",
      path = s"/mail/${id}/alerts",
      body = None,
      formParameters = None,
      queryParameters = queryParameters,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, SuccessTextResponse]("SuccessTextResponse", r)
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def deleteRule(id: Int, rule: String)(using auth: _Authorization.ApiKey): F[GenericResponse] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten

    _executeRequest[Unit, GenericResponse](
      method = "DELETE",
      path = s"/mail/${id}/rules/${rule}",
      body = None,
      formParameters = None,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, GenericResponse]("GenericResponse", r)
        case r if r.status.code == 400 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
        case r if r.status.code == 404 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def delistBlock(id: Int, email: Option[String] = None)(using auth: _Authorization.ApiKey): F[GenericResponse] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "multipart/form-data")
    ).flatten
    val formParameters = Some((
      email.map("email" -> _).map(Seq(_))
    ).toSeq.flatten)

    _executeRequest[Unit, GenericResponse](
      method = "POST",
      path = s"/mail/${id}/blocks/delete",
      body = None,
      formParameters = formParameters,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, GenericResponse]("GenericResponse", r)
        case r if r.status.code == 400 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
        case r if r.status.code == 404 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def getMailAlerts(id: Int)(using auth: _Authorization.ApiKey): F[MailAlertsResponse] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten

    _executeRequest[Unit, MailAlertsResponse](
      method = "GET",
      path = s"/mail/${id}/alerts",
      body = None,
      formParameters = None,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, MailAlertsResponse]("MailAlertsResponse", r)
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def getMailBlocks(id: Int)(using auth: _Authorization.ApiKey): F[MailBlocks] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten

    _executeRequest[Unit, MailBlocks](
      method = "GET",
      path = s"/mail/${id}/blocks",
      body = None,
      formParameters = None,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, MailBlocks]("MailBlocks", r)
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
        case r if r.status.code == 404 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def getMailDelist(id: Int)(using auth: _Authorization.ApiKey): F[MailDelistResponse] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten

    _executeRequest[Unit, MailDelistResponse](
      method = "GET",
      path = s"/mail/${id}/delist",
      body = None,
      formParameters = None,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, MailDelistResponse]("MailDelistResponse", r)
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def getMailDeliverability(id: Int)(using auth: _Authorization.ApiKey): F[MailDeliverabilityResponse] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten

    _executeRequest[Unit, MailDeliverabilityResponse](
      method = "GET",
      path = s"/mail/${id}/deliverability",
      body = None,
      formParameters = None,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, MailDeliverabilityResponse]("MailDeliverabilityResponse", r)
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def getMailInfo(id: Int)(using auth: _Authorization.ApiKey): F[MailSchema] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten

    _executeRequest[Unit, MailSchema](
      method = "GET",
      path = s"/mail/${id}",
      body = None,
      formParameters = None,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, MailSchema]("MailSchema", r)
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def getMailInvoices(id: Int)(using auth: _Authorization.ApiKey): F[ChargeInvoiceRows] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten

    _executeRequest[Unit, ChargeInvoiceRows](
      method = "GET",
      path = s"/mail/${id}/invoices",
      body = None,
      formParameters = None,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, ChargeInvoiceRows]("ChargeInvoiceRows", r)
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def getMailList()(using auth: _Authorization.ApiKey): F[Seq[MailRow]] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten

    _executeRequest[Unit, Seq[MailRow]](
      method = "GET",
      path = s"/mail",
      body = None,
      formParameters = None,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, Seq[MailRow]]("Seq[MailRow]", r)
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def getMailWelcomeEmail(id: Int)(using auth: _Authorization.ApiKey): F[SuccessTextResponse] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten

    _executeRequest[Unit, SuccessTextResponse](
      method = "GET",
      path = s"/mail/${id}/welcome_email",
      body = None,
      formParameters = None,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, SuccessTextResponse]("SuccessTextResponse", r)
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def getNewMail()(using auth: _Authorization.ApiKey): F[MailOrder] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten

    _executeRequest[Unit, MailOrder](
      method = "GET",
      path = s"/mail/order",
      body = None,
      formParameters = None,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, MailOrder]("MailOrder", r)
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def getRules(id: Int)(using auth: _Authorization.ApiKey): F[Seq[DenyRuleRecord]] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten

    _executeRequest[Unit, Seq[DenyRuleRecord]](
      method = "GET",
      path = s"/mail/${id}/rules",
      body = None,
      formParameters = None,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, Seq[DenyRuleRecord]]("Seq[DenyRuleRecord]", r)
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
        case r if r.status.code == 404 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def getStats(id: Int, time: Option[GetStatsTimeParameter] = None)(using auth: _Authorization.ApiKey): F[MailStatsType] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten
    val queryParameters = (
      time.map("time" -> _).map(Seq(_))
    ).toSeq.flatten

    _executeRequest[Unit, MailStatsType](
      method = "GET",
      path = s"/mail/${id}/stats",
      body = None,
      formParameters = None,
      queryParameters = queryParameters,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, MailStatsType]("MailStatsType", r)
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
        case r if r.status.code == 404 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def mailCancel(id: Int)(using auth: _Authorization.ApiKey): F[MailCancel200Response] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten

    _executeRequest[Unit, MailCancel200Response](
      method = "DELETE",
      path = s"/mail/${id}",
      body = None,
      formParameters = None,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, MailCancel200Response]("MailCancel200Response", r)
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def postMailDelist(id: Int, mailDelistRequest: MailDelistRequest)(using auth: _Authorization.ApiKey): F[SuccessTextResponse] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten

    _executeRequest[MailDelistRequest, SuccessTextResponse](
      method = "POST",
      path = s"/mail/${id}/delist",
      body = Some(mailDelistRequest),
      formParameters = None,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, SuccessTextResponse]("SuccessTextResponse", r)
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def putMail()(using auth: _Authorization.ApiKey): F[Unit] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten

    _executeRequest[Unit, Unit](
      method = "PUT",
      path = s"/mail/order",
      body = None,
      formParameters = None,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => Concurrent[F].pure(())
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def resetMailPassword(id: Int)(using auth: _Authorization.ApiKey): F[SuccessTextResponse] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten

    _executeRequest[Unit, SuccessTextResponse](
      method = "GET",
      path = s"/mail/${id}/reset_password",
      body = None,
      formParameters = None,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, SuccessTextResponse]("SuccessTextResponse", r)
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def sendAdvMail(id: Int, sendMailAdv: SendMailAdv)(using auth: _Authorization.ApiKey): F[GenericResponse] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten

    _executeRequest[SendMailAdv, GenericResponse](
      method = "POST",
      path = s"/mail/${id}/advsend",
      body = Some(sendMailAdv),
      formParameters = None,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, GenericResponse]("GenericResponse", r)
        case r if r.status.code == 400 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
        case r if r.status.code == 404 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def sendMail(id: Int, sendMail: SendMail)(using auth: _Authorization.ApiKey): F[GenericResponse] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten

    _executeRequest[SendMail, GenericResponse](
      method = "POST",
      path = s"/mail/${id}/send",
      body = Some(sendMail),
      formParameters = None,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, GenericResponse]("GenericResponse", r)
        case r if r.status.code == 400 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
        case r if r.status.code == 404 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def updateMailAlert(id: Int, mailAlertUpdateRequest: MailAlertUpdateRequest)(using auth: _Authorization.ApiKey): F[SuccessTextResponse] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten

    _executeRequest[MailAlertUpdateRequest, SuccessTextResponse](
      method = "PUT",
      path = s"/mail/${id}/alerts",
      body = Some(mailAlertUpdateRequest),
      formParameters = None,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, SuccessTextResponse]("SuccessTextResponse", r)
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def updateMailInfo(id: String)(using auth: _Authorization.ApiKey): F[SuccessTextResponse] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten

    _executeRequest[Unit, SuccessTextResponse](
      method = "POST",
      path = s"/mail/${id}",
      body = None,
      formParameters = None,
      queryParameters = Nil,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, SuccessTextResponse]("SuccessTextResponse", r)
        case r if r.status.code == 401 => parseJson[F, GetAccountInfo401Response]("GetAccountInfo401Response", r).flatMap(res => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason, Some(res.asJson))))
    }
  }

  override def viewMailLog(id: Int, id2: Option[Long] = None, origin: Option[String] = None, mx: Option[String] = None, from: Option[String] = None, to: Option[String] = None, subject: Option[String] = None, mailid: Option[String] = None, messageId: Option[String] = None, replyto: Option[String] = None, headerfrom: Option[String] = None, delivered: Option[DeliveredStatus] = None, skip: Option[Int] = None, limit: Option[Int] = None, startDate: Option[ViewMailLogStartDateParameter] = None, endDate: Option[ViewMailLogStartDateParameter] = None, sort: Option[ViewMailLogSortParameter] = None, dir: Option[ViewMailLogDirParameter] = None, groupby: Option[ViewMailLogGroupbyParameter] = None)(using auth: _Authorization.ApiKey): F[MailLog] = {
    val requestHeaders = Seq(
      Some("Content-Type" -> "application/json")
    ).flatten
    val queryParameters = (
      id2.map("id" -> _).map(Seq(_)) ++ 
      origin.map("origin" -> _).map(Seq(_)) ++ 
      mx.map("mx" -> _).map(Seq(_)) ++ 
      from.map("from" -> _).map(Seq(_)) ++ 
      to.map("to" -> _).map(Seq(_)) ++ 
      subject.map("subject" -> _).map(Seq(_)) ++ 
      mailid.map("mailid" -> _).map(Seq(_)) ++ 
      messageId.map("messageId" -> _).map(Seq(_)) ++ 
      replyto.map("replyto" -> _).map(Seq(_)) ++ 
      headerfrom.map("headerfrom" -> _).map(Seq(_)) ++ 
      delivered.map("delivered" -> _).map(Seq(_)) ++ 
      skip.map("skip" -> _).map(Seq(_)) ++ 
      limit.map("limit" -> _).map(Seq(_)) ++ 
      startDate.map("startDate" -> _).map(Seq(_)) ++ 
      endDate.map("endDate" -> _).map(Seq(_)) ++ 
      sort.map("sort" -> _).map(Seq(_)) ++ 
      dir.map("dir" -> _).map(Seq(_)) ++ 
      groupby.map("groupby" -> _).map(Seq(_))
    ).toSeq.flatten

    _executeRequest[Unit, MailLog](
      method = "GET",
      path = s"/mail/${id}/log",
      body = None,
      formParameters = None,
      queryParameters = queryParameters,
      requestHeaders = requestHeaders,
      auth = Some(auth)) {
        
        case r if r.status.code == 200 => parseJson[F, MailLog]("MailLog", r)
        case r if r.status.code == 400 => Concurrent[F].raiseError(_FailedRequest(r.status.code, r.status.reason))
    }
  }

}


