/**
 * InterServer Management API
 * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
 *
 * OpenAPI spec version: 0.9.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIDNSApiOperations.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Dom/JsonObject.h"
#include "Templates/SharedPointer.h"
#include "HttpModule.h"
#include "PlatformHttp.h"

namespace OpenAPI
{

FString OpenAPIDNSApi::AddDnsDomainRequest::ComputePath() const
{
	FString Path(TEXT("/dns"));
	return Path;
}

void OpenAPIDNSApi::AddDnsDomainRequest::SetupHttpRequest(const FHttpRequestRef& HttpRequest) const
{
	static const TArray<FString> Consumes = { TEXT("multipart/form-data"), TEXT("application/json") };
	//static const TArray<FString> Produces = { TEXT("application/json") };

	HttpRequest->SetVerb(TEXT("POST"));

	// Default to Json Body request
	if (Consumes.Num() == 0 || Consumes.Contains(TEXT("application/json")))
	{
		// Form parameters added to try to generate a json body when no body parameters are specified.
		FString JsonBody;
		JsonWriter Writer = TJsonWriterFactory<>::Create(&JsonBody);
		Writer->WriteObjectStart();
		Writer->WriteIdentifierPrefix(TEXT("domain"));
		WriteJsonValue(Writer, Domain);
		Writer->WriteIdentifierPrefix(TEXT("ip"));
		WriteJsonValue(Writer, Ip);
		Writer->WriteObjectEnd();
		Writer->Close();
		HttpRequest->SetHeader(TEXT("Content-Type"), TEXT("application/json; charset=utf-8"));
		HttpRequest->SetContentAsString(JsonBody);
	}
	else if (Consumes.Contains(TEXT("multipart/form-data")))
	{
		HttpMultipartFormData FormData;
		FormData.AddStringPart(TEXT("domain"), *ToUrlString(Domain));
		FormData.AddStringPart(TEXT("ip"), *ToUrlString(Ip));

		FormData.SetupHttpRequest(HttpRequest);
	}
	else if (Consumes.Contains(TEXT("application/x-www-form-urlencoded")))
	{
		TArray<FString> FormParams;
		FormParams.Add(FString(TEXT("domain=")) + ToUrlString(Domain));
		FormParams.Add(FString(TEXT("ip=")) + ToUrlString(Ip));

		HttpRequest->SetHeader(TEXT("Content-Type"), TEXT("application/x-www-form-urlencoded; charset=utf-8"));
		HttpRequest->SetContentAsString(FString::Join(FormParams, TEXT("&")));
	}
	else
	{
		UE_LOG(LogOpenAPI, Error, TEXT("Request ContentType not supported (%s)"), *FString::Join(Consumes, TEXT(",")));
	}
}

void OpenAPIDNSApi::AddDnsDomainResponse::SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode)
{
	Response::SetHttpResponseCode(InHttpResponseCode);
	switch ((int)InHttpResponseCode)
	{
	case 401:
		SetResponseString(TEXT("Unauthorized"));
		break;
	case 0:
	default:
		SetResponseString(TEXT("Default response"));
		break;
	}
}

bool OpenAPIDNSApi::AddDnsDomainResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return true;
}

FString OpenAPIDNSApi::AddDnsRecordRequest::ComputePath() const
{
	TMap<FString, FStringFormatArg> PathParams = { 
	{ TEXT("id"), FStringFormatArg(ToUrlString(Id)) } };

	FString Path = FString::Format(TEXT("/dns/{id}"), PathParams);

	return Path;
}

void OpenAPIDNSApi::AddDnsRecordRequest::SetupHttpRequest(const FHttpRequestRef& HttpRequest) const
{
	static const TArray<FString> Consumes = { TEXT("multipart/form-data"), TEXT("application/json") };
	//static const TArray<FString> Produces = { TEXT("application/json") };

	HttpRequest->SetVerb(TEXT("POST"));

	// Default to Json Body request
	if (Consumes.Num() == 0 || Consumes.Contains(TEXT("application/json")))
	{
		// Form parameters added to try to generate a json body when no body parameters are specified.
		FString JsonBody;
		JsonWriter Writer = TJsonWriterFactory<>::Create(&JsonBody);
		Writer->WriteObjectStart();
		Writer->WriteIdentifierPrefix(TEXT("name"));
		WriteJsonValue(Writer, Name);
		Writer->WriteIdentifierPrefix(TEXT("type"));
		WriteJsonValue(Writer, Type);
		Writer->WriteIdentifierPrefix(TEXT("content"));
		WriteJsonValue(Writer, Content);
		if (Ttl.IsSet()){
			Writer->WriteIdentifierPrefix(TEXT("ttl"));
			WriteJsonValue(Writer, Ttl.GetValue());
		}
		if (Prio.IsSet()){
			Writer->WriteIdentifierPrefix(TEXT("prio"));
			WriteJsonValue(Writer, Prio.GetValue());
		}
		Writer->WriteObjectEnd();
		Writer->Close();
		HttpRequest->SetHeader(TEXT("Content-Type"), TEXT("application/json; charset=utf-8"));
		HttpRequest->SetContentAsString(JsonBody);
	}
	else if (Consumes.Contains(TEXT("multipart/form-data")))
	{
		HttpMultipartFormData FormData;
		FormData.AddStringPart(TEXT("name"), *ToUrlString(Name));
		FormData.AddStringPart(TEXT("type"), *ToUrlString(Type));
		FormData.AddStringPart(TEXT("content"), *ToUrlString(Content));
		if(Ttl.IsSet())
		{
			FormData.AddStringPart(TEXT("ttl"), *ToUrlString(Ttl.GetValue()));
		}
		if(Prio.IsSet())
		{
			FormData.AddStringPart(TEXT("prio"), *ToUrlString(Prio.GetValue()));
		}

		FormData.SetupHttpRequest(HttpRequest);
	}
	else if (Consumes.Contains(TEXT("application/x-www-form-urlencoded")))
	{
		TArray<FString> FormParams;
		FormParams.Add(FString(TEXT("name=")) + ToUrlString(Name));
		FormParams.Add(FString(TEXT("type=")) + ToUrlString(Type));
		FormParams.Add(FString(TEXT("content=")) + ToUrlString(Content));
		if(Ttl.IsSet())
		{
			FormParams.Add(FString(TEXT("ttl=")) + ToUrlString(Ttl.GetValue()));
		}
		if(Prio.IsSet())
		{
			FormParams.Add(FString(TEXT("prio=")) + ToUrlString(Prio.GetValue()));
		}

		HttpRequest->SetHeader(TEXT("Content-Type"), TEXT("application/x-www-form-urlencoded; charset=utf-8"));
		HttpRequest->SetContentAsString(FString::Join(FormParams, TEXT("&")));
	}
	else
	{
		UE_LOG(LogOpenAPI, Error, TEXT("Request ContentType not supported (%s)"), *FString::Join(Consumes, TEXT(",")));
	}
}

void OpenAPIDNSApi::AddDnsRecordResponse::SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode)
{
	Response::SetHttpResponseCode(InHttpResponseCode);
	switch ((int)InHttpResponseCode)
	{
	case 200:
		SetResponseString(TEXT("Add DNS Domain Response"));
		break;
	case 401:
		SetResponseString(TEXT("Unauthorized"));
		break;
	}
}

bool OpenAPIDNSApi::AddDnsRecordResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return true;
}

FString OpenAPIDNSApi::DeleteDnsDomainRequest::ComputePath() const
{
	TMap<FString, FStringFormatArg> PathParams = { 
	{ TEXT("id"), FStringFormatArg(ToUrlString(Id)) } };

	FString Path = FString::Format(TEXT("/dns/{id}"), PathParams);

	return Path;
}

void OpenAPIDNSApi::DeleteDnsDomainRequest::SetupHttpRequest(const FHttpRequestRef& HttpRequest) const
{
	static const TArray<FString> Consumes = {  };
	//static const TArray<FString> Produces = { TEXT("application/json") };

	HttpRequest->SetVerb(TEXT("DELETE"));

}

void OpenAPIDNSApi::DeleteDnsDomainResponse::SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode)
{
	Response::SetHttpResponseCode(InHttpResponseCode);
	switch ((int)InHttpResponseCode)
	{
	case 401:
		SetResponseString(TEXT("Unauthorized"));
		break;
	case 0:
	default:
		SetResponseString(TEXT("Default response"));
		break;
	}
}

bool OpenAPIDNSApi::DeleteDnsDomainResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return true;
}

FString OpenAPIDNSApi::DeleteDnsRecordRequest::ComputePath() const
{
	TMap<FString, FStringFormatArg> PathParams = { 
	{ TEXT("domainId"), FStringFormatArg(ToUrlString(DomainId)) },
	{ TEXT("recordId"), FStringFormatArg(ToUrlString(RecordId)) } };

	FString Path = FString::Format(TEXT("/dns/{domainId}/{recordId}"), PathParams);

	return Path;
}

void OpenAPIDNSApi::DeleteDnsRecordRequest::SetupHttpRequest(const FHttpRequestRef& HttpRequest) const
{
	static const TArray<FString> Consumes = {  };
	//static const TArray<FString> Produces = { TEXT("application/json") };

	HttpRequest->SetVerb(TEXT("DELETE"));

}

void OpenAPIDNSApi::DeleteDnsRecordResponse::SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode)
{
	Response::SetHttpResponseCode(InHttpResponseCode);
	switch ((int)InHttpResponseCode)
	{
	case 401:
		SetResponseString(TEXT("Unauthorized"));
		break;
	case 0:
	default:
		SetResponseString(TEXT("Default response"));
		break;
	}
}

bool OpenAPIDNSApi::DeleteDnsRecordResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return true;
}

FString OpenAPIDNSApi::GetDnsDomainRequest::ComputePath() const
{
	TMap<FString, FStringFormatArg> PathParams = { 
	{ TEXT("id"), FStringFormatArg(ToUrlString(Id)) } };

	FString Path = FString::Format(TEXT("/dns/{id}"), PathParams);

	return Path;
}

void OpenAPIDNSApi::GetDnsDomainRequest::SetupHttpRequest(const FHttpRequestRef& HttpRequest) const
{
	static const TArray<FString> Consumes = {  };
	//static const TArray<FString> Produces = { TEXT("application/json") };

	HttpRequest->SetVerb(TEXT("GET"));

}

void OpenAPIDNSApi::GetDnsDomainResponse::SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode)
{
	Response::SetHttpResponseCode(InHttpResponseCode);
	switch ((int)InHttpResponseCode)
	{
	case 200:
		SetResponseString(TEXT("The DNS records for the specified domain."));
		break;
	case 401:
		SetResponseString(TEXT("Unauthorized"));
		break;
	}
}

bool OpenAPIDNSApi::GetDnsDomainResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Content);
}

FString OpenAPIDNSApi::GetDnsListRequest::ComputePath() const
{
	FString Path(TEXT("/dns"));
	return Path;
}

void OpenAPIDNSApi::GetDnsListRequest::SetupHttpRequest(const FHttpRequestRef& HttpRequest) const
{
	static const TArray<FString> Consumes = {  };
	//static const TArray<FString> Produces = { TEXT("application/json") };

	HttpRequest->SetVerb(TEXT("GET"));

}

void OpenAPIDNSApi::GetDnsListResponse::SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode)
{
	Response::SetHttpResponseCode(InHttpResponseCode);
	switch ((int)InHttpResponseCode)
	{
	case 200:
		SetResponseString(TEXT("Listing of DNS domains on the account with their primary A record."));
		break;
	case 401:
		SetResponseString(TEXT("Unauthorized"));
		break;
	}
}

bool OpenAPIDNSApi::GetDnsListResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return TryGetJsonValue(JsonValue, Content);
}

FString OpenAPIDNSApi::UpdateDnsRecordRequest::ComputePath() const
{
	TMap<FString, FStringFormatArg> PathParams = { 
	{ TEXT("domainId"), FStringFormatArg(ToUrlString(DomainId)) },
	{ TEXT("recordId"), FStringFormatArg(ToUrlString(RecordId)) } };

	FString Path = FString::Format(TEXT("/dns/{domainId}/{recordId}"), PathParams);

	return Path;
}

void OpenAPIDNSApi::UpdateDnsRecordRequest::SetupHttpRequest(const FHttpRequestRef& HttpRequest) const
{
	static const TArray<FString> Consumes = { TEXT("multipart/form-data"), TEXT("application/json") };
	//static const TArray<FString> Produces = { TEXT("application/json") };

	HttpRequest->SetVerb(TEXT("POST"));

	// Default to Json Body request
	if (Consumes.Num() == 0 || Consumes.Contains(TEXT("application/json")))
	{
		// Form parameters added to try to generate a json body when no body parameters are specified.
		FString JsonBody;
		JsonWriter Writer = TJsonWriterFactory<>::Create(&JsonBody);
		Writer->WriteObjectStart();
		if (Name.IsSet()){
			Writer->WriteIdentifierPrefix(TEXT("name"));
			WriteJsonValue(Writer, Name.GetValue());
		}
		if (Type.IsSet()){
			Writer->WriteIdentifierPrefix(TEXT("type"));
			WriteJsonValue(Writer, Type.GetValue());
		}
		if (Content.IsSet()){
			Writer->WriteIdentifierPrefix(TEXT("content"));
			WriteJsonValue(Writer, Content.GetValue());
		}
		if (Ttl.IsSet()){
			Writer->WriteIdentifierPrefix(TEXT("ttl"));
			WriteJsonValue(Writer, Ttl.GetValue());
		}
		if (Prio.IsSet()){
			Writer->WriteIdentifierPrefix(TEXT("prio"));
			WriteJsonValue(Writer, Prio.GetValue());
		}
		if (Disabled.IsSet()){
			Writer->WriteIdentifierPrefix(TEXT("disabled"));
			WriteJsonValue(Writer, Disabled.GetValue());
		}
		if (Ordername.IsSet()){
			Writer->WriteIdentifierPrefix(TEXT("ordername"));
			WriteJsonValue(Writer, Ordername.GetValue());
		}
		if (Auth.IsSet()){
			Writer->WriteIdentifierPrefix(TEXT("auth"));
			WriteJsonValue(Writer, Auth.GetValue());
		}
		Writer->WriteObjectEnd();
		Writer->Close();
		HttpRequest->SetHeader(TEXT("Content-Type"), TEXT("application/json; charset=utf-8"));
		HttpRequest->SetContentAsString(JsonBody);
	}
	else if (Consumes.Contains(TEXT("multipart/form-data")))
	{
		HttpMultipartFormData FormData;
		if(Name.IsSet())
		{
			FormData.AddStringPart(TEXT("name"), *ToUrlString(Name.GetValue()));
		}
		if(Type.IsSet())
		{
			FormData.AddStringPart(TEXT("type"), *ToUrlString(Type.GetValue()));
		}
		if(Content.IsSet())
		{
			FormData.AddStringPart(TEXT("content"), *ToUrlString(Content.GetValue()));
		}
		if(Ttl.IsSet())
		{
			FormData.AddStringPart(TEXT("ttl"), *ToUrlString(Ttl.GetValue()));
		}
		if(Prio.IsSet())
		{
			FormData.AddStringPart(TEXT("prio"), *ToUrlString(Prio.GetValue()));
		}
		if(Disabled.IsSet())
		{
			FormData.AddStringPart(TEXT("disabled"), *ToUrlString(Disabled.GetValue()));
		}
		if(Ordername.IsSet())
		{
			FormData.AddStringPart(TEXT("ordername"), *ToUrlString(Ordername.GetValue()));
		}
		if(Auth.IsSet())
		{
			FormData.AddStringPart(TEXT("auth"), *ToUrlString(Auth.GetValue()));
		}

		FormData.SetupHttpRequest(HttpRequest);
	}
	else if (Consumes.Contains(TEXT("application/x-www-form-urlencoded")))
	{
		TArray<FString> FormParams;
		if(Name.IsSet())
		{
			FormParams.Add(FString(TEXT("name=")) + ToUrlString(Name.GetValue()));
		}
		if(Type.IsSet())
		{
			FormParams.Add(FString(TEXT("type=")) + ToUrlString(Type.GetValue()));
		}
		if(Content.IsSet())
		{
			FormParams.Add(FString(TEXT("content=")) + ToUrlString(Content.GetValue()));
		}
		if(Ttl.IsSet())
		{
			FormParams.Add(FString(TEXT("ttl=")) + ToUrlString(Ttl.GetValue()));
		}
		if(Prio.IsSet())
		{
			FormParams.Add(FString(TEXT("prio=")) + ToUrlString(Prio.GetValue()));
		}
		if(Disabled.IsSet())
		{
			FormParams.Add(FString(TEXT("disabled=")) + ToUrlString(Disabled.GetValue()));
		}
		if(Ordername.IsSet())
		{
			FormParams.Add(FString(TEXT("ordername=")) + ToUrlString(Ordername.GetValue()));
		}
		if(Auth.IsSet())
		{
			FormParams.Add(FString(TEXT("auth=")) + ToUrlString(Auth.GetValue()));
		}

		HttpRequest->SetHeader(TEXT("Content-Type"), TEXT("application/x-www-form-urlencoded; charset=utf-8"));
		HttpRequest->SetContentAsString(FString::Join(FormParams, TEXT("&")));
	}
	else
	{
		UE_LOG(LogOpenAPI, Error, TEXT("Request ContentType not supported (%s)"), *FString::Join(Consumes, TEXT(",")));
	}
}

void OpenAPIDNSApi::UpdateDnsRecordResponse::SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode)
{
	Response::SetHttpResponseCode(InHttpResponseCode);
	switch ((int)InHttpResponseCode)
	{
	case 401:
		SetResponseString(TEXT("Unauthorized"));
		break;
	case 0:
	default:
		SetResponseString(TEXT("Default response"));
		break;
	}
}

bool OpenAPIDNSApi::UpdateDnsRecordResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	return true;
}

}
