-module(openapi_vps_service_master).

-export([encode/1]).

-export_type([openapi_vps_service_master/0]).

-type openapi_vps_service_master() ::
    #{ 'vps_id' => binary(),
       'vps_name' => binary(),
       'vps_ip' => binary(),
       'vps_type' => binary(),
       'vps_hdsize' => binary(),
       'vps_hdfree' => binary(),
       'vps_bits' => binary(),
       'vps_load' => binary(),
       'vps_ram' => binary(),
       'vps_cpu_model' => binary(),
       'vps_cpu_mhz' => binary(),
       'vps_location' => binary(),
       'vps_last_update' => binary(),
       'vps_raid_building' => binary(),
       'vps_kernel' => binary(),
       'vps_available' => binary(),
       'vps_cores' => binary(),
       'vps_iowait' => binary(),
       'vps_raid_status' => binary(),
       'vps_mounts' => binary(),
       'vps_server_max' => binary(),
       'vps_server_max_slices' => binary(),
       'vps_drive_type' => binary(),
       'vps_order' => binary()
     }.

encode(#{ 'vps_id' := VpsId,
          'vps_name' := VpsName,
          'vps_ip' := VpsIp,
          'vps_type' := VpsType,
          'vps_hdsize' := VpsHdsize,
          'vps_hdfree' := VpsHdfree,
          'vps_bits' := VpsBits,
          'vps_load' := VpsLoad,
          'vps_ram' := VpsRam,
          'vps_cpu_model' := VpsCpuModel,
          'vps_cpu_mhz' := VpsCpuMhz,
          'vps_location' := VpsLocation,
          'vps_last_update' := VpsLastUpdate,
          'vps_raid_building' := VpsRaidBuilding,
          'vps_kernel' := VpsKernel,
          'vps_available' := VpsAvailable,
          'vps_cores' := VpsCores,
          'vps_iowait' := VpsIowait,
          'vps_raid_status' := VpsRaidStatus,
          'vps_mounts' := VpsMounts,
          'vps_server_max' := VpsServerMax,
          'vps_server_max_slices' := VpsServerMaxSlices,
          'vps_drive_type' := VpsDriveType,
          'vps_order' := VpsOrder
        }) ->
    #{ 'vps_id' => VpsId,
       'vps_name' => VpsName,
       'vps_ip' => VpsIp,
       'vps_type' => VpsType,
       'vps_hdsize' => VpsHdsize,
       'vps_hdfree' => VpsHdfree,
       'vps_bits' => VpsBits,
       'vps_load' => VpsLoad,
       'vps_ram' => VpsRam,
       'vps_cpu_model' => VpsCpuModel,
       'vps_cpu_mhz' => VpsCpuMhz,
       'vps_location' => VpsLocation,
       'vps_last_update' => VpsLastUpdate,
       'vps_raid_building' => VpsRaidBuilding,
       'vps_kernel' => VpsKernel,
       'vps_available' => VpsAvailable,
       'vps_cores' => VpsCores,
       'vps_iowait' => VpsIowait,
       'vps_raid_status' => VpsRaidStatus,
       'vps_mounts' => VpsMounts,
       'vps_server_max' => VpsServerMax,
       'vps_server_max_slices' => VpsServerMaxSlices,
       'vps_drive_type' => VpsDriveType,
       'vps_order' => VpsOrder
     }.
