-module(openapi_vps_service_info).

-export([encode/1]).

-export_type([openapi_vps_service_info/0]).

-type openapi_vps_service_info() ::
    #{ 'vps_id' => binary(),
       'vps_custid' => binary(),
       'vps_server' => binary(),
       'vps_ip' => binary(),
       'vps_ipv6' => binary(),
       'vps_vzid' => binary(),
       'vps_currency' => binary(),
       'vps_type' => binary(),
       'vps_order_date' => binary(),
       'vps_status' => binary(),
       'vps_invoice' => binary(),
       'vps_coupon' => binary(),
       'vps_extra' => binary(),
       'vps_hostname' => binary(),
       'vps_server_status' => binary(),
       'vps_comment' => binary(),
       'vps_slices' => binary(),
       'vps_vnc' => binary(),
       'vps_vnc_port' => binary(),
       'vps_rootpass' => binary(),
       'vps_mac' => binary(),
       'vps_os' => binary(),
       'vps_version' => binary(),
       'vps_location' => binary(),
       'vps_platform' => binary(),
       'vps_diskused' => binary(),
       'vps_diskmax' => binary()
     }.

encode(#{ 'vps_id' := VpsId,
          'vps_custid' := VpsCustid,
          'vps_server' := VpsServer,
          'vps_ip' := VpsIp,
          'vps_ipv6' := VpsIpv6,
          'vps_vzid' := VpsVzid,
          'vps_currency' := VpsCurrency,
          'vps_type' := VpsType,
          'vps_order_date' := VpsOrderDate,
          'vps_status' := VpsStatus,
          'vps_invoice' := VpsInvoice,
          'vps_coupon' := VpsCoupon,
          'vps_extra' := VpsExtra,
          'vps_hostname' := VpsHostname,
          'vps_server_status' := VpsServerStatus,
          'vps_comment' := VpsComment,
          'vps_slices' := VpsSlices,
          'vps_vnc' := VpsVnc,
          'vps_vnc_port' := VpsVncPort,
          'vps_rootpass' := VpsRootpass,
          'vps_mac' := VpsMac,
          'vps_os' := VpsOs,
          'vps_version' := VpsVersion,
          'vps_location' := VpsLocation,
          'vps_platform' := VpsPlatform,
          'vps_diskused' := VpsDiskused,
          'vps_diskmax' := VpsDiskmax
        }) ->
    #{ 'vps_id' => VpsId,
       'vps_custid' => VpsCustid,
       'vps_server' => VpsServer,
       'vps_ip' => VpsIp,
       'vps_ipv6' => VpsIpv6,
       'vps_vzid' => VpsVzid,
       'vps_currency' => VpsCurrency,
       'vps_type' => VpsType,
       'vps_order_date' => VpsOrderDate,
       'vps_status' => VpsStatus,
       'vps_invoice' => VpsInvoice,
       'vps_coupon' => VpsCoupon,
       'vps_extra' => VpsExtra,
       'vps_hostname' => VpsHostname,
       'vps_server_status' => VpsServerStatus,
       'vps_comment' => VpsComment,
       'vps_slices' => VpsSlices,
       'vps_vnc' => VpsVnc,
       'vps_vnc_port' => VpsVncPort,
       'vps_rootpass' => VpsRootpass,
       'vps_mac' => VpsMac,
       'vps_os' => VpsOs,
       'vps_version' => VpsVersion,
       'vps_location' => VpsLocation,
       'vps_platform' => VpsPlatform,
       'vps_diskused' => VpsDiskused,
       'vps_diskmax' => VpsDiskmax
     }.
