-module(openapi_server_order_cpu).

-export([encode/1]).

-export_type([openapi_server_order_cpu/0]).

-type openapi_server_order_cpu() ::
    #{ 'id' => binary(),
       'price' => integer(),
       'img' => binary(),
       'short_desc' => binary(),
       'long_desc' => binary(),
       'location' => binary(),
       'fsb' => binary(),
       'manu' => binary(),
       'type' => binary(),
       'speed' => binary(),
       'cache' => binary(),
       'active' => binary(),
       'num_cores' => binary(),
       'num_cpus' => binary(),
       'benchmark' => binary(),
       'monthly_price' => integer(),
       'max_ram' => binary(),
       'min_ram' => binary(),
       'max_lff' => binary(),
       'max_sff' => binary(),
       'max_nve' => binary(),
       'visible' => binary(),
       'hd_ids' => openapi_any_type:openapi_any_type(),
       'price_display' => binary(),
       'monthly_price_display' => binary()
     }.

encode(#{ 'id' := Id,
          'price' := Price,
          'img' := Img,
          'short_desc' := ShortDesc,
          'long_desc' := LongDesc,
          'location' := Location,
          'fsb' := Fsb,
          'manu' := Manu,
          'type' := Type,
          'speed' := Speed,
          'cache' := Cache,
          'active' := Active,
          'num_cores' := NumCores,
          'num_cpus' := NumCpus,
          'benchmark' := Benchmark,
          'monthly_price' := MonthlyPrice,
          'max_ram' := MaxRam,
          'min_ram' := MinRam,
          'max_lff' := MaxLff,
          'max_sff' := MaxSff,
          'max_nve' := MaxNve,
          'visible' := Visible,
          'hd_ids' := HdIds,
          'price_display' := PriceDisplay,
          'monthly_price_display' := MonthlyPriceDisplay
        }) ->
    #{ 'id' => Id,
       'price' => Price,
       'img' => Img,
       'short_desc' => ShortDesc,
       'long_desc' => LongDesc,
       'location' => Location,
       'fsb' => Fsb,
       'manu' => Manu,
       'type' => Type,
       'speed' => Speed,
       'cache' => Cache,
       'active' => Active,
       'num_cores' => NumCores,
       'num_cpus' => NumCpus,
       'benchmark' => Benchmark,
       'monthly_price' => MonthlyPrice,
       'max_ram' => MaxRam,
       'min_ram' => MinRam,
       'max_lff' => MaxLff,
       'max_sff' => MaxSff,
       'max_nve' => MaxNve,
       'visible' => Visible,
       'hd_ids' => HdIds,
       'price_display' => PriceDisplay,
       'monthly_price_display' => MonthlyPriceDisplay
     }.
