-module(openapi_mail_log_entry).

-export([encode/1]).

-export_type([openapi_mail_log_entry/0]).

-type openapi_mail_log_entry() ::
    #{ '_id' := integer(),
       'id' := binary(),
       'from' := binary(),
       'to' := binary(),
       'subject' => binary(),
       'messageId' => binary(),
       'created' := binary(),
       'time' := integer(),
       'user' := binary(),
       'transtype' := binary(),
       'origin' := binary(),
       'interface' := binary(),
       'sendingZone' => binary(),
       'bodySize' => integer(),
       'seq' => integer(),
       'delivered' => integer(),
       'code' => integer(),
       'recipient' => binary(),
       'response' => binary(),
       'domain' => binary(),
       'locked' => integer(),
       'lockTime' => binary(),
       'assigned' => binary(),
       'queued' => binary(),
       'mxHostname' => binary()
     }.

encode(#{ '_id' := Id,
          'id' := Id,
          'from' := From,
          'to' := To,
          'subject' := Subject,
          'messageId' := MessageId,
          'created' := Created,
          'time' := Time,
          'user' := User,
          'transtype' := Transtype,
          'origin' := Origin,
          'interface' := Interface,
          'sendingZone' := SendingZone,
          'bodySize' := BodySize,
          'seq' := Seq,
          'delivered' := Delivered,
          'code' := Code,
          'recipient' := Recipient,
          'response' := Response,
          'domain' := Domain,
          'locked' := Locked,
          'lockTime' := LockTime,
          'assigned' := Assigned,
          'queued' := Queued,
          'mxHostname' := MxHostname
        }) ->
    #{ '_id' => Id,
       'id' => Id,
       'from' => From,
       'to' => To,
       'subject' => Subject,
       'messageId' => MessageId,
       'created' => Created,
       'time' => Time,
       'user' => User,
       'transtype' => Transtype,
       'origin' => Origin,
       'interface' => Interface,
       'sendingZone' => SendingZone,
       'bodySize' => BodySize,
       'seq' => Seq,
       'delivered' => Delivered,
       'code' => Code,
       'recipient' => Recipient,
       'response' => Response,
       'domain' => Domain,
       'locked' => Locked,
       'lockTime' => LockTime,
       'assigned' => Assigned,
       'queued' => Queued,
       'mxHostname' => MxHostname
     }.
