-module(openapi_quickserver_service_info).

-export([encode/1]).

-export_type([openapi_quickserver_service_info/0]).

-type openapi_quickserver_service_info() ::
    #{ 'qs_id' => binary(),
       'qs_custid' => binary(),
       'qs_server' => binary(),
       'qs_ip' => binary(),
       'qs_ipv6' => openapi_any_type:openapi_any_type(),
       'qs_vzid' => binary(),
       'qs_currency' => binary(),
       'qs_type' => binary(),
       'qs_order_date' => binary(),
       'qs_status' => binary(),
       'qs_invoice' => binary(),
       'qs_coupon' => binary(),
       'qs_extra' => binary(),
       'qs_hostname' => binary(),
       'qs_server_status' => binary(),
       'qs_comment' => binary(),
       'qs_slices' => binary(),
       'qs_vnc' => binary(),
       'qs_vnc_port' => openapi_any_type:openapi_any_type(),
       'qs_rootpass' => binary(),
       'qs_mac' => binary(),
       'qs_os' => binary(),
       'qs_version' => binary(),
       'qs_location' => binary(),
       'qs_platform' => openapi_any_type:openapi_any_type()
     }.

encode(#{ 'qs_id' := QsId,
          'qs_custid' := QsCustid,
          'qs_server' := QsServer,
          'qs_ip' := QsIp,
          'qs_ipv6' := QsIpv6,
          'qs_vzid' := QsVzid,
          'qs_currency' := QsCurrency,
          'qs_type' := QsType,
          'qs_order_date' := QsOrderDate,
          'qs_status' := QsStatus,
          'qs_invoice' := QsInvoice,
          'qs_coupon' := QsCoupon,
          'qs_extra' := QsExtra,
          'qs_hostname' := QsHostname,
          'qs_server_status' := QsServerStatus,
          'qs_comment' := QsComment,
          'qs_slices' := QsSlices,
          'qs_vnc' := QsVnc,
          'qs_vnc_port' := QsVncPort,
          'qs_rootpass' := QsRootpass,
          'qs_mac' := QsMac,
          'qs_os' := QsOs,
          'qs_version' := QsVersion,
          'qs_location' := QsLocation,
          'qs_platform' := QsPlatform
        }) ->
    #{ 'qs_id' => QsId,
       'qs_custid' => QsCustid,
       'qs_server' => QsServer,
       'qs_ip' => QsIp,
       'qs_ipv6' => QsIpv6,
       'qs_vzid' => QsVzid,
       'qs_currency' => QsCurrency,
       'qs_type' => QsType,
       'qs_order_date' => QsOrderDate,
       'qs_status' => QsStatus,
       'qs_invoice' => QsInvoice,
       'qs_coupon' => QsCoupon,
       'qs_extra' => QsExtra,
       'qs_hostname' => QsHostname,
       'qs_server_status' => QsServerStatus,
       'qs_comment' => QsComment,
       'qs_slices' => QsSlices,
       'qs_vnc' => QsVnc,
       'qs_vnc_port' => QsVncPort,
       'qs_rootpass' => QsRootpass,
       'qs_mac' => QsMac,
       'qs_os' => QsOs,
       'qs_version' => QsVersion,
       'qs_location' => QsLocation,
       'qs_platform' => QsPlatform
     }.
