-module(openapi_quickserver_service_master).

-export([encode/1]).

-export_type([openapi_quickserver_service_master/0]).

-type openapi_quickserver_service_master() ::
    #{ 'qs_id' => binary(),
       'qs_name' => binary(),
       'qs_ip' => binary(),
       'qs_type' => binary(),
       'qs_hdsize' => binary(),
       'qs_hdfree' => binary(),
       'qs_bits' => binary(),
       'qs_load' => binary(),
       'qs_ram' => binary(),
       'qs_cpu_model' => binary(),
       'qs_cpu_mhz' => binary(),
       'qs_location' => binary(),
       'qs_available' => binary(),
       'qs_cost' => binary(),
       'qs_last_update' => binary(),
       'qs_cores' => binary(),
       'qs_iowait' => binary(),
       'qs_raid_status' => binary(),
       'qs_drive_type' => binary(),
       'qs_order' => binary(),
       'qs_raid_building' => binary(),
       'qs_kernel' => binary(),
       'qs_ioping' => binary(),
       'qs_speed' => binary(),
       'qs_distro' => binary(),
       'qs_distro_version' => binary(),
       'qs_bytes_sec_in' => binary(),
       'qs_bytes_sec_out' => binary(),
       'qs_packets_sec_in' => binary(),
       'qs_packets_sec_out' => binary(),
       'qs_last_install_time' => binary(),
       'qs_partitions' => binary(),
       'qs_cpu_flags' => binary()
     }.

encode(#{ 'qs_id' := QsId,
          'qs_name' := QsName,
          'qs_ip' := QsIp,
          'qs_type' := QsType,
          'qs_hdsize' := QsHdsize,
          'qs_hdfree' := QsHdfree,
          'qs_bits' := QsBits,
          'qs_load' := QsLoad,
          'qs_ram' := QsRam,
          'qs_cpu_model' := QsCpuModel,
          'qs_cpu_mhz' := QsCpuMhz,
          'qs_location' := QsLocation,
          'qs_available' := QsAvailable,
          'qs_cost' := QsCost,
          'qs_last_update' := QsLastUpdate,
          'qs_cores' := QsCores,
          'qs_iowait' := QsIowait,
          'qs_raid_status' := QsRaidStatus,
          'qs_drive_type' := QsDriveType,
          'qs_order' := QsOrder,
          'qs_raid_building' := QsRaidBuilding,
          'qs_kernel' := QsKernel,
          'qs_ioping' := QsIoping,
          'qs_speed' := QsSpeed,
          'qs_distro' := QsDistro,
          'qs_distro_version' := QsDistroVersion,
          'qs_bytes_sec_in' := QsBytesSecIn,
          'qs_bytes_sec_out' := QsBytesSecOut,
          'qs_packets_sec_in' := QsPacketsSecIn,
          'qs_packets_sec_out' := QsPacketsSecOut,
          'qs_last_install_time' := QsLastInstallTime,
          'qs_partitions' := QsPartitions,
          'qs_cpu_flags' := QsCpuFlags
        }) ->
    #{ 'qs_id' => QsId,
       'qs_name' => QsName,
       'qs_ip' => QsIp,
       'qs_type' => QsType,
       'qs_hdsize' => QsHdsize,
       'qs_hdfree' => QsHdfree,
       'qs_bits' => QsBits,
       'qs_load' => QsLoad,
       'qs_ram' => QsRam,
       'qs_cpu_model' => QsCpuModel,
       'qs_cpu_mhz' => QsCpuMhz,
       'qs_location' => QsLocation,
       'qs_available' => QsAvailable,
       'qs_cost' => QsCost,
       'qs_last_update' => QsLastUpdate,
       'qs_cores' => QsCores,
       'qs_iowait' => QsIowait,
       'qs_raid_status' => QsRaidStatus,
       'qs_drive_type' => QsDriveType,
       'qs_order' => QsOrder,
       'qs_raid_building' => QsRaidBuilding,
       'qs_kernel' => QsKernel,
       'qs_ioping' => QsIoping,
       'qs_speed' => QsSpeed,
       'qs_distro' => QsDistro,
       'qs_distro_version' => QsDistroVersion,
       'qs_bytes_sec_in' => QsBytesSecIn,
       'qs_bytes_sec_out' => QsBytesSecOut,
       'qs_packets_sec_in' => QsPacketsSecIn,
       'qs_packets_sec_out' => QsPacketsSecOut,
       'qs_last_install_time' => QsLastInstallTime,
       'qs_partitions' => QsPartitions,
       'qs_cpu_flags' => QsCpuFlags
     }.
