-module(openapi_vps_order).

-export([encode/1]).

-export_type([openapi_vps_order/0]).

-type openapi_vps_order() ::
    #{ 'vpsSliceSsdOvzCost' := integer(),
       'vpsSliceOvzCost' := integer(),
       'vpsSliceSsdVirtuozzoCost' := integer(),
       'vpsSliceVirtuozzoCost' := integer(),
       'vpsSliceHypervCost' := integer(),
       'vpsSliceVmwareCost' := integer(),
       'vpsSliceLxcCost' := integer(),
       'vpsSliceXenCost' := integer(),
       'vpsSliceKvmLCost' := integer(),
       'vpsSliceKvmStorageCost' := integer(),
       'vpsNyCost' := integer(),
       'vpsSliceKvmWCost' := integer(),
       'cpanelCost' := integer(),
       'daCost' := integer(),
       'ramSlice' := binary(),
       'hdSlice' := binary(),
       'hdStorageSlice' := binary(),
       'bwSlice' := binary(),
       'bwType' := binary(),
       'bwTotal' := integer(),
       'maxSlices' := binary(),
       'platformPackages' := openapi_vps_order_platform_packages:openapi_vps_order_platform_packages(),
       'platformNames' := openapi_vps_order_platform_names:openapi_vps_order_platform_names(),
       'packageCosts' := openapi_vps_order_package_costs:openapi_vps_order_package_costs(),
       'locationStock' := openapi_vps_order_location_stock:openapi_vps_order_location_stock(),
       'locationNames' := openapi_vps_order_location_names:openapi_vps_order_location_names(),
       'osNames' := openapi_vps_order_os_names:openapi_vps_order_os_names(),
       'templates' := openapi_vps_order_templates:openapi_vps_order_templates(),
       'serviceTypes' := openapi_vps_order_service_types:openapi_vps_order_service_types(),
       'currency' := binary(),
       'currencySymbol' := binary()
     }.

encode(#{ 'vpsSliceSsdOvzCost' := VpsSliceSsdOvzCost,
          'vpsSliceOvzCost' := VpsSliceOvzCost,
          'vpsSliceSsdVirtuozzoCost' := VpsSliceSsdVirtuozzoCost,
          'vpsSliceVirtuozzoCost' := VpsSliceVirtuozzoCost,
          'vpsSliceHypervCost' := VpsSliceHypervCost,
          'vpsSliceVmwareCost' := VpsSliceVmwareCost,
          'vpsSliceLxcCost' := VpsSliceLxcCost,
          'vpsSliceXenCost' := VpsSliceXenCost,
          'vpsSliceKvmLCost' := VpsSliceKvmLCost,
          'vpsSliceKvmStorageCost' := VpsSliceKvmStorageCost,
          'vpsNyCost' := VpsNyCost,
          'vpsSliceKvmWCost' := VpsSliceKvmWCost,
          'cpanelCost' := CpanelCost,
          'daCost' := DaCost,
          'ramSlice' := RamSlice,
          'hdSlice' := HdSlice,
          'hdStorageSlice' := HdStorageSlice,
          'bwSlice' := BwSlice,
          'bwType' := BwType,
          'bwTotal' := BwTotal,
          'maxSlices' := MaxSlices,
          'platformPackages' := PlatformPackages,
          'platformNames' := PlatformNames,
          'packageCosts' := PackageCosts,
          'locationStock' := LocationStock,
          'locationNames' := LocationNames,
          'osNames' := OsNames,
          'templates' := Templates,
          'serviceTypes' := ServiceTypes,
          'currency' := Currency,
          'currencySymbol' := CurrencySymbol
        }) ->
    #{ 'vpsSliceSsdOvzCost' => VpsSliceSsdOvzCost,
       'vpsSliceOvzCost' => VpsSliceOvzCost,
       'vpsSliceSsdVirtuozzoCost' => VpsSliceSsdVirtuozzoCost,
       'vpsSliceVirtuozzoCost' => VpsSliceVirtuozzoCost,
       'vpsSliceHypervCost' => VpsSliceHypervCost,
       'vpsSliceVmwareCost' => VpsSliceVmwareCost,
       'vpsSliceLxcCost' => VpsSliceLxcCost,
       'vpsSliceXenCost' => VpsSliceXenCost,
       'vpsSliceKvmLCost' => VpsSliceKvmLCost,
       'vpsSliceKvmStorageCost' => VpsSliceKvmStorageCost,
       'vpsNyCost' => VpsNyCost,
       'vpsSliceKvmWCost' => VpsSliceKvmWCost,
       'cpanelCost' => CpanelCost,
       'daCost' => DaCost,
       'ramSlice' => RamSlice,
       'hdSlice' => HdSlice,
       'hdStorageSlice' => HdStorageSlice,
       'bwSlice' => BwSlice,
       'bwType' => BwType,
       'bwTotal' => BwTotal,
       'maxSlices' => MaxSlices,
       'platformPackages' => PlatformPackages,
       'platformNames' => PlatformNames,
       'packageCosts' => PackageCosts,
       'locationStock' => LocationStock,
       'locationNames' => LocationNames,
       'osNames' => OsNames,
       'templates' => Templates,
       'serviceTypes' => ServiceTypes,
       'currency' => Currency,
       'currencySymbol' => CurrencySymbol
     }.
