/*
 * InterServer Management API
 * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
 *
 * OpenAPI spec version: 0.9.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InterServerManagementApi);
  }
}(this, function(expect, InterServerManagementApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ServerLocation1', function() {
      beforeEach(function() {
        instance = new InterServerManagementApi.ServerLocation1();
      });

      it('should create an instance of ServerLocation1', function() {
        // TODO: update the code to test ServerLocation1
        expect(instance).to.be.a(InterServerManagementApi.ServerLocation1);
      });

      it('should have the property location_id (base name: "location_id")', function() {
        // TODO: update the code to test the property location_id
        expect(instance).to.have.property('location_id');
        // expect(instance.location_id).to.be(expectedValueLiteral);
      });

      it('should have the property location_name (base name: "location_name")', function() {
        // TODO: update the code to test the property location_name
        expect(instance).to.have.property('location_name');
        // expect(instance.location_name).to.be(expectedValueLiteral);
      });

      it('should have the property location_description (base name: "location_description")', function() {
        // TODO: update the code to test the property location_description
        expect(instance).to.have.property('location_description');
        // expect(instance.location_description).to.be(expectedValueLiteral);
      });

      it('should have the property location_lat (base name: "location_lat")', function() {
        // TODO: update the code to test the property location_lat
        expect(instance).to.have.property('location_lat');
        // expect(instance.location_lat).to.be(expectedValueLiteral);
      });

      it('should have the property location_long (base name: "location_long")', function() {
        // TODO: update the code to test the property location_long
        expect(instance).to.have.property('location_long');
        // expect(instance.location_long).to.be(expectedValueLiteral);
      });

      it('should have the property location_ipmi_group (base name: "location_ipmi_group")', function() {
        // TODO: update the code to test the property location_ipmi_group
        expect(instance).to.have.property('location_ipmi_group');
        // expect(instance.location_ipmi_group).to.be(expectedValueLiteral);
      });

    });
  });

}));
