/**
 * InterServer Management API
 *
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Payload for creating a mail alert.
 */
export interface MailAlertRequest { 
    /**
     * Alert type identifier.
     */
    type?: string;
    /**
     * Alert value or threshold.
     */
    value?: string;
    /**
     * Email address to notify.
     */
    to?: string;
    /**
     * Whether the alert is enabled.
     */
    enabled?: string;
}

