/**
 * InterServer Management API
 *
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VpsDALicense } from './vpsDALicense';


/**
 * DirectAdmin license options available for a VPS.
 */
export interface VpsDAData { 
    free?: VpsDALicense;
}

