export * from './AccountApi';
import { AccountApi } from './AccountApi';
export * from './BackupsApi';
import { BackupsApi } from './BackupsApi';
export * from './BillingApi';
import { BillingApi } from './BillingApi';
export * from './DNSApi';
import { DNSApi } from './DNSApi';
export * from './DomainsApi';
import { DomainsApi } from './DomainsApi';
export * from './FloatingIPsApi';
import { FloatingIPsApi } from './FloatingIPsApi';
export * from './LicensesApi';
import { LicensesApi } from './LicensesApi';
export * from './MailApi';
import { MailApi } from './MailApi';
export * from './PublicApi';
import { PublicApi } from './PublicApi';
export * from './QuickServersApi';
import { QuickServersApi } from './QuickServersApi';
export * from './SSLCertificatesApi';
import { SSLCertificatesApi } from './SSLCertificatesApi';
export * from './ScrubIpsApi';
import { ScrubIpsApi } from './ScrubIpsApi';
export * from './ServersApi';
import { ServersApi } from './ServersApi';
export * from './TicketsApi';
import { TicketsApi } from './TicketsApi';
export * from './VPSApi';
import { VPSApi } from './VPSApi';
export * from './WebhostingApi';
import { WebhostingApi } from './WebhostingApi';
export const APIS = [AccountApi, BackupsApi, BillingApi, DNSApi, DomainsApi, FloatingIPsApi, LicensesApi, MailApi, PublicApi, QuickServersApi, SSLCertificatesApi, ScrubIpsApi, ServersApi, TicketsApi, VPSApi, WebhostingApi];
