/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.78).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ChargeInvoiceRows;
import io.swagger.model.InlineResponse2004;
import io.swagger.model.InlineResponse401;
import io.swagger.model.IpObject;
import io.swagger.model.License;
import io.swagger.model.LicenseRow;
import io.swagger.model.LicensesOrder;
import io.swagger.model.ServiceOrderPostResponse;
import io.swagger.model.SuccessTextResponse;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.micronaut.http.*;
import io.micronaut.http.annotation.*;
import io.reactivex.rxjava3.core.Single;
import io.swagger.v3.oas.annotations.*;
import io.swagger.v3.oas.annotations.responses.*;

import javax.annotation.Nullable;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Map;


public interface LicensesApi {


    @Operation(summary = "Place License Order", operationId = "addLicense", description = "Places an order for a new software license. Use `PUT /licenses/order` to validate the order first." , tags = {"Licenses"})
    @ApiResponse(responseCode = "200", description = "Order placed successfully. Use the invoice ID to proceed to payment via `/pay/{method}/{invoices}` or view the invoice at `/billing/invoices/{id}`.")
    @ApiResponse(responseCode = "401", description = "Unauthorized")
    @Post(value = "/licenses/order", produces = { "application/json" })
    default Single<HttpResponse<ServiceOrderPostResponse>> addLicense() {
        return Single.fromCallable(() -> {
            throw new UnsupportedOperationException();
        });
    }


    @Operation(summary = "Get License", operationId = "getLicenseInfo", description = "Returns detailed information about a specific license including its type, IP assignment, and status." , tags = {"Licenses"})
    @ApiResponse(responseCode = "200", description = "License information.")
    @ApiResponse(responseCode = "401", description = "Unauthorized")
    @Get(value = "/licenses/{id}", produces = { "application/json" })
    default Single<HttpResponse<License>> getLicenseInfo(@Parameter(description = "The license service ID. Use `license_id` from `GET /licenses`.") @PathVariable("id") Integer id) {
        return Single.fromCallable(() -> {
            throw new UnsupportedOperationException();
        });
    }


    @Operation(summary = "Get License Invoices", operationId = "getLicenseInvoices", description = "Returns the billing invoices associated with this license service." , tags = {"Licenses"})
    @ApiResponse(responseCode = "200", description = "Get Invoices response")
    @ApiResponse(responseCode = "401", description = "Unauthorized")
    @Get(value = "/licenses/{id}/invoices", produces = { "application/json" })
    default Single<HttpResponse<ChargeInvoiceRows>> getLicenseInvoices(@Parameter(description = "The license service ID. Use `license_id` from `GET /licenses`.") @PathVariable("id") Integer id) {
        return Single.fromCallable(() -> {
            throw new UnsupportedOperationException();
        });
    }


    @Operation(summary = "List Licenses", operationId = "getLicenseList", description = "Returns all software license services on the account with their current status and IP assignments." , tags = {"Licenses"})
    @ApiResponse(responseCode = "200", description = "The listing of `Licenses` services on your account.")
    @ApiResponse(responseCode = "401", description = "Unauthorized")
    @Get(value = "/licenses", produces = { "application/json" })
    default Single<HttpResponse<List<LicenseRow>>> getLicenseList() {
        return Single.fromCallable(() -> {
            throw new UnsupportedOperationException();
        });
    }


    @Operation(summary = "Get License Order Information for Category", operationId = "getLicenseOrderCatTagInfo", description = "Returns the available license types and pricing for a specific license category. Use the category tags from `GET /licenses/order` to identify valid values." , tags = {"Licenses"})
    @ApiResponse(responseCode = "200", description = "License types and pricing for the specified category.")
    @ApiResponse(responseCode = "401", description = "Unauthorized")
    @Get(value = "/licenses/order/{catTag}", produces = { "application/json" })
    default Single<HttpResponse<Void>> getLicenseOrderCatTagInfo(@Parameter(description = "The license category tag (e.g. `cpanel`, `plesk`). Obtain valid values from the `GET /licenses/order` response.") @PathVariable("catTag") String catTag) {
        return Single.fromCallable(() -> {
            throw new UnsupportedOperationException();
        });
    }


    @Operation(summary = "Resend License Welcome Email", operationId = "getLicensesWelcomeEmail", description = "Resends the welcome email for the license service. The email contains the license key and activation instructions." , tags = {"Licenses"})
    @ApiResponse(responseCode = "200", description = "A response indicating the operation completed successfully with a text message.")
    @ApiResponse(responseCode = "401", description = "Unauthorized")
    @Get(value = "/licenses/{id}/welcome_email", produces = { "application/json" })
    default Single<HttpResponse<SuccessTextResponse>> getLicensesWelcomeEmail(@Parameter(description = "The license service ID. Use `license_id` from `GET /licenses`.") @PathVariable("id") Integer id) {
        return Single.fromCallable(() -> {
            throw new UnsupportedOperationException();
        });
    }


    @Operation(summary = "Get License Order Information", operationId = "getNewLicense", description = "Retrieves available license types, categories, and pricing for ordering a new license." , tags = {"Licenses"})
    @ApiResponse(responseCode = "200", description = "License ordering information.")
    @ApiResponse(responseCode = "401", description = "Unauthorized")
    @Get(value = "/licenses/order", produces = { "application/json" })
    default Single<HttpResponse<LicensesOrder>> getNewLicense() {
        return Single.fromCallable(() -> {
            throw new UnsupportedOperationException();
        });
    }


    @Operation(summary = "Cancel License", operationId = "licensesCancel", description = "Cancels a license service. After cancellation the license key is deactivated and the service transitions to a canceled status. No further billing charges will be incurred." , tags = {"Licenses"})
    @ApiResponse(responseCode = "200", description = "License Cancel")
    @ApiResponse(responseCode = "401", description = "Unauthorized")
    @Delete(value = "/licenses/{id}", produces = { "application/json" })
    default Single<HttpResponse<InlineResponse2004>> licensesCancel(@Parameter(description = "The license service ID. Use `license_id` from `GET /licenses`.") @PathVariable("id") Integer id) {
        return Single.fromCallable(() -> {
            throw new UnsupportedOperationException();
        });
    }


    @Operation(summary = "Change License IP", operationId = "postLicenseChangeIp", description = "Changes the IP address associated with the license. The service must be active. Use `GET /licenses/{id}` to view the current IP assignment before making changes." , tags = {"Licenses"})
    @ApiResponse(responseCode = "200", description = "A response indicating the operation completed successfully with a text message.")
    @ApiResponse(responseCode = "401", description = "Unauthorized")
    @Post(value = "/licenses/{id}/change_ip", produces = { "application/json" }, consumes = {"application/json", "multipart/form-data"})
    default Single<HttpResponse<SuccessTextResponse>> postLicenseChangeIp(@NotNull @Valid @Parameter(description = "") @Body IpObject body,@Parameter(description = "The license service ID. Use `license_id` from `GET /licenses`.") @PathVariable("id") Integer id) {
        return Single.fromCallable(() -> {
            throw new UnsupportedOperationException();
        });
    }


    @Operation(summary = "Change License IP", operationId = "postLicenseChangeIp", description = "Changes the IP address associated with the license. The service must be active. Use `GET /licenses/{id}` to view the current IP assignment before making changes." , tags = {"Licenses"})
    @ApiResponse(responseCode = "200", description = "A response indicating the operation completed successfully with a text message.")
    @ApiResponse(responseCode = "401", description = "Unauthorized")
    @Post(value = "/licenses/{id}/change_ip", produces = { "application/json" }, consumes = {"application/json", "multipart/form-data"})
    default Single<HttpResponse<SuccessTextResponse>> postLicenseChangeIp(@NotNull @Parameter(description = "") @Body(value = "ip")  String ip,@Parameter(description = "The license service ID. Use `license_id` from `GET /licenses`.") @PathVariable("id") Integer id) {
        return Single.fromCallable(() -> {
            throw new UnsupportedOperationException();
        });
    }


    @Operation(summary = "Validate License Order", operationId = "putLicenses", description = "Validates a license order before placing it. Use this to check for errors before committing to a purchase." , tags = {"Licenses"})
    @ApiResponse(responseCode = "200", description = "Validate Licenses order response")
    @ApiResponse(responseCode = "401", description = "Unauthorized")
    @Put(value = "/licenses/order", produces = { "application/json" })
    default Single<HttpResponse<Void>> putLicenses() {
        return Single.fromCallable(() -> {
            throw new UnsupportedOperationException();
        });
    }


    @Operation(summary = "Update License", operationId = "updateLicenseInfo", description = "Updates settings on a license service such as its assigned IP." , tags = {"Licenses"})
    @ApiResponse(responseCode = "200", description = "A response indicating the operation completed successfully with a text message.")
    @ApiResponse(responseCode = "401", description = "Unauthorized")
    @Post(value = "/licenses/{id}", produces = { "application/json" })
    default Single<HttpResponse<SuccessTextResponse>> updateLicenseInfo(@Parameter(description = "The license service ID. Use `license_id` from `GET /licenses`.") @PathVariable("id") String id) {
        return Single.fromCallable(() -> {
            throw new UnsupportedOperationException();
        });
    }

}
