<?php
/**
 * BackupOrderPostResponse
 *
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * InterServer Management API
 *
 * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@interserver.net
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use OpenAPI\Client\ObjectSerializer;

/**
 * BackupOrderPostResponse Class Doc Comment
 *
 * @description Backup Order Placement Response
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class BackupOrderPostResponse implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'BackupOrderPostResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'continue' => 'bool',
        'errors' => 'string[]',
        'total_cost' => 'string',
        'iid' => 'string',
        'iids' => 'string[]',
        'real_iids' => 'string[]',
        'service_id' => 'int',
        'invoice_description' => 'string',
        'cj_params' => '\OpenAPI\Client\Model\BackupOrderPostResponseCjParams'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'continue' => null,
        'errors' => null,
        'total_cost' => null,
        'iid' => null,
        'iids' => null,
        'real_iids' => null,
        'service_id' => 'int32',
        'invoice_description' => null,
        'cj_params' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'continue' => false,
        'errors' => false,
        'total_cost' => false,
        'iid' => false,
        'iids' => false,
        'real_iids' => false,
        'service_id' => false,
        'invoice_description' => false,
        'cj_params' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'continue' => 'continue',
        'errors' => 'errors',
        'total_cost' => 'total_cost',
        'iid' => 'iid',
        'iids' => 'iids',
        'real_iids' => 'real_iids',
        'service_id' => 'serviceId',
        'invoice_description' => 'invoice_description',
        'cj_params' => 'cj_params'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'continue' => 'setContinue',
        'errors' => 'setErrors',
        'total_cost' => 'setTotalCost',
        'iid' => 'setIid',
        'iids' => 'setIids',
        'real_iids' => 'setRealIids',
        'service_id' => 'setServiceId',
        'invoice_description' => 'setInvoiceDescription',
        'cj_params' => 'setCjParams'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'continue' => 'getContinue',
        'errors' => 'getErrors',
        'total_cost' => 'getTotalCost',
        'iid' => 'getIid',
        'iids' => 'getIids',
        'real_iids' => 'getRealIids',
        'service_id' => 'getServiceId',
        'invoice_description' => 'getInvoiceDescription',
        'cj_params' => 'getCjParams'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('continue', $data ?? [], null);
        $this->setIfExists('errors', $data ?? [], null);
        $this->setIfExists('total_cost', $data ?? [], null);
        $this->setIfExists('iid', $data ?? [], null);
        $this->setIfExists('iids', $data ?? [], null);
        $this->setIfExists('real_iids', $data ?? [], null);
        $this->setIfExists('service_id', $data ?? [], null);
        $this->setIfExists('invoice_description', $data ?? [], null);
        $this->setIfExists('cj_params', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets continue
     *
     * @return bool|null
     */
    public function getContinue(): ?bool
    {
        return $this->container['continue'];
    }

    /**
     * Sets continue
     *
     * @param bool|null $continue continue
     *
     * @return $this
     */
    public function setContinue(?bool $continue): static
    {
        if (is_null($continue)) {
            throw new InvalidArgumentException('non-nullable continue cannot be null');
        }
        $this->container['continue'] = $continue;

        return $this;
    }

    /**
     * Gets errors
     *
     * @return string[]|null
     */
    public function getErrors(): ?array
    {
        return $this->container['errors'];
    }

    /**
     * Sets errors
     *
     * @param string[]|null $errors errors
     *
     * @return $this
     */
    public function setErrors(?array $errors): static
    {
        if (is_null($errors)) {
            throw new InvalidArgumentException('non-nullable errors cannot be null');
        }
        $this->container['errors'] = $errors;

        return $this;
    }

    /**
     * Gets total_cost
     *
     * @return string|null
     */
    public function getTotalCost(): ?string
    {
        return $this->container['total_cost'];
    }

    /**
     * Sets total_cost
     *
     * @param string|null $total_cost total_cost
     *
     * @return $this
     */
    public function setTotalCost(?string $total_cost): static
    {
        if (is_null($total_cost)) {
            throw new InvalidArgumentException('non-nullable total_cost cannot be null');
        }
        $this->container['total_cost'] = $total_cost;

        return $this;
    }

    /**
     * Gets iid
     *
     * @return string|null
     */
    public function getIid(): ?string
    {
        return $this->container['iid'];
    }

    /**
     * Sets iid
     *
     * @param string|null $iid iid
     *
     * @return $this
     */
    public function setIid(?string $iid): static
    {
        if (is_null($iid)) {
            throw new InvalidArgumentException('non-nullable iid cannot be null');
        }
        $this->container['iid'] = $iid;

        return $this;
    }

    /**
     * Gets iids
     *
     * @return string[]|null
     */
    public function getIids(): ?array
    {
        return $this->container['iids'];
    }

    /**
     * Sets iids
     *
     * @param string[]|null $iids iids
     *
     * @return $this
     */
    public function setIids(?array $iids): static
    {
        if (is_null($iids)) {
            throw new InvalidArgumentException('non-nullable iids cannot be null');
        }
        $this->container['iids'] = $iids;

        return $this;
    }

    /**
     * Gets real_iids
     *
     * @return string[]|null
     */
    public function getRealIids(): ?array
    {
        return $this->container['real_iids'];
    }

    /**
     * Sets real_iids
     *
     * @param string[]|null $real_iids real_iids
     *
     * @return $this
     */
    public function setRealIids(?array $real_iids): static
    {
        if (is_null($real_iids)) {
            throw new InvalidArgumentException('non-nullable real_iids cannot be null');
        }
        $this->container['real_iids'] = $real_iids;

        return $this;
    }

    /**
     * Gets service_id
     *
     * @return int|null
     */
    public function getServiceId(): ?int
    {
        return $this->container['service_id'];
    }

    /**
     * Sets service_id
     *
     * @param int|null $service_id service_id
     *
     * @return $this
     */
    public function setServiceId(?int $service_id): static
    {
        if (is_null($service_id)) {
            throw new InvalidArgumentException('non-nullable service_id cannot be null');
        }
        $this->container['service_id'] = $service_id;

        return $this;
    }

    /**
     * Gets invoice_description
     *
     * @return string|null
     */
    public function getInvoiceDescription(): ?string
    {
        return $this->container['invoice_description'];
    }

    /**
     * Sets invoice_description
     *
     * @param string|null $invoice_description invoice_description
     *
     * @return $this
     */
    public function setInvoiceDescription(?string $invoice_description): static
    {
        if (is_null($invoice_description)) {
            throw new InvalidArgumentException('non-nullable invoice_description cannot be null');
        }
        $this->container['invoice_description'] = $invoice_description;

        return $this;
    }

    /**
     * Gets cj_params
     *
     * @return \OpenAPI\Client\Model\BackupOrderPostResponseCjParams|null
     */
    public function getCjParams(): ?\OpenAPI\Client\Model\BackupOrderPostResponseCjParams
    {
        return $this->container['cj_params'];
    }

    /**
     * Sets cj_params
     *
     * @param \OpenAPI\Client\Model\BackupOrderPostResponseCjParams|null $cj_params cj_params
     *
     * @return $this
     */
    public function setCjParams(?\OpenAPI\Client\Model\BackupOrderPostResponseCjParams $cj_params): static
    {
        if (is_null($cj_params)) {
            throw new InvalidArgumentException('non-nullable cj_params cannot be null');
        }
        $this->container['cj_params'] = $cj_params;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


