//
// ScrubIpPlaceOrder.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Place ScrubIP Order */
open class ScrubIpPlaceOrder: JSONEncodable {
    public var serviceType: Int32?
    public var ip: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["service_type"] = self.serviceType?.encodeToJSON()
        nillableDictionary["ip"] = self.ip

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
