/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.ServerNetworkInfoSwitchports
import org.openapitools.client.models.ServerSwitchport

class ServerNetworkInfoSwitchportsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ServerNetworkInfoSwitchports
        //val modelInstance = ServerNetworkInfoSwitchports()

        // to test the property `_10414`
        should("test _10414") {
            // uncomment below to test the property
            //modelInstance._10414 shouldBe ("TODO")
        }

    }
}
