/**
 * InterServer Management API
 * # Overview  The InterServer Management API provides programmatic access to manage your InterServer services. Use this REST API to automate provisioning, configuration, and billing operations across your account.  The API covers the following service categories: - [Domains](https://www.interserver.net/domains/) — registration, transfers, and DNS management - [Web Hosting](https://www.interserver.net/hosting/) — shared and reseller hosting - [VPS Hosting](https://www.interserver.net/vps/) — virtual private servers - [Dedicated Servers](https://www.interserver.net/dedicated/) — bare metal and [Rapid Deploy Servers](https://www.interserver.net/dedicated/rapid-deploy.html) - [Backups](https://www.interserver.net/storage/) — storage and backup services - Licenses — control panel and software licenses - [Mail](https://www.mail.baby/) — mail delivery services - SSL — certificate provisioning - Billing — invoices, payment methods, and account management  For interactive testing, see the [API documentation](/api-docs/).  # Authentication  Most endpoints require authentication. Two methods are supported:  ## API Key (Preferred)  Generate an API key from the [Account Security](https://my.interserver.net/account_security) page on [my.interserver.net](https://my.interserver.net/). Pass it in the `X-API-KEY` request header:  ``` X-API-KEY: your-api-key-here ```  ## Session-Based Authentication  Alternatively, authenticate by creating a session:  1. **Log in** — Send a `POST` request to `/login` with your account credentials. The response includes a session identifier. 2. **Pass the session ID** — Include the session identifier in the `sessionid` header on subsequent requests:  ``` sessionid: your-session-id-here ```  API key authentication is recommended for most integrations as it does not expire and avoids the overhead of session management.  
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { autoinject } from 'aurelia-framework';
import { HttpClient } from 'aurelia-http-client';
import { Api } from './Api';
import { AuthStorage } from './AuthStorage';
import {
  GetOauthRedirect200Response,
  PostOauthCallbackRequest,
  LoginSubmissionExampleGRecaptchaResponse,
  LoginInfo,
  CaptchaResponse,
  LoginSuccessResponse,
  LoginSubmissionExample,
  BuyItNowList,
  PatchOauthTwoFactorRequest,
  PatchOauthTwoFactor200Response,
  ServicesInfo,
  PostOauthCallback200Response,
} from './models';

/**
 * getCaptcha - parameters interface
 */
export interface IGetCaptchaParams {
}

/**
 * getCountries - parameters interface
 */
export interface IGetCountriesParams {
  fetchBy?: 'iso2' | 'iso3' | 'numcode';
}

/**
 * getInfo - parameters interface
 */
export interface IGetInfoParams {
}

/**
 * getLoginInfo - parameters interface
 */
export interface IGetLoginInfoParams {
}

/**
 * getMPServers - parameters interface
 */
export interface IGetMPServersParams {
}

/**
 * getOauthRedirect - parameters interface
 */
export interface IGetOauthRedirectParams {
  provider: string;
}

/**
 * getTimezones - parameters interface
 */
export interface IGetTimezonesParams {
}

/**
 * patchOauthTwoFactor - parameters interface
 */
export interface IPatchOauthTwoFactorParams {
  patchOauthTwoFactorRequest: PatchOauthTwoFactorRequest;
}

/**
 * pingServer - parameters interface
 */
export interface IPingServerParams {
}

/**
 * postOauthCallback - parameters interface
 */
export interface IPostOauthCallbackParams {
  provider: string;
  postOauthCallbackRequest?: PostOauthCallbackRequest;
}

/**
 * submitLogin - parameters interface
 */
export interface ISubmitLoginParams {
  login: string;
  passwd: string;
  remember?: string;
  gRecaptchaResponse?: LoginSubmissionExampleGRecaptchaResponse;
  tfa?: string;
}

/**
 * submitSignup - parameters interface
 */
export interface ISubmitSignupParams {
  loginSubmissionExample?: LoginSubmissionExample;
}

/**
 * PublicApi - API class
 */
@autoinject()
export class PublicApi extends Api {

  /**
   * Creates a new PublicApi class.
   *
   * @param httpClient The Aurelia HTTP client to be injected.
   * @param authStorage A storage for authentication data.
   */
  constructor(httpClient: HttpClient, authStorage: AuthStorage) {
    super(httpClient, authStorage);
  }

  /**
   * Get Captcha Challenge
   * Returns a base64-encoded JPEG captcha image for human verification. Display this image to the user and submit their response along with the registration or order form. No authentication is required for this endpoint.
   */
  async getCaptcha(): Promise<CaptchaResponse> {
    // Verify required parameters are set

    // Create URL to call
    const url = `${this.basePath}/captcha`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()

      // Authentication 'sessionIdCookieAuth' required
      // Authentication 'apiKeyAuth' required
      .withHeader('X-API-KEY', this.authStorage.getapiKeyAuth())
      // Authentication 'sessionIdHeaderAuth' required
      .withHeader('sessionid', this.authStorage.getsessionIdHeaderAuth())
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Get Countries
   * Returns a map of country codes to country names. Use the optional &#x60;fetch_by&#x60; parameter to select the key format: &#x60;iso2&#x60; (default, two-letter codes), &#x60;iso3&#x60; (three-letter codes), or &#x60;numcode&#x60; (numeric codes). Use these values when populating country fields in account registration or domain contact forms.
   * @param params.fetchBy Get countries by iso2 or iso3 or numcode
   */
  async getCountries(params: IGetCountriesParams): Promise<object> {
    // Verify required parameters are set

    // Create URL to call
    const url = `${this.basePath}/account/countries`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()
      // Set query parameters
      .withParams({ 
        'fetch_by': params['fetchBy'],
      })

      // Authentication 'sessionIdCookieAuth' required
      // Authentication 'apiKeyAuth' required
      .withHeader('X-API-KEY', this.authStorage.getapiKeyAuth())
      // Authentication 'sessionIdHeaderAuth' required
      .withHeader('sessionid', this.authStorage.getsessionIdHeaderAuth())
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Get Server Info
   * Returns metadata about the API server\&#39;s available modules, service packages, categories, and types. This public endpoint does not require authentication and is useful for discovering supported services before placing orders.
   */
  async getInfo(): Promise<ServicesInfo> {
    // Verify required parameters are set

    // Create URL to call
    const url = `${this.basePath}/info`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()

      // Authentication 'sessionIdCookieAuth' required
      // Authentication 'apiKeyAuth' required
      .withHeader('X-API-KEY', this.authStorage.getapiKeyAuth())
      // Authentication 'sessionIdHeaderAuth' required
      .withHeader('sessionid', this.authStorage.getsessionIdHeaderAuth())
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Get Login Info
   * Gets the various pieces of information useful for generating a login page.
   */
  async getLoginInfo(): Promise<LoginInfo> {
    // Verify required parameters are set

    // Create URL to call
    const url = `${this.basePath}/login`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()

      // Authentication 'sessionIdCookieAuth' required
      // Authentication 'apiKeyAuth' required
      .withHeader('X-API-KEY', this.authStorage.getapiKeyAuth())
      // Authentication 'sessionIdHeaderAuth' required
      .withHeader('sessionid', this.authStorage.getsessionIdHeaderAuth())
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * List Marketplace Servers
   * Returns the list of available Rapid Deploy dedicated servers with current pricing. Each entry includes CPU, memory, disk, bandwidth, IP allocation, and location details. These servers are pre-configured and can be provisioned immediately after purchase.
   */
  async getMPServers(): Promise<BuyItNowList> {
    // Verify required parameters are set

    // Create URL to call
    const url = `${this.basePath}/buy_now_servers_list`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()

      // Authentication 'sessionIdCookieAuth' required
      // Authentication 'apiKeyAuth' required
      .withHeader('X-API-KEY', this.authStorage.getapiKeyAuth())
      // Authentication 'sessionIdHeaderAuth' required
      .withHeader('sessionid', this.authStorage.getsessionIdHeaderAuth())
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Get OAuth Redirect URL
   * Returns the OAuth redirect URL for the specified provider. Redirect the user to this URL to begin the OAuth authentication flow. After the user authorizes, the provider will redirect back to your callback endpoint where you should call &#x60;POST /oauth&#x60;.
   * @param params.provider The OAuth provider name (e.g. &#x60;Google&#x60;).
   */
  async getOauthRedirect(params: IGetOauthRedirectParams): Promise<GetOauthRedirect200Response> {
    // Verify required parameters are set
    this.ensureParamIsSet('getOauthRedirect', params, 'provider');

    // Create URL to call
    const url = `${this.basePath}/oauth`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()
      // Set query parameters
      .withParams({ 
        'provider': params['provider'],
      })

      // Authentication 'sessionIdCookieAuth' required
      // Authentication 'apiKeyAuth' required
      .withHeader('X-API-KEY', this.authStorage.getapiKeyAuth())
      // Authentication 'sessionIdHeaderAuth' required
      .withHeader('sessionid', this.authStorage.getsessionIdHeaderAuth())
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Get Available Timezones
   * Returns the complete list of available timezone identifiers (e.g. &#x60;America/New_York&#x60;, &#x60;UTC&#x60;). Use these values when updating timezone settings on your account or on VPS and QuickServer services via &#x60;/vps/{id}/change_timezone&#x60; or &#x60;/qs/{id}/change_timezone&#x60;.
   */
  async getTimezones(): Promise<Array<string>> {
    // Verify required parameters are set

    // Create URL to call
    const url = `${this.basePath}/account/timezones`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()

      // Authentication 'sessionIdCookieAuth' required
      // Authentication 'apiKeyAuth' required
      .withHeader('X-API-KEY', this.authStorage.getapiKeyAuth())
      // Authentication 'sessionIdHeaderAuth' required
      .withHeader('sessionid', this.authStorage.getsessionIdHeaderAuth())
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Complete OAuth Two-Factor Verification
   * Completes the OAuth login by verifying a two-factor authentication code. Use the &#x60;account_id&#x60; returned by &#x60;POST /oauth&#x60; when the response contained &#x60;error_code: \&quot;2fa_required\&quot;&#x60;.
   * @param params.patchOauthTwoFactorRequest 
   */
  async patchOauthTwoFactor(params: IPatchOauthTwoFactorParams): Promise<PatchOauthTwoFactor200Response> {
    // Verify required parameters are set
    this.ensureParamIsSet('patchOauthTwoFactor', params, 'patchOauthTwoFactorRequest');

    // Create URL to call
    const url = `${this.basePath}/oauth`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asPatch()
      // Encode body parameter
      .withHeader('content-type', 'application/json')
      .withContent(JSON.stringify(params['patchOauthTwoFactorRequest'] || {}))

      // Authentication 'sessionIdCookieAuth' required
      // Authentication 'apiKeyAuth' required
      .withHeader('X-API-KEY', this.authStorage.getapiKeyAuth())
      // Authentication 'sessionIdHeaderAuth' required
      .withHeader('sessionid', this.authStorage.getsessionIdHeaderAuth())
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Ping Server
   * Performs a single ping/pong request to let you know if the server is up.
   */
  async pingServer(): Promise<string> {
    // Verify required parameters are set

    // Create URL to call
    const url = `${this.basePath}/ping`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()

      // Authentication 'sessionIdCookieAuth' required
      // Authentication 'apiKeyAuth' required
      .withHeader('X-API-KEY', this.authStorage.getapiKeyAuth())
      // Authentication 'sessionIdHeaderAuth' required
      .withHeader('sessionid', this.authStorage.getsessionIdHeaderAuth())
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * OAuth Callback
   * Handles the OAuth callback after the user authorizes with the provider. Returns the login status. If the account has two-factor authentication enabled, the response will include &#x60;error_code: \&quot;2fa_required\&quot;&#x60; and an &#x60;account_id&#x60;; use &#x60;PATCH /oauth&#x60; with the 2FA code and account ID to complete login.
   * @param params.provider The OAuth provider name (e.g. &#x60;Google&#x60;).
   * @param params.postOauthCallbackRequest 
   */
  async postOauthCallback(params: IPostOauthCallbackParams): Promise<PostOauthCallback200Response> {
    // Verify required parameters are set
    this.ensureParamIsSet('postOauthCallback', params, 'provider');

    // Create URL to call
    const url = `${this.basePath}/oauth`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asPost()
      // Set query parameters
      .withParams({ 
        'provider': params['provider'],
      })
      // Encode body parameter
      .withHeader('content-type', 'application/json')
      .withContent(JSON.stringify(params['postOauthCallbackRequest'] || {}))

      // Authentication 'sessionIdCookieAuth' required
      // Authentication 'apiKeyAuth' required
      .withHeader('X-API-KEY', this.authStorage.getapiKeyAuth())
      // Authentication 'sessionIdHeaderAuth' required
      .withHeader('sessionid', this.authStorage.getsessionIdHeaderAuth())
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Submit Login Information
   * Authenticates using the provided login credentials and returns a session token. Include the returned session ID in the &#x60;sessionid&#x60; header on subsequent requests. If authentication fails, a &#x60;402&#x60; error is returned.
   * @param params.login 
   * @param params.passwd 
   * @param params.remember 
   * @param params.gRecaptchaResponse 
   * @param params.tfa Two Factor Authentication Response.
   */
  async submitLogin(params: ISubmitLoginParams): Promise<LoginSuccessResponse> {
    // Verify required parameters are set
    this.ensureParamIsSet('submitLogin', params, 'login');
    this.ensureParamIsSet('submitLogin', params, 'passwd');

    // Create URL to call
    const url = `${this.basePath}/login`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asPost()
      // Encode form parameters
      .withHeader('content-type', 'application/x-www-form-urlencoded')
      .withContent(this.queryString({ 
        'login': params['login'],
        'passwd': params['passwd'],
        'remember': params['remember'],
        'g-recaptcha-response': params['gRecaptchaResponse'],
        'tfa': params['tfa'],
      }))

      // Authentication 'sessionIdCookieAuth' required
      // Authentication 'apiKeyAuth' required
      .withHeader('X-API-KEY', this.authStorage.getapiKeyAuth())
      // Authentication 'sessionIdHeaderAuth' required
      .withHeader('sessionid', this.authStorage.getsessionIdHeaderAuth())
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Submit Signup Information
   * Creates a new account in our system using the provided information.
   * @param params.loginSubmissionExample 
   */
  async submitSignup(params: ISubmitSignupParams): Promise<any> {
    // Verify required parameters are set

    // Create URL to call
    const url = `${this.basePath}/signup`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asPost()
      // Encode body parameter
      .withHeader('content-type', 'application/json')
      .withContent(JSON.stringify(params['loginSubmissionExample'] || {}))

      // Authentication 'sessionIdCookieAuth' required
      // Authentication 'apiKeyAuth' required
      .withHeader('X-API-KEY', this.authStorage.getapiKeyAuth())
      // Authentication 'sessionIdHeaderAuth' required
      .withHeader('sessionid', this.authStorage.getsessionIdHeaderAuth())
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

}

